### ISSUE TITLE
Front page notifications with translation support

### ISSUE THREAD

**Issue by leovegoda** [peeringdb/peeringdb#1095]
**Is your feature request related to a problem? Please describe.**
We should be able to make planned announcements to all website users on the front page. These announcements should be available whichever language the user chooses to use.

This approach was tested in English-only for the 2021 user survey and successfully increased user participation.

**Who is affected by the problem?**
The PeeringDB organization should be able to make announcements that are relevant to users of localized translations should not be excluded form announcements.

**What is the impact?**
A wider group of people will be able to participate in PeeringDB if they are aware of events, like the annual user survey or elections.

**Are there security concerns?**
No

**Are there privacy concerns?**
No

**Describe the solution you'd like**
A simple announcement box allowing a couple of sentences of text and an optional URL.

**Do you think this feature will require a formal design?**
It would be good to integrate with with the UX work if possible. 

**Describe alternatives you've considered**
None

**Could this feature request need support from the Admin Committee?**
It should not

**What is the proposed priority?**
Deploy by June, so we can use it for the annual user survey in September 2022.

**Provide a rationale for any/all of the above**
This should make a wider set of users aware of how they can influence PeeringDB through surveys, or governance events.

**Additional context**
As other work is planned for a generalized notifications framework, this implementation should be as simple as possible.

**Comment by grizz** [comment]
+1

@peeringdb/pc votes?

**Comment by martinhannigan** [comment]
This seems like more detail is needed.  Fundamentally, Im a yes. Aren’t
there more pressing translation issues?

**Comment by peterhelmenstine** [comment]
+1 more accessibility the better

**Comment by leovegoda** [comment]
> This seems like more detail is needed. 

Can you expand on that? What else do you want to know?

**Comment by martinhannigan** [comment]
Hi Leo,

Sure. How much effort would this be and at what cost? Where does it fit in
relation to other and possibly more important (and beneficial) translation
efforts?  Where will the translations come from? Will they cost anything?
What qualifies as a banner? Its a great idea. Used one time so far with no
demand that I can see. How many more times will it be used? What are the
benefits?

Im “fundamentally yes”  thinking this is a low priority.


Thanks

-M<

**Comment by arnoldnipper** [comment]
> How much effort would this be and at what cost? Where does it fit in relation to other and possibly more important (and beneficial) translation efforts? Where will the translations come from? Will they cost anything?

Translations are done by volunteers. Some of them are listed [here](https://docs.peeringdb.com/translation/#thanks-to-the-translators). I would love to see all of them listed there.

We use [Weblate](https://translate.peeringdb.com/) to organise the translations. As soon as a translation is mature (i.e. >= 80% translated) it is added to production

**Comment by mcmanuss8** [comment]
How would these notifications work with translations? I get that we could use the existing translation mechanism to translate the strings (assuming we design this well), but some of the notifications we might want to publish we wouldn't necessarily have time to get translated beforehand. For example, we might use this feature to send messages to users that were not planned well in advance:

* "Please fill in the 2023 PeeringDB User Survey!"
* "We're seeing significant performance degradation due to a problem with our hosting provider. Please bear with us while we work on it"
* "PeeringDB will be offline from X to Y for schedule maintenance"
* "Your API calls are harming the service availability for all PeeringDB users. Please throttle them or your access will be revoked" 

I'm for translations in general, I just want to be realistic that we would need to think a process mechanism to get these strings translated, else we're not really going to get the benefit. Similarly there might be strings that are short lived enough that we don't want to spend translator time on them if they are already inactive. The  design should account for:

* Notifications that we plan to use in the future or will likely reuse  - worth translating this
* Notifications that we probably won't use again and were sort of last minue - not worth translating these

**Comment by martinhannigan** [comment]
On Wed, Dec 22, 2021 at 1:17 PM mcmanuss8 ***@***.***> wrote:

[ clip ]


>
> I'm for translations in general, I just want to be realistic that we would
> need to think a process mechanism to get these strings translated, else
> we're not really going to get the benefit. Similarly there might be strings
> that are short lived enough that we don't want to spend translator time on
> them if they are already inactive. The design should account for:
>
>    - Notifications that we plan to use in the future or will likely reuse
>    - worth translating this
>
>
Agreed


>    - Notifications that we probably won't use again and were sort of last
>    minue - not worth translating these
>
>
Agreed.

Above you seemed to define [ at least ] two categories. Marketing and
Operations. The ops stuff is more easily translated since it should be
canned. I also think the "when" to use a banner is important. While the use
for the survey was a good one, there are uses that are not good and without
careful consideration (policy) we could end up quickly removing the value.

Warm regards,

-M<

**Comment by leovegoda** [comment]
> On Wed, Dec 22, 2021 at 1:17 PM mcmanuss8 ***@***.***> wrote: [ clip ]
> I'm for translations in general, I just want to be realistic that we would need to think a process mechanism to get these strings translated, else we're not really going to get the benefit. Similarly there might be strings that are short lived enough that we don't want to spend translator time on them if they are already inactive. The design should account for: - Notifications that we plan to use in the future or will likely reuse - worth translating this
> Agreed

This proposal is specifically for planned announcements that have a broad audience. My initial thoughts were the survey and the elections.

> - Notifications that we probably won't use again and were sort of last minue - not worth translating these
> Agreed. Above you seemed to define [ at least ] two categories. Marketing and Operations. The ops stuff is more easily translated since it should be canned. I also think the "when" to use a banner is important. While the use for the survey was a good one, there are uses that are not good and without careful consideration (policy) we could end up quickly removing the value. 

I agree that clear policy is vital in making sure that the value is not undermine by excessive use.

It's also worth noting that this is intended to be separate from the targeted notifications service, which would be an opportunity for users to design what are essentially search based notifications. As the users would be designing their own notifications in that case, they would be empowered to add, adjust, and remove them either through the website or the API.

**Comment by leovegoda** [comment]
> Hi Leo, Sure. How much effort would this be and at what cost? 

In our current process we get an effort estimate after there is a consensus for a proposal.

> Where does it fit in relation to other and possibly more important (and beneficial) translation efforts? 

As Arnold noted, we use Weblate for translations (https://translate.peeringdb.com/projects/peeringdb/#languages). We probably need to recruit some more translators and one of my hopes that was translating announcements for governance events, like the elections could help there. My thought was that this could help us power up by bringing in some more volunteers.

**Comment by grizz** [comment]
After thinking about this more, there might be a fair amount of work to add translations to this because of how they are compiled, adding a notice to the top itself is quite simple / easy.

**Comment by leovegoda** [comment]
Closing as we will redesign the front page as part of a website update
