### ISSUE TITLE
fix issue from DeskPRO #2116

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#117]
User says: We were updating information of our PeeringDB page ( Lan details and all our member listed data got vanished.  We have updated the information but we are not able to find any of our members listing

**Comment by vegu** [comment]
The old ixlan got deleted and alongside all network relations to it, looking at the current state it seems like restoration is already under way to a new ixlan , at this point there appears to be at least 50 networks still missing from the new ixlan (compared vs the old one) - do you want us to restore the remaining network relations and move them to the new lan?

**Comment by vegu** [comment]
Looking into the cause there appears no signs of a bug (at least according to the server logs all seems to be in order), it shows that the ixlan was deliberately deleted, did the user say otherwise? If it was an UI issue, need more details.

I do think an additional warning on the ixlan deletion confirmation stating that network relationships to the ix via that ixlan will be removed as well is required so i went ahead and made that change in #119

**Comment by arnoldnipper** [comment]
Yes, a double confirmation would be useful her
