### ISSUE TITLE
missing delete button for organisations

### ISSUE THREAD

**Issue by kieber** [peeringdb/peeringdb#121]
Every org should be permitted to be deleted by an admin user of that org.  It may be sensible to force the admin to disassociated the org from any facility, network or exchange before deleting the org itself.

Every user should be permitted to delete his/her own account.

**Comment by vegu** [comment]
About to implement this, was wondering if we should protect these actions by something more involved than a Yes/No confirmation dialogue, as having to undo an accidental deletion of an org o r a user account can lead to a potentially large amount of extra work for admincom.

I was thinking maybe in order to have a user confirm these removals they have to type "delete" into the confirmation dialogue before clicking "Yes"

Thoughts?

**Comment by eloos** [comment]
@vegu I believe we should indeed have an explicit warning dialogue that explains what they are about to delete and that it will be impossible to restore it and will require them to re-enter all data. I would also add that if they are struggling with something that they should contact support (provide link). After that rather than 'delete' i would opt for the phrase 'agreed and understood'

**Comment by arnoldnipper** [comment]
Deletion of an organisation should be impossible as long as there are records associated with it. That way we more or less guarantee that the deletion is **not** done accidently. 

What do you think?

**Comment by eloos** [comment]
@arnoldnipper: I am trying to imagine the use-cases in the current context of PDB and I would believe that in most cases this would be the 'dying gasp' of an admin that wants to show that the PDB entry will no longer be maintained. Making it cumbersome to do so will reduce the data quality.
On the other hand, how do we protect against an admin account acting in malice? Could we send an email notification to all admin accounts and merely mark the objects as 'stale' (there we go again with #61) and consider them that stale we no longer show them? Then we delete them after 7 days unless we receive a notification?

**Comment by arnoldnipper** [comment]
Reagrding a malice admin @eloos ... we already do not care today. And shouldn't as this violates or paradigm that the networks take care od their data.

Otoh it might improve PeeringDB if we introduce a couple of notify options (affiliation requests, add / delete of records, change of records)

**Comment by fhibler** [comment]
I do like the idea marking an entry as 'stale' (or maybe 'pending deletion') and just remove them from all search results. But I would keep this status for at least 1 month (due to PTO etc. it is more sensible to keep it longer than 7 days).

**Comment by nopedial** [comment]
+1 on what @fhibler said - keeping the 'stale'/'pending deletion' record for longer than 7 days is probably wise.

**Comment by mcmanuss8** [comment]
+1 keeping the record around after deletion. Ideally we would move deleted records to an archive table for easy recovery against malicious (recently laid off for example) admin action.

**Comment by arnoldnipper** [comment]
Summarise: currently, an admin is able to delete everything but the org itself. According to our paradigm that the data is user-maintained, we should add a button to do so. How to handle this if operational data is affected should be discussed in a separate ticket.

@peeringdb/pc and @ccaputo what do you think?

**Comment by arnoldnipper** [comment]
+1

**Comment by ccaputo** [comment]
I trust that an "org" record could not be deleted if there are remaining other records pointing to it, such as "net" and "ix" records.

I will soon be proposing to the Data Ownership Task Force language along these lines:

'In order to prevent operational disruption, this Task Force recommends that PeeringDB be modified to prevent deletion or updates of "ix", "ixlan", and "ixpfx" data elements from having a disruptive effect on dependent "netixlan" data elements.  When needed, the removal of dependent data elements should be coordinated by the Admin Committee.'

**Comment by shane-kerr** [comment]
@arnoldnipper it's not clear to me if the proposal for the PC is to immediately delete the org or to move it to a "pending delete" or archive state as mentioned by @fhibler and supported by @mcmanuss8.

**Comment by arnoldnipper** [comment]
@shane-kerr, the proposal is to add a knob in the GUI. Currently, the user have to send an email to [AC](support@peeringdb.com) to have the `org` deleted.  And as mentioned before **how to handle this request if operational data is affected should be discussed in a separate ticket**. Makes sense?

**Comment by shane-kerr** [comment]
+1 

This is simply for the deletion button for org, and not for the "softer" and possibly more robust method where orgs are turned into zombie objects for a while. My understanding is that will either be handled as a separate ticket (if someone wants to propose that) or not at all.

Given that a bad actor can already delete everything else, I don't see any reason not to let them finish their reign of destruction. :wink:

**Comment by arnoldnipper** [comment]
> Given that a bad actor can already delete everything else, I don't see any reason not to let them finish their reign of destruction. 😉

Exactly, an admin can delete all but the org and users.

**Comment by mcmanuss8** [comment]
+1 to make this button - can we link the separate issue here for posterity please?

**Comment by grizz** [comment]
I'm a bit late to the game here but how often are orgs actually deleted? I think that we could focus time and effort on something more pressing, no?

From the way the db works, it would be a soft delete, not a hard delete -- just for the record.

**Comment by arnoldnipper** [comment]
@grizz it's about **deciding** whether to have this button or not. This does not imply to implement it right away. Hence a more robust roadmap would make sense. Then we could say that it will be implemented with 3.11.0 (e.g.)

**Comment by grizz** [comment]
Ohhh, now I understand, thank you. +1 from me

**Comment by grizz** [comment]
To summarize: an admin user should be able to delete an org if it has no live objects under it.

**Comment by arnoldnipper** [comment]
**Release Note**

New feature. An admin user is able to delete an org if it has no live objects under it.
