### ISSUE TITLE
Last updated field only updates on content of the entry, not LAN/FAC updates

### ISSUE THREAD

**Issue by martzuk** [peeringdb/peeringdb#129]
_Hi Marty,

the "Last Updated" field only changes if you change something related to the *network*. Adding an entry to an IXP is manipulating a different object (netixlans).I've changed your "Notes" field by removing the "anycast" and adding it again. As you can see the "Last updated" changed.

Cheers,
Arnold_

I think any update to the PeeringDB entry (either updating the record itself or changing IXP IPs or private facilities) should update the last updated time.

**Comment by eloos** [comment]
this approach is consistent with querying the API and asking only for objects changed since 'x', if the entire net object would be considered update, the entire peeringdb record and referenced records should all need to be offered as updated too.
From a consistency point of view and based on the fact that this would require a backend implementation, I would strongly argue against implementing this

**Comment by eloos** [comment]
@martzuk does this make sense to you?

**Comment by martzuk** [comment]
@eloos yup
