### ISSUE TITLE
OAuth2 flow fails to complete when using U2F Security Key

### ISSUE THREAD

**Issue by KittensAreDaBest** [peeringdb/peeringdb#1294]
**Describe the bug**
Cannot complete the OAuth2 flow when using U2F Security Key.

**To Reproduce**
1. Go to a application that uses OAuth2 (eg: https://peering.cloudflare.com/ )
2. Login to your PeeringDB account
3. Choose U2F Security Key as an authentication method
4. After completion it redirects to https://auth.peeringdb.com and not back to peering.cloudflare.com

**Expected behavior**
After doing the 2fa authentication to redirected back to peering.cloudflare.com (which works with TOTP)

**Who is affected by the problem?**
People that use U2F Security Key authentication 

**What is the impact?**
People that primarily use U2F Security Key authentication on PeeringDB being unable to use OAuth2 applications that use PeeringDB

**Are there security concerns?**
none

**Are there privacy concerns?**
none

**Comment by grizz** [comment]
@KittensAreDaBest Thanks for the report. I just tested and it works as expected for me.

Are you using MFA as well? (Feel free to email and take this out of public info as well).

**Comment by KittensAreDaBest** [comment]
Yeah, I am using MFA.

I also can take a video of the flow failing also if you want.

**Comment by grizz** [comment]
@KittensAreDaBest Sure, that could be helpful, I'm unable to reproduce.

Thanks!

**Comment by nicoduck** [comment]
I just had the same issue. I use a yubikey as 2FA device and don't have passwordless login activated.
Tried to login to the cloudflare peering portal but got redirected to the normal PDB landing page.
Tried multiple times with both Chrome and Firefox (on my PC) and always got the same result.
Deactivated MFA and the login worked. 
Reactivated 2FA and the issue came back.

**Comment by nicoduck** [comment]
I created a screen recording of the workflow.
It's accessible for the next 4 weeks here: https://nc.4nx.de/s/3j2miTMgqY5yTym
I also saw that my account doesn't have the "2FA" flag, when having a look at all accounts authorized for our organization. Maybe something is half-broken because I don't have TOTP activated but solely security keys?

**Comment by benjojo** [comment]
X-Linking https://github.com/peeringdb/peeringdb/issues/1191 since it's the same issue

**Comment by leovegoda** [comment]
@KittensAreDaBest Resolving #1191 ought to have resolved this issue, too. Do you still see it?

**Comment by KittensAreDaBest** [comment]
Yeah, seems to work now /w security key
