### ISSUE TITLE
display website URL on all non-org objects

### ISSUE THREAD

**Issue by grizz** [peeringdb/peeringdb#1300]
The field is added to carrier but was not being displayed.

We should display it, and fall back to org website URL if not set.

@peeringdb/pc vote quick and we can get this in now :)

**Comment by peterhelmenstine** [comment]
Would def prefer pulling from org data over adding another field to enter data. $0.02

**Comment by mcmanuss8** [comment]
Let's rescope this a bit - instead of doing this on carrier, let's do this for *all* (non org) objects:

1.  Rename (in the *editing* ui, skip the api) the website field to be "website override". Add a tooltip in that ui that says "If this field is set, it will be displayed on this record. If not, we will display the website from the organization record this is tied to" 
2. On the UI, If the child (net, ix, fac, carrier) object has a null website field, show the website of the parent org object  [ coalesce(child.website, org.website) in mysql parlance) 
3. Optionally do the same as 2 on the api but I don't think that's super important to do

**Comment by grizz** [comment]
+1

**Comment by martinhannigan** [comment]
+1

**Comment by mustangthz** [comment]
+1

**Comment by grizz** [comment]
**Summary**

> * Rename (in the _editing_ ui, skip the api) the website field to be "website override". Add a tooltip in that ui that says "If this field is set, it will be displayed on this record. If not, we will display the website from the organization record this is tied to"
> * On the UI, If the child (net, ix, fac, carrier) object has a null website field, show the website of the parent org object  [ coalesce(child.website, org.website) in mysql parlance)
> * Optionally do the same as 2 on the api but I don't think that's super important to do
