### ISSUE TITLE
Duplicate content served via peeeringdb

### ISSUE THREAD

**Issue by bogdanrotariu** [peeringdb/peeringdb#1316]
**Describe the bug**

Accessing https://anything.peeringdb.com shows the same content instead of redirect to www.peeringdb.com or tools.peeringdb.com

**To Reproduce**
$ curl --head https://anything.peeringdb.com/ix/26
HTTP/1.1 200 OK

**Expected behavior**
$ curl --head https://anything.peeringdb.com/ix/26
HTTP/1.1 301 Moved Permanently
location: https://www.peeringdb.com/ix/26

**Who is affected by the problem?**
everyone

**What is the impact?**
I think the impact is very large as it affects all the information stored in peeringdb, as the search engines indexed the content from hundreds of locations and gives penalties

**Are there security concerns?**
No
**Are there privacy concerns?**
No
**What are the proposed actions?**
Rethink the subdomain, redirect and do not serve content that should not be supposed to be on that subdomain.

**What is the proposed priority?**
high

**Comment by grizz** [comment]
PeeringDB uses the canonical link tag to let search engines know where it's referenced.

```sh
$ curl https://anything.peeringdb.com | grep canonical
<link rel="canonical" href="https://www.peeringdb.com/" />
```

That said, we should probably see what needs to be there and what doesn't and tighten up the requirements.

+1 from me, @peeringdb/oc am I forgetting a reason behind having this?

**Comment by ccaputo** [comment]
I experimented with this and coded up the nginx config for it:

```
if ($host !~* "^www.peeringdb.com$") {
     return 301 https://www.peeringdb.com$request_uri;
}
```

Couldn't test on beta for obvious reasons, so tested with the API production instances first and then rolled it to general non-API production. Tested our existing redirects and then wildcard FQDNs and things seem fine. Give things a try and let me know if I should revert.

Otherwise, we can ansible it as follows:

```
- 'if ($host !~* "^{{peeringdb_vhost}}$")
     {
     return 301 https://{{peeringdb_vhost}}$request_uri;
     }'
```

I did find that direct (ie. load-balancer bypass) queries to instances from admin bastions, such as for monitoring, will break with this, but I think that is okay since our load-balancer healthchecker now verifies database connectivity (https://github.com/peeringdb/peeringdb/issues/1284).

I haven't thought of any other reasons to not leave this experimental redirect in place. Anyone else on @peeringdb/oc recall anything? Also, @peeringdb/ac FYI in case anyone reports any problems.

**Comment by peterhelmenstine** [comment]
+1

**Comment by ccaputo** [comment]
> I experimented with this and coded up the nginx config for it:

auth.peeringdb.com is now being exempted from the redirection, so that oauth efforts aren't delayed by a redirect. Other exceptions can be added if needed.

**Comment by grizz** [comment]
Perfect, thanks Chris!

**Comment by leovegoda** [comment]
@ccaputo I think we can close this now. Is that right?

**Comment by ccaputo** [comment]
> @ccaputo I think we can close this now. Is that right?

No, I don't think so. The work is not yet complete in a deployable form - not yet ansiblized - nor do I know that the issue has been decided in a @peeringdb/pc sense such that it should be formalized. Does Ops have the go-ahead from @peeringdb/pc to code this up for the long term?

**Comment by mcmanuss8** [comment]
Not yet but +1 from me-Steve(from iPhone - expect typos)On Feb 28, 2023, at 6:26 PM, Chris Caputo ***@***.***> wrote:﻿

@ccaputo I think we can close this now. Is that right?

No, I don't think so. The work is not yet complete in a deployable form - not yet ansiblized - nor do I know that the issue has been decided in a @peeringdb/pc sense such that it should be formalized. Does Ops have the go-ahead from @peeringdb/pc to code this up for the long term?

**Comment by arnoldnipper** [comment]
+1

**Comment by ccaputo** [comment]
Ansibled and done.
