### ISSUE TITLE
Show in the API when a facility is part of a campus

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#1340]
**Is your feature request related to a problem? Please describe.**
We should make it easy for users to detect via the API when a `fac`is a part of a `campus`. This creates also feature parity to #1336.

**Who is affected by the problem?**

PeeringDB users searching for a `fac` can clearly see when it is part of a `campus`

**What is the impact?**
Improve the user experience for everyone

**Are there security concerns?**
no

**Are there privacy concerns?**
no

**Describe the solution you'd like**

Depending on the outcome of the question: Can a `fac` be a member of more than 1 `campus`?

- yes: create a `faccampus` object the same way as e.g. `netfac`
- no: add a field `campus_id` to the `fac`object

**Do you think this feature will require a formal design?**
yes, as at least a new field must be added to an object

**What is the proposed priority?**
Ideally in sync with #1336

**Comment by martinhannigan** [comment]
Id like to understand a bit more before being onboard on how this works beyond the icon since it was brought up in 1136 that a building may be able to be part of multiple campuses. How does that work?


Thanks!

-M<

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Arnold Nipper ***@***.***>
Sent: Monday, March 6, 2023 15:06
To: peeringdb/peeringdb ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [peeringdb/peeringdb] Clearly show in the API when a facility is part of a campus (Issue #1340)


Is your feature request related to a problem? Please describe.
We should make it easy for users to detect via the API when a facis a part of a campus. This creates also feature parity to #1336<https://github.com/peeringdb/peeringdb/issues/1336>.

Who is affected by the problem?

PeeringDB users searching for a fac can clearly see when it is part of a campus

What is the impact?
Improve the user experience for everyone

Are there security concerns?
no

Are there privacy concerns?
no

Describe the solution you'd like

Depending on the outcome of the question: Can a fac be a member of more than 1 campus?

  *   yes: create a faccampus object the same way as e.g. netfac
  *   no: add a field campus_id to the facobject

Do you think this feature will require a formal design?
yes, as at least a new field must be added to an object

What is the proposed priority?
Ideally in sync with #1336<https://github.com/peeringdb/peeringdb/issues/1336>

**Comment by mustangthz** [comment]
I'd say the outcome to should a facility be part of multiple campuses is no.  

With that, I don't see a problem with adding a field campus_id to the fac object.

**Comment by arnoldnipper** [comment]
> The physical address ”should or must” be neutral and not in a campus IMHO.

The `campus` object does not have address{1,2} fields. And even if, this is not subject of this issue

**Comment by martinhannigan** [comment]
If this is what the search result will contain:

https://www.peeringdb.com/campus/25

It leads to this:

https://www.peeringdb.com/fac/13346

I agree that campus doesn’t show an address. However, it leads back to exactly the concern that I described – unauthorized entities creating the perception that they control a building when they really don’t which limits competition and choice for PDB users.

Not certain how to solve and could probably go ahead. If this will be solved in PDB 3, then I may be able to agree.


Thanks –

-M<



From: mustangthz ***@***.***>
Date: Tuesday, March 7, 2023 at 8:15 PM
To: peeringdb/peeringdb ***@***.***>
Cc: Martin Hannigan ***@***.***>, Comment ***@***.***>
Subject: Re: [peeringdb/peeringdb] Clearly show in the API when a facility is part of a campus (Issue #1340)
AgreedOn Mar 7, 2023, at 6:53 PM, Arnold Nipper ***@***.***> wrote:﻿

The physical address ”should or must” be neutral and not in a campus IMHO.

The campus object does not have address{1,2} fields. And even if, this is not subject of this issue

**Comment by arnoldnipper** [comment]
> However, it leads back to exactly the concern that I described – unauthorized entities creating the perception that they control a building when they really don’t which limits competition and choice for PDB users.

Your concerns are outside the scope of this issue. This issue deals with getting feature parity to what has been acked by @peeringdb/pc in #1336

**Comment by martinhannigan** [comment]
On Wed, Mar 8, 2023 at 11:59 AM Arnold Nipper ***@***.***>
wrote:

> However, it leads back to exactly the concern that I described –
> unauthorized entities creating the perception that they control a building
> when they really don’t which limits competition and choice for PDB users.
>
> Your concerns are outside the scope of this issue. This issue deals with
> getting feature parity to what has been acked by @peeringdb/pc
> <https://github.com/orgs/peeringdb/teams/pc> in #1336
> <https://github.com/peeringdb/peeringdb/issues/1336>
>

How are questions out of scope? Demanding changes which are completely
unrelated certainly out of scope (see your comments regarding 230v, on
another approved issue.)

I haven’t seen a full ack and commit on this. As I noted, I want to
understand better the workflow so we don’t end up with confusion and
collission as a result of implementation of this feature which on its face
looks OK. Trying to get these collisions resolved later, if history repeats
itself, will be unreasonably difficult (see Verizon and 200 S. Virginia).

So -1.

Happy to have a rational discussion about workflow. Let’s not try and
railroad things through for the sake of “parity” without thinking things
through.

**Comment by arnoldnipper** [comment]
If this issue is not thought through, then #1336 also not is. However, that is approved. Now apply some logics.

**Comment by arnoldnipper** [comment]
**Summary**

It's consensus that a facility can only be a member of one campus. Hence a field `campus_id` should be added to the `fac` object.

@peeringdb/pc, please ACK

**Comment by martinhannigan** [comment]
That may not accurate. You could have multiple tenants in a same facility
with different secondary addresses, comprising multiple campuses.

**Comment by peterhelmenstine** [comment]
+1 Should be consistent with what was already approved.

**Comment by martinhannigan** [comment]
As long as multiple facilities can be at the same address.  This further reflects how broken the subordination of facility to address is and the use of facility to really mean a company at multiple addresses.

The issue request actually doesnt set that limit. It appears nom essential and Im concerned once again we’re going to limit competition as a result.

-1 for now.



Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by martinhannigan** [comment]
Here’s an example:

https://www.peeringdb.com/org/7841
https://www.peeringdb.com/fac/1517

And:

https://www.peeringdb.com/fac/1517

Does DE-CIX have their own space at 60 Hudson direct with the landlord? Why doesn’t the 60 Hudson org record have contact information so anyone can reach out to the landlord and make a space request as a result of a PDB search? Is DE-CIX eligible to create a campus in NYC since they have multiple facilities? If they did, would that then restrict any other IXP from saying they had a campus that included 60 Hudson?

While campus is a good idea, limiting it at this early stage is likely to create scenarios where someone on the AC denies legitimate requests based on our agreement without any experience with the use of a new object.

I hope we can always help the less powerful and cash rich to enjoy the benefits of PDB with the same lack of pain as big data centers and commercial IX’s enjoy.

Hope that helps.

Thanks –

-M<


From: Peter Helmenstine ***@***.***>
Date: Sunday, July 2, 2023 at 10:13 PM
To: peeringdb/peeringdb ***@***.***>
Cc: Martin Hannigan ***@***.***>, Comment ***@***.***>
Subject: Re: [peeringdb/peeringdb] Show in the API when a facility is part of a campus (Issue #1340)

+1 Should be consistent with what was already approved.

**Comment by peterhelmenstine** [comment]
This is a feature parity issue on something that was previously decided and voted on. This is simply to make that functionality consistent.

If there’s an issue with the way the Campus object works then that should be part of the original campus creation discussion. Not here.

That said… I’m still not understanding how PeeringDB is limiting any legitimate requests. Can you reference a ticket/request?

I don’t believe DE-CIX has their own space at 60 Hudson direct with the landlord but you’d have to ask them. 

The 60 Hudson org record probably does not have contact information because they haven’t submitted it. Pretty common with old telco hotel facility entries.

Not sure why DE-CIX would create any facility entries as they are traditionally an IX operator as far as I’m aware.

Maybe I’m not following but in any case this is simply an issue to fix the API to be consistent with previous consensus.

**Comment by arnoldnipper** [comment]
> Maybe I’m not following but in any case this is simply an issue to fix the API to be consistent with previous consensus.

+1 ... this missing field also prohibits that https://tutorial.peeringdb.com can work properly (campus objects are missing)

**Comment by martinhannigan** [comment]
Inline

From: Peter Helmenstine ***@***.***>
Date: Monday, July 3, 2023 at 12:16 AM
To: peeringdb/peeringdb ***@***.***>
Cc: Martin Hannigan ***@***.***>, Comment ***@***.***>
Subject: Re: [peeringdb/peeringdb] Show in the API when a facility is part of a campus (Issue #1340)

This is a feature parity issue on something that was previously decided and voted on. This is simply to make that functionality consistent.



Thanks. You referenced what was in the issue and I’m queuing off exactly what the issue says. In the discussions I don’t recall declaring consensus on this particular policy issue and if we’ve already agreed I’m not sure why this came up anyhow.

If there’s an issue with the way the Campus object works then that should be part of the original campus creation discussion. Not here.

That said… I’m still not understanding how PeeringDB is limiting any legitimate requests. Can you reference a ticket/request?

200 SV,  when one party requested a FAC object be created, but the AC instead mistakenly determined Verizon owned the facility and without Verizon asking for it (or being asked) it was assigned it to them based on a six year old PDF for local network sales offerings? There’s more. There’s a pattern of unnecessarily limiting competition.

I don’t believe DE-CIX has their own space at 60 Hudson direct with the landlord but you’d have to ask them.

I don’t either, but it’s an example that if another IXP wanted “parity” I have a strong suspicion they would not be able to be associated with the 60 Hudson org. Concerning.

The 60 Hudson org record probably does not have contact information because they haven’t submitted it. Pretty common with old telco hotel facility entries.

Perhaps the solution there is to disallow any association with an unclaimed Org? For another issue.

Not sure why DE-CIX would create any facility entries as they are traditionally an IX operator as far as I’m aware.

Agree. They could. And as long as it’s legitimate they should.

Maybe I’m not following but in any case this is simply an issue to fix the API to be consistent with previous consensus.

I agree we should have feature parity but objects are for different things and I doubt 100% feature parity makes sense or is required. What I don’t want to do is set policy in creating these new objects or feature where we have no experience.

It would be helpful if the AC could put a monthly report up showing all rejections of created objects to help everyone learn if it’s really not a problem.

**Comment by arnoldnipper** [comment]
> I agree we should have feature parity but objects are for different things and I doubt 100% feature parity makes sense or is required.

100% feature parity between GUI and API was decided by the PC

**Comment by mcmanuss8** [comment]
+1 we should add this

**Comment by grizz** [comment]
+1

**Comment by martinhannigan** [comment]
+1

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by grizz** [comment]
This will be completed with #1352 

`faccampus` object is not required.
