### ISSUE TITLE
Intermittent issue with api/carrier incremental updates

### ISSUE THREAD

**Issue by vegu** [peeringdb/peeringdb#1351]
**Describe the bug**

Currently its possible for a carrier object to break the `/api/carrier?since={timestamp}` endpoint. This happens when there is no website specified on a soft-deleted carrier. Carriers with empty website property are supposed to pass through the website property of the parent organization, and issue seems to relate to that.

**Who is affected by the problem?**

People using the api to sync and ops / devs having to fix the data issue manually to make the error go away.

**Comment by ccaputo** [comment]
@peeringdb/pc I think this is important to fix ASAP (if reasonable: prior to next prod release) since this will unexpectedly break peeringdb-py sync's resulting in lower adoption of a tool we want to encourage. Please consider.

**Comment by martinhannigan** [comment]
+1

From: Chris Caputo ***@***.***>
Date: Wednesday, March 15, 2023 at 11:00 AM
To: peeringdb/peeringdb ***@***.***>
Cc: Martin Hannigan ***@***.***>, Team mention ***@***.***>
Subject: Re: [peeringdb/peeringdb] Intermittent issue with api/carrier incremental updates (Issue #1351)

@peeringdb/pc<https://github.com/orgs/peeringdb/teams/pc> I think this is important to fix ASAP (if reasonable: prior to next prod release) since this will unexpectedly break peeringdb-py sync's resulting in lower adoption of a tool we want to encourage. Please consider.

**Comment by mcmanuss8** [comment]
This feels like a clear bug so we shouldn't need to vote on it.

**Comment by ccaputo** [comment]
> This feels like a clear bug so we shouldn't need to vote on it.

Superduper. How do we evaluate if it makes sense to slip into the upcoming production release?

**Comment by mcmanuss8** [comment]
I'll defer to @grizz  and @leovegoda on that one. I support getting it done in the next release.
