### ISSUE TITLE
Clarifying the Network Type field

### ISSUE THREAD

**Issue by martinhannigan** [peeringdb/peeringdb#1357]
**Is your feature request related to a problem? Please describe.**

The net object has a field called Network Type. The purpose of this field isn't completely clear or remembered, but its easy to conclude its supposed to tell a user of PDB what kind of network it is. There are a number of choices that one can make from a drop down menu if they choose.

They are:

- Not Disclosed
- NSP
- Content
- Cable/DSL/ISP
- Enterprise
- Education/Research
- Non-Profit
- Route Server
- Network Services
- Route Collector
- Government

That's fairly unclear holistically. 

[ PeeringDB PC Hat on: We agreed to kick-start this question hence the issue creation ]

**Who is affected by the problem?**

Users of PeeringDB

**What is the impact?**

Unclear nomenclature in a field and potential waste of valuable screen space.

**Are there security concerns?**

No.

**Are there privacy concerns?**

No.

**Describe the solution you'd like**
We could change to the following list to create clarity:

- Content, Cloud, Compute
- Enterprise Network Operator
- Education Network Operator
- Internet Service Provider
- Other

On a personal note, the argument to not include the others is its dubious that anyone is searching for route servers or route collectors as a default to peer with. Same for non-profit, government. 

**Do you think this feature will require a formal design?**
yes/no (add why if no):

No. There's already a drop down list that could be updated.

**Describe alternatives you've considered**

Easy to do nothing and truck on. However, one of our goals is to improve the UI and this falls into that category IMHO.

Delete the field entirely. If we can't reach consensus the alternative option is to probably deprecate this field entirely. The failure to reach consensus could be a decent indicator of how confusing this really is e.g. peering, paid peering, partial peering, etc.

**Could this feature request need support from the Admin Committee?**

No.

Consider if an administrator might need to provide assistance at any point.

Doubtful.

**What is the proposed priority?**

As time permits.

**Provide a rationale for any/all of the above**

See the other parts of the issue.

**Additional context**

Thanks for commenting and giving the PC guidance.

**Comment by leovegoda** [comment]
@martinhannigan If we get consensus on this, how should networks whose type does not fit into the new list be handled?

**Comment by martinhannigan** [comment]
We should probably look at how many are set and to what to ascertain scope
of the question.

**Comment by arnoldnipper** [comment]
> We should probably look at how many are set and to what to ascertain scope

```
    396
   9791 Cable/DSL/ISP
   2082 Content
   1203 Educational/Research
   1382 Enterprise
     68 Government
   3426 NSP
    449 Network Services
    564 Non-Profit
   7262 Not Disclosed
     22 Route Collector
    525 Route Server
```

I.e. only  1.45% don't use `info_type`

**Comment by leovegoda** [comment]
> -1 ... in general, we are lacking documentation. And IMO, it should go there.

Whatever the outcome of this discussion, we should definitely document the outcome.

**Comment by martinhannigan** [comment]
Good data. I’m less certain this field/data is any different than inbound, outbound or balanced ratio notations. The vast direction of traffic for the list by default (for example) was “inbound” which implies “eyeballs”. The heavy outbound category would be content/cloud (which cloud is understood to mean compute). Balanced ratios usually means Telco.

This could cover everything if we want simple pointers:


  *   ISP
  *   Content Cloud
  *   Telco

There are corner cases where someone will be confused if we made such a change like an IT admin at an $company saying “we’re not an ISP!” because they don’t really understand they’re providing internet service to users just like an ISP. Many of these terms are from a day of immaturity of the internet.  Cable/DSL/ISP makes little sense for example. In 1999 it a lot of sense. So would we make it Cable/DSL/LTE/FTTH/WiFi/Dial to bring it current? /wireless to opt for something all inclusive without overdoing lables. Anyhow.

How could we also test the waters for deprecation? Admittedly, I have never used this field in my entire time using PDB for anything  - peering, depeering, etc. I filled it out, but “just because”. Whats the use case again?

Thanks,

-M<



From: Leo Vegoda ***@***.***>
Date: Monday, March 20, 2023 at 2:49 PM
To: peeringdb/peeringdb ***@***.***>
Cc: Martin Hannigan ***@***.***>, Mention ***@***.***>
Subject: Re: [peeringdb/peeringdb] Clarifying or Deprecating the Network Type field (Issue #1357)

-1 ... in general, we are lacking documentation. And IMO, it should go there.

Whatever the outcome of this discussion, we should definitely document the outcome.

**Comment by martinhannigan** [comment]
Leo what do you want to document? Even with the labels out of date, they’re pretty clear as to what they mean. Except the cable one.



From: Leo Vegoda ***@***.***>
Date: Monday, March 20, 2023 at 2:49 PM
To: peeringdb/peeringdb ***@***.***>
Cc: Martin Hannigan ***@***.***>, Mention ***@***.***>
Subject: Re: [peeringdb/peeringdb] Clarifying or Deprecating the Network Type field (Issue #1357)

-1 ... in general, we are lacking documentation. And IMO, it should go there.

Whatever the outcome of this discussion, we should definitely document the outcome.

**Comment by leovegoda** [comment]
> Leo what do you want to document? Even with the labels out of date, they’re pretty clear as to what they mean. Except the cable one. 

I think we should document not just what the labels mean but also why those labels are considered relevant. The world changes and the labels might need updating in a few years from now. Documenting the intent should make that update process easier - probably.

**Comment by martinhannigan** [comment]
@peeringdb/pc FYI

**Comment by martinhannigan** [comment]
+1

**Comment by arnoldnipper** [comment]
-1 as I still don't see what the proposal is. The lately introduced network types make good sense. Hence, they **must** stay.

**Comment by peterhelmenstine** [comment]
This seems like a documentation issue. I don't see any need to change what's there based on the way folks are using it today if < 2% aren't using it.

**Comment by grizz** [comment]
I'm a bit surprised by the responses here, the last couple times it's come up on PC calls there's been a lot of interest in fixing this field.

The main problem is that the choices are not mutually exclusive, thus it's impossible to have this field be accurate without a change. Inaccurate data is worse than no data at all.

We have discussed making the choices a lot more generic and multiple choice, along the lines of the tagging which @martzuk suggested which seems like a good possibility.

The other option is to remove the field, it's informational, meaning not approved or verified so we won't be able vouch for the truth of it.

> This seems like a documentation issue. I don't see any need to change what's there based on the way folks are using it today if < 2% aren't using it.

Having the field filled in does not denote use, in fact, I'd wager it's more in line with the law of triviality in that people see a multiple choice question with answers they understand so they fill it out. The real question would be if data consumers are able to use the field, and since we have received complaints, there are at least some cases where the answer is no.

Having said all of that, I personally don't care much either way, I'm not a fan of any of the `info_` fields. :)

At the bare minimum, to make the field somewhat more useful, we should update the options and enable multiple selections.

**Comment by arnoldnipper** [comment]
> At the bare minimum, to make the field somewhat more useful, we should update the options and enable multiple selections.

+1 ... regarding the "... so we won't be able vouch for the truth of it." We say: "PeeringDB is ..., **user-maintained**, database ...". Hence, truth is what the users say, unless there is a syntax or a source which gives 100% truth. Our users use this field, although they could leave it empty. Looks like they chose the option which fits best **for them**

**Comment by raybellis** [comment]
I'd like to see "DNS Root Server Operator" on the list, as RSOs are an important set of neighbours that all IXP users should peer with, and be able to find easily.

**Comment by lukastribus** [comment]
The network type is useful to gauge the type of network by reading a short field as opposed to trying to extract that information from a huge (user-provided) notes field often filled with marketing or, a lot worse, from the (marketing firm provided) organizations website.


Consider a peering request, incoming our outgoing. In both situations the PDB consumer wants structured user-provided data that can be consumed (read by a human) really fast, because the alternatives are terrible. Trying to read the user provided Notes section (where the entire guidance PDB provides to fill it out is literally: `Markdown enabled`) or even worse: going to the organizations website ... which is often completely useless and in the best-case scenario an order of magnitude slower.

The job of a peering manager is to make quick decisions and have data available for fast consumption. It is the peering managers job to judge whether the data can be trustworthy or not. It's also his job to understand which fields in PDB are user provided and which ones are verified.

And a whole lot of inputs are not PDB verified, that is the entire point of PDB.

IPv4 Prefixes, IPv6 Prefixes, Traffic Levels, Traffic Ratios, Geographic Scope, even "Protocols Supported" is not PDB verified. How are you going to verify whether a network runs Multicast or not? How are you going to verify traffic levels or geographic scope?

I fully agree with IX-F based validation of IX data, that's extremely useful.

I disagree with busy work on fields intended for human consumption, erasing data in fields by the tens of thousands or compacting them for a similar effect.

That is the kind of decision that makes users move data into the notes section, so it can stay untouched.

A organization made a conscious decision to set network type to, let's say Educational/Research, perhaps even involving upper management, just to find the decision reverted by PDB and aggregated into "Content Cloud" years later?

Those are the kind of decisions that slowly eradicate trust.

I don't need PDB to speak for me. I need PDB to respect my choices. Otherwise it's back to the `as64509.net` sites (hopefully hidden from marketing).



> and potential waste of valuable screen space.

For me the field provides a lot of value and I can't believe we are discussing screen space as an argument when it is single line in a HTML document while on the other hand the user provide notes section can be hundreds of lines.



> The real question would be if data consumers are able to use the field

Depends on what those data consumers do with it. The real *real* question seems to be:

How can data consumers distinguish between user provided information and PDB verified information, in UI, API, and dumps. That's a valid question warranting further discussion, but it is also orthogonal to the discussion at hand.



> The real question would be if data consumers are able to use the field, and since we have received complaints, there are at least some cases where the answer is no.

What operationally relevant problems are those complaints talking about? You are suggesting changes based on complaints you are not sharing.

For all I know people could be doing something they shouldn't be doing in the first place with this field, and then complaining about the consequences.


> The main problem is that the choices are not mutually exclusive, thus it's impossible to have this field be accurate without a change.

So perhaps this is where the complaints are from?

"We are a non-profit research institute, so do we pick research or non-profit?"

Not from data consumers, but from entities that struggle to fill out the template, is that it?



> Inaccurate data is worse than no data at all.

This statement does not make any sense for user provided data in PDB. Traffic Levels are inaccurate. Traffic ratios are inaccurate. The user provided data in PDB is useful despite being partially inaccurate. That's what user provided data means.


Should we downgrade PDB to a read only visualization tool for IX-F feeds?

**Comment by leovegoda** [comment]
The PC [met in July](https://docs.peeringdb.com/committee/product/notes/2023-07-06_Product_Committee_Notes.pdf) and agreed that PeeringDB will retain the Network Type field. We will not change the types of networks but will implement the ability to select multiple types. This will be implemented in the website and v2 API now deployed. We will plan a more radical update of the field for a future v3 API.

**Comment by leovegoda** [comment]
**Summary**
Enable the ability to select and show multiple network type options

**Comment by grizz** [comment]
**Summary**
Enable the ability to select and show multiple network type options. For staying on API v2, this will require a second field that's a set, and the single value field will become read only (db level). Any write to the single value field will clobber the set field to a single value.

UX will seamlessly show a multi-select field.

The single field can be dropped on APIv3 #625
