### ISSUE TITLE
Show connected networks, exchanges, and carriers on campus results pages

### ISSUE THREAD

**Issue by leovegoda** [peeringdb/peeringdb#1362]
**Is your feature request related to a problem? Please describe.**
A `campus` listing page currently shows each member `facility` but does not show the networks, exchanges, or carriers with a presence in that campus

<img width="1185" alt="Screenshot 2023-03-27 at 13 09 18" src="https://user-images.githubusercontent.com/59064677/228054968-83b90c32-25c4-436f-810e-39046110982e.png">

**Who is affected by the problem?**
Users in, or interested in, `campus` connected facilities

**What is the impact?**
More work is required to build a complete picture

**Are there security concerns?**
No

**Are there privacy concerns?**
No

**Describe the solution you'd like**
Create tables listing the carriers, exchanges, and networks present on the campus

**Do you think this feature will require a formal design?**
Probably not but we should consider whether there would be any value in extending the table format to note the specific `facility` hosting a network, exchange, or carrier

**Describe alternatives you've considered**
Do nothing

**Could this feature request need support from the Admin Committee?**
No

**What is the proposed priority?**
Soon

**Provide a rationale for any/all of the above**
Improve the user experience by making it easier to learn the value of a whole campus of facilities

Overall discoverability will be improved through #1204. This issue is focused on providing a clearer overview and simple data export

**Comment by martinhannigan** [comment]
this seems like a scope for inclusion to “v3” eg hierarchical integration.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Leo Vegoda ***@***.***>
Sent: Monday, March 27, 2023 6:13:51 PM
To: peeringdb/peeringdb ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [peeringdb/peeringdb] Show connected networks, exchanges, and carriers on campus results pages (Issue #1362)


Is your feature request related to a problem? Please describe.
A campus listing page currently shows each member facility but does not show the networks, exchanges, or carriers with a presence in that campus

[Screenshot 2023-03-27 at 13 09 18]<https://user-images.githubusercontent.com/59064677/228054968-83b90c32-25c4-436f-810e-39046110982e.png>

Who is affected by the problem?
Users in, or interested in, campus connected facilities

What is the impact?
More work is required to build a complete picture

Are there security concerns?
No

Are there privacy concerns?
No

Describe the solution you'd like
Create tables listing the carriers, exchanges, and networks present on the campus

Do you think this feature will require a formal design?
Probably not but we should consider whether there would be any value in extending the table format to note the specific facility hosting a network, exchange, or carrier

Describe alternatives you've considered
Do nothing

Could this feature request need support from the Admin Committee?
No

What is the proposed priority?
Soon

Provide a rationale for any/all of the above
Improve the user experience by making it easier to learn the value of a whole campus of facilities

Overall discoverability will be improved through #1204<https://github.com/peeringdb/peeringdb/issues/1204>. This issue is focused on providing a clearer overview and simple data export

**Comment by arnoldnipper** [comment]
+1000 and does not have to wait for v3.

**Comment by arnoldnipper** [comment]
> **Do you think this feature will require a formal design?**
> Probably not but we should consider whether there would be any value in extending the table format to note the specific `facility` hosting a network, exchange, or carrier

KISS, IMO ... Hence, let's not overload this feature

**Comment by martinhannigan** [comment]
+1000 is a lot of votes!  I will have to reconsider!

Tks

-M<


* early analytics =adv search looking like a huge priority.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by arnoldnipper** [comment]
@peeringdb/pc, some facility operators are waiting for the full deployment of the `campus` object in order to split their existing *campus* facilites (e.g. [InterXion Frankfurt (FRA1-15)](https://www.peeringdb.com/fac/58).

Please give a +1, esp. as we already agreed last time how to split the existing *campus* facilities while keeping the information.

**Comment by mcmanuss8** [comment]
+1

**Comment by grizz** [comment]
+1

**Comment by peterhelmenstine** [comment]
+1

**Comment by Yo-Robinson** [comment]
+1

**Comment by leovegoda** [comment]
**Summary**
Add an aggregate view of interconnection resources at a campus on the `campus` page. Add the the tables listed below with columns in the order given, so columns can neatly be reduced for an improved (future) mobile portrait view mode.

All tables have a new "Facilities" column. This lets users quickly know how many facilities a `carrier`, `ix`, or `net` is present in. This is always a digit unless they are present in all facilities. When that happens they should be listed as "ALL" so users do not need to compare the number of facilities in the `campus` with the listed number. The word "ALL" should be translatable.

Default sort order is alphabetical or numerical for Column 1.

_Carriers_
Column 1: Name
Column 2: Facilities

_Exchanges_
Column 1: Exchange
Column 2: Facilities
Column 3: ASNs
Column 4: Prefixes (IPv4/IPv6)
Column 5: Routeservers

_Networks_
Column 1: ASN
Column 2: Name
Column 3: Facilities
Column 4: # IX Connections
