### ISSUE TITLE
Creating a new network not possible

### ISSUE THREAD

**Issue by marcelb98** [peeringdb/peeringdb#1401]
**Describe the bug**

**To Reproduce**
1. Login
2. fill in data of new network, submit

**Expected behavior**
Network to be created in PeeringDB.

![image](https://github.com/peeringdb/peeringdb/assets/20777899/c207ef5d-0ff4-4b24-8181-6344c4bede02)

**Comment by martinhannigan** [comment]
@marcelb98 Is this still happening? This may be a better issue for [support@peeringdb.com](mailto:support@peeringdb.com).

**Comment by arnoldnipper** [comment]
> @marcelb98 Is this still happening? This may be a better issue for [support@peeringdb.com](mailto:support@peeringdb.com).

No, it isn't :)

**Comment by martinhannigan** [comment]
I can’t recreate it and it feels like a one-off.

From: Arnold Nipper ***@***.***>
Date: Saturday, June 17, 2023 at 5:19 PM
To: peeringdb/peeringdb ***@***.***>
Cc: Martin Hannigan ***@***.***>, Assign ***@***.***>
Subject: Re: [peeringdb/peeringdb] Creating a new network not possible (Issue #1401)

@marcelb98<https://github.com/marcelb98> Is this still happening? This may be a better issue for ***@***.******@***.***>.

No, it isn't :)

**Comment by arnoldnipper** [comment]
> I can’t recreate it and it feels like a one-off.

It's definitely not. It happened already at least three times. Besides, the error message is very, very, very poor

**Comment by martinhannigan** [comment]
Agree, that’s part of it. However, its probably better for AC to decide if its worth some investigating. I hesitate to call it a bug since sending it down that path potentially costs $.

From: Arnold Nipper ***@***.***>
Date: Saturday, June 17, 2023 at 5:22 PM
To: peeringdb/peeringdb ***@***.***>
Cc: Martin Hannigan ***@***.***>, Assign ***@***.***>
Subject: Re: [peeringdb/peeringdb] Creating a new network not possible (Issue #1401)

I can’t recreate it and it feels like a one-off.

It's definitely not. It happened already at least three times. Besides, the error message is very, very, very poor

**Comment by arnoldnipper** [comment]
> Agree, that’s part of it. However, its probably better for AC to decide if its worth some investigating. I hesitate to call it a bug since sending it down that path potentially costs $.

BTDT, Mr. Hannigan. It needs helping hands from @peeringdb/20c

**Comment by arnoldnipper** [comment]
> I can’t recreate it

What happened when you tried to add AS 198116? I don't see a DeskPRO ticket

**Comment by martinhannigan** [comment]
No worries Arnold - looks like you have it well under control.  Thanks for the work!



Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by peterhelmenstine** [comment]
+1

**Comment by vegu** [comment]
I was able to reproduce on beta, but not on my developer instance. My dev is ahead of beta in terms of updates - which might mean its already fixed there or the issue is simply intermittent.

This is a bug with the user facing UX for adding networks, stemming from the social media fields that were added earlier this year.

When it happens the server returns this error with the response:

```
{
    "social_media": [
        {
            "service": [
                "This field is required."
            ],
            "identifier": [
                "This field is required."
            ]
        },
        {
            "service": [
                "This field is required."
            ],
            "identifier": [
                "This field is required."
            ]
        },
        {
            "service": [
                "This field is required."
            ],
            "identifier": [
                "This field is required."
            ]
        }
    ],
    "meta": {
        "error": "Bad Request"
    }
}
```

**Summary**

- fix issue where network creation through /org UX fails with non-descriptive bad request error because of bogus social media fields sent with the request.

**Comment by martinhannigan** [comment]
+1

**Comment by arnoldnipper** [comment]
Routed through to 4 as identified as a bug by a developer

**Comment by netravnen** [comment]
Another ticket to the list. https://peeringdb.deskpro.com/agent/#app.tickets,inbox:agent,t.o:89821

**Comment by vegu** [comment]
closed through https://github.com/peeringdb/peeringdb/pull/1440
