### ISSUE TITLE
Enhancement: Add other global voltages to the Available Voltages feature

### ISSUE THREAD

**Issue by kavirondo** [peeringdb/peeringdb#1465]
Hello PeeringDB Team,

I am enjoying using the platform, but i have some suggestions for the Available Voltage Services Feature.

The voltages listed in the system right now, (apart from the 48v DC) are not applicable in all of Europe, The UK, Australia and much of Asia Pacific, Africa etc.

Please could you add the following voltages?

- 230v AC (This is the European Single Phase voltage) as a minimum add this
- 400v AC (This is the European Three Phase voltage) as a minimum add this
- 240v AC (This is the Single Phase voltage in my country, Kenya) nice to have
- 415v AC (This is the Three Phase voltage in my country, Kenya) nice to have

Many other voltages are listed on this wikipedia page:

[Wikipedia Electricity by Country](https://en.wikipedia.org/wiki/Mains_electricity_by_country)

Many thanks for your consideration on this enhancement and thanks for the product.

Alex

**Comment by leovegoda** [comment]
The PC discussed power options in https://github.com/peeringdb/peeringdb/issues/1341 and agreed that the purpose of the field is to show differences from the default in a country. We will be making a change but won't be attempting to include things like 230v AC in Europe as people take that as given.

What we might need to do is make the purpose of the field clearer in the webUI and in documentation.

**Comment by martinhannigan** [comment]
-1

**Comment by martinhannigan** [comment]
My suggestion would be we clarify the use of the field with a tool tip such as:

"This selectable field showcases a range of distinctive voltage options available at various facilities. We deliberately exclude household and common to data center voltages such as 120V, 208V, 240V, and 277V AC, focusing instead on unique offerings provided by a building or facility operator. These uncommon selections include 480V AC and higher voltages in the United States, along with specialized DC power services delivered rack side at -48V, catering to specific needs beyond the typical spectrum."

We certainly can add interesting voltages from other countries. We started with the US because it's orders of magnitude a larger DC market than the entire world combined:

https://www.statista.com/statistics/1228433/data-centers-worldwide-by-country/

The 400/415VAC options also look common. I would suggest if there's disagreement that these are commonly available voltages in the data center in Europe I can go ask at a few of the largest retail colo operators to confirm what they assert is common or not.

Hope that helps. And really glad to see healthy commentary on this option even though it's been challenging to focus it on what we think it's most useful for here.

**Comment by leovegoda** [comment]
> My suggestion would be we clarify the use of the field with a tool tip such as:

Rebecca (our designer) and I sat down at RIPE to discuss exactly how to do this. In the new design for the admin interface we want to have some inline documentation that will explain exactly this sort of thing. We might need to edit your text for length but the goal is to provide the essence of your explanation.

**Comment by mcmanuss8** [comment]
-1, let's not

**Comment by jackcarrozzo** [comment]
-1

**Comment by martinhannigan** [comment]
-1

**Comment by arnoldnipper** [comment]
**Summary**
The proposal adding this feature has  been turned down.
