### ISSUE TITLE
Support for Multiple IP Addresses on an IX 

### ISSUE THREAD

**Issue by daveschwartz1** [peeringdb/peeringdb#15]
Is it possible to add support for adding multiple IP address for a single IX?

For example an ISP could have multiple IP addresses on a single interface to an IX but you can only list one IX Address.

If you need to add another you need to create a new 'line' in your PDB record and associate a capacity with it, therefore you could be misrepresenting your capacity.

Therefore I would like the ability to add multiple addresses to an IX using the same capacity.

**Comment by grizz** [comment]
This would involve a somewhat major schema change, could you give a real world use case?

**Comment by arnoldnipper** [comment]
@grizz , there a few IXP which allow multiple IP's on the same physical port. The current data model is not able to handle this.

**Comment by daveschwartz1** [comment]
Depending upon the schema, can we make another column in the data titled
that named "IX Address Alternate" where we would be able to add that
address.

And then only show it  in the website UI if the value !=null ? This way
only if you have a second address it shows up.

This way it would be query-able and displayable.

Dave


-- 

Dave Schwartz
Peering & Content Distribution
Google AS15169
daveschwartz@google.com
+1-650-253-7615 / +44 20 3820 9224

**Comment by arnoldnipper** [comment]
@daveschwartz1 , imho allowing 0..n IP addresses would be the cleaner approach. We have another ticket where 0 IP addresses would be needed if someones wants to indicate that s/he is provisioning the connection to an IXP.

**Comment by grizz** [comment]
Personally, I don't see a reason for IXPs to do that, and it goes against all the IXP BCOPs I've seen. Obviously, it's not PDB's place to tell an IXP what to do, but I'm against making the schema and API more complex for a corner case.

**Comment by mcmanuss8** [comment]
I agree a placeholder value makes sense for when you haven't had an IP provisioned yet. But, what is the use case for having multiple IPs (not just 1 IPv4 and 1 IPv6) on a single interface to an IXP? Is that you migrating from old to new? 

I think it'd help if we knew why.

**Comment by grizz** [comment]
Actually, I was thinking about this wrong, there's nothing wrong with it if one uses VLANs, PCH does this to peer with 2 ASNs on each IXP.

Still, it's really only an issue in displaying capacity, but it could be solved by adding another level for phy connection between a network and it's ip addresses, which would make the backend a tiny bit more complex but would keep the API the same as it is now.

**Comment by arnoldnipper** [comment]
@grizz , even when looking at *the* standard document (http://www.open-ix.org/standards/ixp-technical-requirements/) I can't find anything about it. The referal on this page to http://bcop.nanog.org/ goes into Nirvana.

Imho we should find a model which really describes an IXP in an abstract way and not necessarily the way both of us think it should be.

**Comment by eloos** [comment]
@arnoldnipper when I look at the standards document at open-ix, there are clear references to using VLAN's for access to PVLAN or public IX VLAN. This would argue for a level of additional abstraction as @grizz indicated by introducing a physical layer that has the speed. Then the individual VLAN on the port can still have another speed metric. Do we want to introduce this? How do we make this happen in terms of the schema? @vegu/@grizz how would you propose to implement this?

**Comment by arnoldnipper** [comment]
even if we introduce an additional (physical) layer, it doesn't solve the original problem @eloos ... you still may have several IPs on the same VLAN.

So what has to be changed is the representation. ipaddr{4,6} would have to be a (non empty) list of IPv{4,6} addresses

**Comment by grizz** [comment]
@arnoldnipper 
> even if we introduce an additional (physical) layer, it doesn't solve the original problem @eloos ... you still may have several IPs on the same VLAN.
So what has to be changed is the representation. ipaddr{4,6} would have to be a (non empty) list of IPv{4,6} addresses.

Networks can add multiple sets of IP addresses now, it would just show their capacity incorrectly

> I still don't see a use case for the additional physical layer, though

If a network wanted to know another networks actual capacity.

**Comment by arnoldnipper** [comment]
@grizz : representing addresses as a set of IP addresses would solve the problem w/o introducing the physical layer. Right?

**Comment by grizz** [comment]
@arnoldnipper probably, but the API would change (or we could add another field for it)

I'd want to think about that more, and double check how the IXP member list schema represented that

**Comment by eloos** [comment]
@grizz I checked the euro-ix json format, it doens't have this concept either so we would also need to (ideally) push for a change there to incorporate this... but then of course we are back to what is the value of this information if people can already document multiple entries? It is not because you have 20G that is empty or full. Only use case I see is someone having more than 10G of traffic and wondering on which public IX they could exchange it with partner X. is at that moment it not enough to know whether a peer has at least n*times the required capacity available to understand whether it makes sense to push it via there.
Furthermore in SDN mechanisms this is all pretty much moot since they would measure congestion and route away... so we are back to understanding which decision this would influence.
I am leaning towards calling this a wontfix

**Comment by arnoldnipper** [comment]
@eloos of course euro-ix json format doesn't have this format because they have the concept of a physical interface if_list which also has the speed as an attribute.

For IXP physical interfaces make sense as there may be additional vlan services besides peering lans.  PeeringDB does not (yet) support it.

From that pov it might be easiest to model according IX-F / Euro-IX JSON. I definitely wouldn't drop the issue

**Comment by eloos** [comment]
@arnoldnipper I am not sure what euro-ix file I was looking at because indeed the euro-ix json schema is very complete with the definition of a switch, VLAN. (euro-ix json schema here)[https://github.com/euro-ix/json-schemas/blob/master/ixp-member-list.schema.json] so what is not there is the hierarchy between if_list and vlan, so if we follow that model, we shouldn't do it in PDB either.
If we compare:
"connection_list": [
        {
          "ixp_id": 2,
          "if_list": [
            {
              "switch_id": 15,
              "if_speed": 60000
            }
          ],
          "vlan_list": [
            {
              "vlan_id": 510,
              "ipv4": {
                "address": "193.105.101.138",
                "routeserver": false
              }
            }
          ]
        },
Our Org matches with IXP, our InternetExchange matches with ixp_list, ixlan arguably overlaps with VLAN and networkixlan overlaps with connection_list and if_list, where we in effect mix the if_list into the networkixlan object. So in order to match with the euro-ix schema we should introduce the if_list and perhaps for now proxy the value from the if_list to the networkixlan object until people fill it in themselves?

**Comment by arnoldnipper** [comment]
@eloos , both IX-F JSON and PeeringDB do not allow for multiple addresses on the same "port" afais. I.e. there is no way to exactly express addresses **and** speed simultaneously.

I was wrong with my earlier post. So leave it as it is and classify as ''wontfix''

**Comment by arnoldnipper** [comment]
@eloos ... jeez not my day. I was wrong. Of course IX-F JSON format allows for multiple addresses on same port. Question really is whether we want to model that

**Comment by grizz** [comment]
@peeringdb/pc This issue hasn't been touched for a year, let's vote or close?

**Comment by daveschwartz1** [comment]
Hi Matt,

I am OK to close.

Thanks,
Dave

--

Dave Schwartz
Peering & Content Distribution
Google AS15169
daveschwartz@google.com
+1-650-253-7615
+44 20 3820 9224
