### ISSUE TITLE
When merging objects, notify all admins

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#153]
1. send an e-mail to the "merged" admins to which object they were merged
2. send an e-mail to the remaining object admins which objects have been merged

**Comment by vegu** [comment]
fixed in 25a63e2

Below is an example of the mail sent to all admins affected by an organization merge, ix and facility merges dispatch similar messages. **Note** that the url in the sample mail is from a dev environment and won't actually lead to the expected target when clicked.

Let me know if you want any other information added to the message.

**Subject**

> Organization Merge Notification: 20C_Test_Org_3 -> 20C_Test_Org_1

**Body**

> Organization Merge Notification
> 
> Organization "20C_Test_Org_3" (ID: 15702)
> 
> has been merged into
> 
> Organization "20C_Test_Org_1" (ID: 15700)
> https://www.peeringdb.com/org/15700
> 
> All merges are processed manually by peeringdb support staff. If you think this action has been executed in error please don't hesitate to contact peeringdb support at support@peeringdb.com

**Comment by arnoldnipper** [comment]
Looks good ... coul become a bit confusing when merging a couple of organisations at the same time. Or will you then send one message per merged organisation? Which could make sense imho

**Comment by vegu** [comment]
Indeed, in case where multiple organisations are merged, it will send one message per merged organisation.
