### ISSUE TITLE
Feature Request: Add new network type "Personal"

### ISSUE THREAD

**Issue by benjojo** [peeringdb/peeringdb#1537]
**Is your feature request related to a problem? Please describe.**

With the rise of the “personal” ( networks that are primarily used for learning or hobbies ) network,  I often find that users are selecting “ research and educational networks “  when I feel like that is not necessarily the right category that these networks belong in.  as I assume that category was initially designed for NREN’s  and experimental networks like the peering testbed.

Currently there is no good way to describe a hobby/personal network on PeeringDB

**What is the impact?**

Personal and Hobby networks are not categorised and thus not represented in details and statistics,  in addition academic projects struggles sometimes to tell the difference between hobby networks and commercial entities 

**Are there security concerns?**

No

**Are there privacy concerns?**

As much as there are any other privacy problems with “personal” networks

**Describe the solution you'd like**

I would like "Personal" or "Hobby" to be in this list:

![image](https://github.com/peeringdb/peeringdb/assets/1504626/6e4a8170-b014-432e-9a21-946633ba5a43)

**Do you think this feature will require a formal design?**

no, I feel like this is a minor change

**Describe alternatives you've considered / Provide a rationale for any/all of the above**

Currently if you look at [the ASNs that bgp.tools consider personal ASNs](https://bgp.tools/tags/perso) you get the following network type breakdowns

```
+----------------------+-----+
| info_type            | Cnt |
+----------------------+-----+
| Educational/Research | 508 |
|                      | 273 |
| Non-Profit           | 111 |
| Network Services     |  31 |
| Content              |  29 |
| Cable/DSL/ISP        |  28 |
| Enterprise           |  19 |
| NSP                  |  16 |
| Route Server         |   2 |
| Government           |   1 |
| Route Collector      |   1 |
+----------------------+-----+
11 rows in set (0.009 sec)
```

To me this seems relative to be clear that there is a gap in the network types. As out of the 29,383 ASNs on PeeringDB, around 5% of them are not represented

**Could this feature request need support from the Admin Committee?**

No more than the existing options already do 

**What is the proposed priority?**

Not Urgent

**Comment by leovegoda** [comment]
@benjojo When the @peeringdb/pc last discussed the Network Types field there was a feeling that it wasn't very useful and just a hangover from v1. The goal was to get rid of this field in v3 of the API. But was the PC wrong? Do people rely on the data in this field when finding networks and making peering decisions?

**Comment by benjojo** [comment]
I think that it can have some uses, for example understanding things like route collectors  and other “special” types of ASNs. (and I promise that I am not just saying that because I am one of those weird types)

However I think I would genuinely agree that outside of that it doesn't really matter that much.

I think what most people want to know is “is this an inbound heavy or an outbound heavy network?”  and that is already answered by another field.

**Comment by job** [comment]
The `Route Server` and `Route Collector` values seem very useful, because those can drive network automation configuration changes. If the `Route Server` value is encountered, the operator might want to automatically configure that it's OK that the peer's ASN is not the first one in the AS_PATH, and when a `Route Collector` is encountered, the operator might automatically configure their device to not accept any BGP routes from said peer. Full removal of the field might negatively impact such workflows.

On the matter of NREN vs Personal vs Hobby vs Government I don't really have an opinion.

**Comment by martinhannigan** [comment]
Re inbound/outbound ratio. Does anyone besides a few LECs care about that
anymore? And even if they do, once you figure out the magic words to
interconnect that goes away. It's effectively just a tool to deny "free"
interconnection.  That requirement originates and was a vestige of at least
voice language in the telecommunications act of 1996, section 251 or 252
IIRC. Some of the European and Asian LEC's took a queue from that. I
wouldn't argue it doesn't matter, but I would venture a guess anyone
peering over an IX isn't so concerned and more so concerned PNI wise. The
effort we made last go around which I volunteered to shepherd and took the
pain was to simply if. Content/Cloud/ISP/Enterprise. Since Cable/DSL/etc
physical plant was less important than actual type. Of course, every
network cares about different things so disclaimer. Then the problem with
network operators who consider themselves an NSP when they're an ISP, the
collapse of cloud and content companies into compute companies, etc. And
now AI. I can't wait for someone to ask us to add "AI network". At least
from my view they're all network operators. Someday we might spend time on
trying to categorize us all a lot better than the wiki fights over tier1
and who's SFI which also doesn't matter a lot these days to those it used
to matter to.

I would argue "personal" probably fits OK in non-profit since we kept it.
:) We also have the notes field which supports Markdown language. However,
one of the things I've noticed lately is users tend to use fields for
things that lack in peeringdb like type or city or what networks are not in
PDB or won't take time to properly affiliate with a building. Or those that
do and shouldn't. PDB has a lot of issues.

Hope that helps.

-M<

**Comment by grizz** [comment]
As I recall, `Route Server` and `Route Collector` piggybacked on that field since it was already there to test out having them as options. I think they're both quite useful and should be in their own `network_function` or similar field for v3 and the rest can still be dropped.

~$.02

**Comment by martinhannigan** [comment]
On Wed, Jan 31, 2024 at 20:44 Matt Griswold ***@***.***>
wrote:

> As I recall, Route Server and Route Collector piggybacked on that field
> since it was already there to test out having them as options. I think
> they're both quite useful and should be in their own network_function or
> similar field for v3 and the rest can still be dropped.
>
> ~$.02
>

Its not describing layer two and its clear.  Supportable.

**Comment by arnoldnipper** [comment]
> On the matter of NREN vs Personal vs Hobby vs Government I don't really have an opinion.

+1

**Comment by peterhelmenstine** [comment]
Agreed on the route viewer & collector. The rest don't see the need.

**Comment by jackcarrozzo** [comment]
PC call: already discussed and decided (TODO: link to decision)

**Comment by benjojo** [comment]
> TODO: link to decision

What was it?

**Comment by benjojo** [comment]
RIPE 88, someone confirmed that the decision was no

**Comment by martinhannigan** [comment]
Accurate.
