### ISSUE TITLE
 RFE for IRRdb support on Route Servers

### ISSUE THREAD

**Issue by stkonst** [peeringdb/peeringdb#1600]
Hi PDB team,

I am submitting this issue to request a new feature for the Peering DB Route Server records. To be more specific, while examining our Route Server object (https://www.peeringdb.com/net/4277) I noticed I cannot mention anywhere which IRR databases we are officially supporting to configure the Route Servers. This is relevant to a work that is being done in Connect WG at RIPE community. There is an upcoming BCP in the RIPE community (Arnold knows about it) where IXPs will restrict the amount of IRRs being used to configure the Route servers with the end goal to support official IRRs only.
 
Thus, it would be nice to have a list of supported IRR databases where we can fill it in (perhaps via a drop-down menu?). That can help customers to understand: 

- which IRRs are being supported in the IXP’s Route Servers 
- where to place their IRR objects in order to be fetched from automation tools and configure the Route Server filters.
 
 
Do you think would be feasible to add such a feature in PeeringDB?
 
 
Kind Regards
Stavros Konstantaras | AMS-IX

**Comment by arnoldnipper** [comment]
> * which IRRs are being supported in the IXP’s Route Servers

Iirc, we allow all DB listed at [irr.net](https://irr.net/registry/)

**Comment by stkonst** [comment]
Hi @arnoldnipper  correct. But is there a way to present a list of supported IRRs under the Route Servers object where I can define the individual items of this list? For example I can have a list for the AMS-IX NL Route Servers where the items are [ RIPE, ARIN, APNIC, LACNIC, AFRINIC ] while another IXP in Asia might declare [ ARIN, IDNIC, RADB ] IRR dbs. 

I am not against if PeeringDB provides all possible IRRdbs for me to fill in my list but I would love to have a list and fill it with the items I want based on our strategy. 


BR
Stavros

**Comment by arnoldnipper** [comment]
Hi @stkonst, I still fail to see why it would make sense having this in PeeringDB. If an ASN wants to peer with your RS, you probably will let them know your policy. 

@peeringdb/pc, thoughts?

**Comment by arnoldnipper** [comment]
> Does the above text help a bit?

No really, @stkonst. As mentioned before, if an ASN wants to connect to one of your IXP they will contact you for the requirements, resp. you will have this information as part of your peering policy. Hence, no need having this information in PeeringDB. We are supporting all IRR. KISS :)

**Comment by mcmanuss8** [comment]
-1 from me unless we hear a lot of request for this across a large enough numbers of IXes

**Comment by jackcarrozzo** [comment]
PC call: sounds AMS-IX specific? Not clear we need this without clear use cases.

**Comment by Martolins** [comment]
Hi, as Namex 
> Let me elaborate a bit further. Although I can define in Peering DB where my Peering Policy is with "RIPE::AS1200" or where my AS-SET is with "RIPE::AS6777:AS-AMS-IX-RS", it will still be valuable to present a list of supported IRRdbs where IXPs consult in order to retrieve Policies and AS-SETs to configure Prefix Lists for Route Servers.

I agree on this, and thinking about members who are in different IXPs can use PeeringDB as a single source to retrieve this information. Plus if it could be a way to not generate empty prefix lists, even better.

**Comment by irinovna** [comment]
Hello Stavros, 

From LU-CIX side I would agree that this is a rather useful feature request which will allow better IX operations.

**Comment by grizz** [comment]
To add a bit more context, we discussed at the last PC meeting and felt that the Notes field is the correct place for this.

Adding a field to the object does not give any sort of actionable programmatic response that a network can use to add themselves to one of the IRRs.

**Comment by rafeurdean** [comment]
I think there is a real use of an "Supported IRRs" field. While there my not be some immediate use "in a programmatic way", it gives clear visibility where different networks stand with respect to "IRR filtering" (which is unfortunately not such a simple problem as some people may think). 

Putting that info in the "notes" field (with each network presenting it in a different/random format) approaches the level of "useless".

**Comment by moshivji** [comment]
Hi  Stavros 
From LINX we also agree that this feature would be useful.

**Comment by martinhannigan** [comment]
-1 lets move on.

**Comment by tvberlin** [comment]
For us an operator this information would be helpful to have. I'm wondering why this was closed despite interest from multiple IXPs? I believe that the free-text notes field is not a proper place to store the information. Thanks!

**Comment by fvompe** [comment]
Hello, 

I support having this RFE addressed. There are many operators (not only IX-s) that have many customers, this customers may have address space and as-sets managed in one or many regional registries. Besides having a double colon syntax (RIPE::AS6777:AS-AMS-IX-RS), it's really important to have a list of this regional registries (and not limited to RIR-s, eg. others like RADB, JPIRR, ALTDB.. ) that should be used to resolve underlying customer resources.

Right now a decision is a part of peering policy or peering agreement between operators, although this is pure documentational information.

Having a dedicated field for sources would guide operators on how to resolve those AS-sets and address spaces properly.

Best regards,
Fedor Vompe
SWE, Deutsche Telekom

**Comment by benjojo** [comment]
Sorry this is going to be quite tongue in cheek here but is PeeringDB
a database or advisory on how to build networks?

I'm sure in a realistic world it would be really nice if all networks
could actually register authoritative IRRs instead but for a lot of
networks (for whole bunch of reasons some of them reasonable and some
of them stupid) can't do that right now. i think we're asking for here
is a basic text box the just suggests which IRRs are going to be used
here, which doesn't really seem like a huge lift technically

**Comment by arnoldnipper** [comment]
> ... we are requiring just a simple textbox that can be exposed in the PeeringDB's REST API where the network operator can insert ...

@stkonst, we receive tons of requests for just adding a simple textbox. That doesn't scale. KISS

**Comment by jwbensley** [comment]
This would be a really useful feature for us and it relates to https://github.com/peeringdb/peeringdb/issues/1973.

Consider this use case / work flow:

* We only support pulling data from the 5x RIR DBs + RADB, no others.
* Customers can sign up to our service by using our self-serve portal (they put in their ASN+AS-SET)
* Similarly, peers are auto-configured by an internal tool
* From time to time, someone's AS-SET is in AltDB for example, and we don't build prefix lists for that customer or peer due to the data source.
* Once it's failed and caused a problem and they've opened a support ticket with us, and we tell them, "sorry we don't pull data from AltDB" (or wherever their data is), they always move their data into the appropriate RIR (or RADB If they are in North America with legacy space).
* Then everything works after a day or two and prefix generation run again etc.

Considering that every time we have this problem, the customer/peer is always happy to move their data in to a reputable DB (it's in their best interest!), we could avoid this whole song and dance that takes several takes to go round, if there was somewhere I could list the DBs I support for prefix generation.

Also, now that https://github.com/peeringdb/peeringdb/issues/1973 will hopefully be implemented, I will actually be able to tell in advance "oh, network X stores their data in RIPE, and I have RIPE in my list of DBs, so peering will work" - or - "oh, I store my data in ARIN and network Y only pulls from JPNIC, this won't work" - so actually the two feature requests for PeeringDB would compliment each other.
