### ISSUE TITLE
Improve explanatory and help text

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#189]
@arnoldnipper commented on [Thu Dec 08 2016](https://github.com/peeringdb/admincom/issues/6)

We often see e-mails like this:

----------------------------------------------- snip -----------------------------------------------
My name is X Y. I am handling the operations of AAA who is hosting ZZZ IX.

We have asked all members in the IX to register at Peering DB and mention that they peer at our Exchange Point.

It seems that the "Affiliate" part is confusing them as they are thinking that they should affiliate to Beirut IX.

I have already denied two requests!
----------------------------------------------- snip -----------------------------------------------

Other misunderstandings we see is that users *add* IXP I and facilities F to their organisation where they actually wanted to add their network N to IXP I resp. facility F. 

Maybe a clearer and more verbose wording is needed

**Comment by grizz** [comment]
Please provide the new wording and we will update it

**Comment by arnoldnipper** [comment]
Please add the following text at the end.

_Affilition is for your own organisation. That means you are an employer or otherwise working for the organisation. The affiliation request is sent to support@peeringdb.com if no one is affiliated to the organisation yet. Otherwise, the admins are contacted. Only affiliate once per organisation. If you don't get an answer within a couple of days, please contact support@peeringdb.com_

Native speakers, please feel free to improve this text. @peeringdb/pc (esp. @shane-kerr ) +1, please

**Comment by arnoldnipper** [comment]
Would it be harmful if the requestor gets an email with a list of admin addresses, once the request is kicked off? Sometimes users wait for ages because the current admin left the organisation.

**Comment by grizz** [comment]
wording looks fine to me, +1

**Comment by shane-kerr** [comment]
I like the idea of improving the description. It will probably help in many cases, although in many cases people skim and won't see it. Better than nothing though!

_Affiliation is your own organisation. That means you are an employee or otherwise working for the organisation. The affiliation request is sent to support@peeringdb.com if no one is affiliated to the organisation yet. Otherwise, the admins are contacted. Only affiliate once per organisation. If you don't get an answer within a couple of days, please contact support@peeringdb.com_

Changes:
* `s/Affilition/Affiliation/`
* `s/ for //`
* `s/employer/employee/`

I appreciate the idea of letting requestors know the administrators, but are there any confidentiality  concerns there? I may not want unauthorized people knowing who my administrators are. Maybe instead we could change the final sentence to something like, _If you don't get an answer within a couple of days, or if the admins are no longer able to help, please contact support@peeringdb.com_

**Comment by arnoldnipper** [comment]
@shane-kerr, there might be confidentiality or also security concerns when sending the list of administrators. But if we don't send the list the sentence "... or if the admins are no longer able to help," does not really make sense as the requestor does not know whether there is an administrator at all. Maybe sending partial information like ar****@***per.de would help. Someone familiar with the organisation would probably be able to decipher the address.

**Comment by grizz** [comment]
Where does it say list the admins? I'm very against disclosing any level of information, including even if the org has 0 admins.

**Comment by arnoldnipper** [comment]
> Where does it say list the admins? I'm very against disclosing any level of information, including even if the org has 0 admins.

This is tbd, @grizz.

**Comment by mcmanuss8** [comment]
> Would it be harmful if the requestor gets an email with a list of admin addresses, once the request is kicked off? Sometimes users wait for ages because the current admin left the organisation.

Seems like something to split into another issue, since this one is pretty straightforward (change the text). Let's focus on that here since it's an easy win and discuss privacy concerns in a separate issue? 

+1 to @shane-kerr's revised text.

**Comment by grizz** [comment]
+1 to @shane-kerr's revised text as well

> This is tbd, @grizz.

Oh, I missed that first comment, sorry @arnoldnipper

**Comment by arnoldnipper** [comment]
**Release Note**
A clear help text is added for requesting affiliation to an organisation.
