### ISSUE TITLE
GUI and API differs

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#208]
API:
curl -sG https://peeringdb.com/api/netixlan --data-urlencode "asn=16570" | jq -c '.data[] | { name: .name }'
{"name":"TorIX"}
{"name":"VANIX"}
{"name":"SIX Seattle"}
{"name":"Digital Realty | Telx Atlanta"}

GUI:
![20170824 peeringdb 00](https://user-images.githubusercontent.com/16888757/29691201-89782474-892a-11e7-923e-9048a18f4f4e.png)

**Comment by vegu** [comment]
When querying asn on the netixlan endpoint - https://www.peeringdb.com/api/netixlan?asn=16570&pretty - it currently queries the asn field on the netixlan instance itself, not the parent network.

Looking at https://www.peeringdb.com/net/8157 and https://www.peeringdb.com/net/13109 shows where those netixlan entries (with the specified asn) in the api result come from.

**Comment by arnoldnipper** [comment]
What operation is net__asn? I can't find that in the API doc ... and when querying for a netixlan object there is no name "net"

**Comment by vegu** [comment]
https://www.peeringdb.com/api/netixlan/34070?pretty&depth=1

**net_id** refers to the parent network by it's id
**net** is the parent network's data if the end point is queried with appropriate depth
**net__asn** queries the asn of the parent network

**net** does not get included in the result of  https://www.peeringdb.com/api/netixlan?asn=16570&pretty because list results have limited depth, so the "net" key does not get expanded. it's existence however is still indicated in the net_id field.

the netixlan schema is layed out here in it's entirety: https://www.peeringdb.com/apidocs/#!/netixlan/Network_Ix_Lan_create
