### ISSUE TITLE
Clarify descriptive 'Add Facility/Exchange' explanation

### ISSUE THREAD

**Issue by netravnen** [peeringdb/peeringdb#215]
The current text does not do much to explain what is expected of a facility request:
> Add a new Facility to your Organization. Note that the newly created Facility will need to be approved by PeeringDB staff before it will appear in the search results or the API listings
> Submit Facility

Maybe append something _(to above text)_ along the lines of what we answer to PDB tickets would be more helpful upfront ?
> To be listed as a Facility in PeeringDB we would expect that you offer colocation, data center and/or meet-me-room services to the public.

**Comment by arnoldnipper** [comment]
Sounds good. And what would be the text for an IXP to be approved?

**Comment by vegu** [comment]
> Sounds good. And what would be the text for an IXP to be approved?

@arnoldnipper @netravnen can you give me a text for this as well, please? :) thanks

**Comment by arnoldnipper** [comment]
A widely accepted definition of an IXP is: An Internet Exchange Point (IXP) is a network facility that enables the interconnection of more than two independent Autonomous Systems, primarily for the purpose of facilitating the exchange of Internet traffic. An IXP provides interconnection only for Autonomous Systems. An IXP does not require the Internet traffic passing between any pair of participating Autonomous Systems to pass through any third Autonomous System, nor does it alter or otherwise interfere with such traffic

**Comment by vegu** [comment]
fixed in 5fdf7e45
