### ISSUE TITLE
Data validation with Inflect

### ISSUE THREAD

**Issue by ghankins** [peeringdb/peeringdb#217]
Need to work this out, opening as a placeholder.

**Comment by grizz** [comment]
Time to get back on this, I have a loose design in my head that definitely needs to be fine tuned, discussed, and thought out.

To start the discussion, I think it should be per field and allow any user to recommend a better value  with a comment via UI or API, and then display alternative values with an upvote / downvote button.

AC should have power to individually replace a value with the recommended value, close all recommendations, and probably lock them? AC should probably have a queue sortable by most voted, and time since recommendation? @arnoldnipper thoughts?

I think the object merges should probably remain somewhat manual, as the number of duplicates is going to decrease over time (I wish I had metrics for this, I haven't done queries to see if that's correct).

I'm not sure we should add API fields on the actual objects for recommended values, I think that should be left for UI only until AC approves it.

Thoughts from everyone?

**Comment by arnoldnipper** [comment]
@grizz imho what you propose would be a new issue and has little to do what was intended with our cooperation with Inflect. What you propose could be applied to any data in PeeringDB. But maybe I'm wrong.

What I had in mind: take all the data we have regarding facilities and pipe them through Inflect (see Greg's slide attached). Otoh when looking at Inflect data, I see that PeeringDB in most cases is one of their sources. So how would that help then?
[2080605-inflect.pptx](https://github.com/peeringdb/peeringdb/files/2070604/2080605-inflect.pptx)

**Comment by arnoldnipper** [comment]
@grizz 
[2080605-inflect.pdf](https://github.com/peeringdb/peeringdb/files/2070610/2080605-inflect.pdf)
 imho what you propose would be a new issue and has little to do what was intended with our cooperation with Inflect. What you propose could be applied to any data in PeeringDB. But maybe I'm wrong.

What I had in mind: take all the data we have regarding facilities and pipe them through Inflect (see Greg's slide attached). Otoh when looking at Inflect data, I see that PeeringDB in most cases is one of their sources. So how would that help then?

**Comment by grizz** [comment]
@arnoldnipper I see it as the same thing, it's a mechanism for "crowd sourced validation"

They pull data from PDB and compare it with other inputs, so this would give them a viable way to feed back fixes.

**Comment by grizz** [comment]
We could, although we still probably want an API for doing it?

**Comment by eloos** [comment]
to me this linked to overall staleness detection/flagging. My understanding is that it would also be easier for us to implement further own data-quality initiatives where we are suggesting better values because we can't find a single source of truth. I would like to understand better how it would work and ideally how we could prevent creating an additional funnel of work for AC. i.e. channel updates to the owner of the record??
