### ISSUE TITLE
IX-F import drops route servers

### ISSUE THREAD

**Issue by ccaputo** [peeringdb/peeringdb#245]
SIX route servers were dropped during the IX-F import run.  The one difference I see is member_type of "routeserver" rather than "peering" in the IX-F JSON data.

To see the difference:

  https://www.peeringdb.com/ix/1285
  [SIX Seattle (Jumbo)]

no longer has "SIX Seattle Route Servers" while:

  https://www.peeringdb.com/ix/13
  [SIX Seattle]

still does.  The IX-F import has so far only been enabled for the Jumbo ix.

**Comment by ccaputo** [comment]
I've reverted the SIX Jumbo ix to not use the JSON importer for now, but if you need to check out the JSON data, it is: https://www.seattleix.net/autogen/participants.json

**Comment by arnoldnipper** [comment]
According to https://github.com/euro-ix/json-schemas/blob/master/versions/ixp-member-list-0.6.schema.json the types are: peering, ixp, pro bono, routeserver or other".

Is there any reason to only import "peering"?

**Comment by vegu** [comment]
Route servers being dropped was an implementation error on our end, i fixed it in cbe79ea - however as we are unsure how the other member types relate to PeeringDB i have not included those in the fix. 

If it's obvious that they should be imported as well, please let me know here and i will add those as well - otherwise lets move this to Done and discuss the remaining member types in a new ticket.

**Comment by ccaputo** [comment]
Ok by me.

**Comment by arnoldnipper** [comment]
At least I also would include ixp and pro bono. ixp behinds stuff like collectors or the other monitoring stuff. And pro bonos are also peering, but do not pay. I will ask Nick and Barry what the idea behind "others" is. Imho: if you can't name it, forget it ;-)

**Comment by vegu** [comment]
fixed in 8fce887 - added probono and ixp as well
