### ISSUE TITLE
/cp/peeringdb_server/user/xxxxx/change/password/ is broken

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#248]
Looks like the last release broke the "Change Password" feature for the AC. I get a "The requested URL /cp/peeringdb_server/user/xxxxx/change/password/ was not found on this server."

**Comment by vegu** [comment]
Looks like the url changed, it is now /cp/peeringdb_server/user/xxxxx/password - unsure at this point what caused the change, my initial instinct is that it was in the 2.5.3 release when we upgraded django, but that means it'd been broken since then. 

In any case please leave this ticket open, as the link to it needs to be fixed.

**Comment by vegu** [comment]
fixed in 89335c
