### ISSUE TITLE
Verify entered phone number through 3rd party verification system

### ISSUE THREAD

**Issue by eloos** [peeringdb/peeringdb#258]
In ticket #50 the correct number format is enforced, in a next step it can be checked whether the number acutally exists, rather than whether the format is correct. We can even do two step verification this way if we want.
This would require contracting with a 3rd party provider of such services.

**Comment by karumugham** [comment]
A 3rd-party method would be nice, perhaps basic where we just verify the # is assigned; but as far as I know, most available data sources will just show if it's assigned to some carrier, not necessarily to an end user (and sources with end-user data tend to be out of date.) We could do an advanced two-step method with a dialout and verification code, but that seems complicated/expensive and could be prone to abuse.

What if we allow users to point to a reference for phone #s? (This can apply to addresses and other data too.) E.g., user enters a # and includes a link to an official website that confirms that info, or to a phone directory, etc. AC then checks the info, and the phone # gets a "verified" checkmark or something. Does that sound feasible, or too much work for AC?

**Comment by arnoldnipper** [comment]
We meanwhile to a syntax check on phone numbers. Do we want to do more? I.e. testing that a phone number/email is valid? 

@peeringdb/pc what is your opinion?

**Comment by job** [comment]
Verification of the phone number may be quite complex, as in, the phone
number may route to a NOC operation thta consider it a phising attempt
or simply not part of their duties to respond.

The verification call may end up in a multple choice menu which can be
hard to navigate for a robot.

I think I'm in favor of a simple syntax validation check (maybe django
has a module for this) and leave it at that.

**Comment by grizz** [comment]
I don't see a need to verify the phone number works either, for reasons that Job said as well as there's a cost associated with doing it and I don't see it as providing much benefit even if was able to be 100% accurate.

> I think I'm in favor of a simple syntax validation check (maybe django has a module for this) and leave it at that.

Already done in #50. :)

**Comment by arnoldnipper** [comment]
Summary:

 * do not do sophisticated verification of phone numbers

 * do basic syntax check ( already done in #50 )

**Comment by grizz** [comment]
+1 from me, which I guess is a -1 to this issue?

**Comment by shane-kerr** [comment]
-1 from me as well. 

We _could_ use the "geocoders" functionality of the `phonenumbers` module introduced in #50 and perform some extra checking, but there's always a chance that we'll have both false positives and false negatives. We could even just check the country code for validity, but it would still have the same problems. 

Plus, phone numbers change all of the time, and we don't really want to have to periodically confirm all of our phone numbers, right?

Plus, even the most sophisticated check won't help if I accidentally type "79" instead of "97" at the end of a phone number, and the other number is a valid phone number.

The only place where I would think that verifying a number is worth this much effort is if we use it for authentication in some way. In that case we'd send some nonce to the actual number in a similar way to how one confirms e-mail addresses.

**Comment by grizz** [comment]
Closing, consensus was to not do this. :)
