### ISSUE TITLE
500 Internal Server Error when affiliating with AS4680

### ISSUE THREAD

**Issue by netravnen** [peeringdb/peeringdb#307]
![image](https://user-images.githubusercontent.com/1938389/38246984-e7917aa2-3743-11e8-8465-f06076ace071.png)

Could you diagnose this `500 Internal Server Error` user `MIND` receives when trying to create ab affiliate request with AS4680 ?

Ticket: https://peeringdb.deskpro.com/agent/#app.tickets,inbox:all,t.o:16239

**Comment by vegu** [comment]
same as #279 - there is a work-around for admincom posted in that ticket as well

**Comment by vegu** [comment]
Root cause for this might be different than #278 - there appears to be some problem with the retrieval of the RiR data for this specific asn, but not necessarily caused by the same RIPE bug as described in #278.

Re-opening.

**Comment by vegu** [comment]
Thank you, @netravnen for looking into this issue - here is what was found: 

https://rdap.apnic.net/autnum/4680 shows the entity `JP00001287`

Querying https://rdap.apnic.net/entity/JP00001287 comes back with an error, causing the failure tracked by this ticket.

Solving #278 will make sure that this gets an appropriate error message as well as a ticket created for support.

However as the root cause of this is different to #278 (which is caused by a RIPE bug) we should also investigate if this particular case is something we can work around.
