### ISSUE TITLE
Allow users to upload a small logo to their record

### ISSUE THREAD

**Issue by job** [peeringdb/peeringdb#346]
A user brought up the idea to be able to decorate their peeringdb record with a logo. I like the idea but I think peeringdb should host these small images. 

See a mock-up attempt in this admincon ticket:
https://github.com/peeringdb/admincom/issues/191

**Comment by grizz** [comment]
@peeringdb/pc There are no votes on this.

I'm -1, I view a logo as mostly useless, and just adding noise. And potentially, making the info page quite ugly.

There's also usage rights, etc, but I'm not sure that would come into play a lot.

**Comment by mcmanuss8** [comment]
+1 but super low priority

**Comment by arnoldnipper** [comment]
So far, 3 +1 and 1 -1, what do the other @peeringdb/pc members think?

**Comment by shane-kerr** [comment]
+1

Having a logo is fun. We should embrace things that are not too important but are fun.

**Comment by grizz** [comment]
@peeringdb/pc 

Where should the logo be added? I was thinking maybe Under notes in the left label column? I don't think having it in the actual notes section makes sense.

**Comment by arnoldnipper** [comment]
> I was thinking maybe Under notes in the left label column

+1

**Comment by mcmanuss8** [comment]
> @peeringdb/pc
> 
> Where should the logo be added? I was thinking maybe Under notes in the left label column? I don't think having it in the actual notes section makes sense.

Works for me

**Comment by grizz** [comment]
**Summary**
Add logo upload to `org` and display it in the left column of entities under that `org`

**Comment by ccaputo** [comment]
Fixes to the above confirmed.

Next issue... Uploading a file slightly larger than 50 kb, such as 263 kb, results in "File size too big, max. 50 kb", but uploading something much larger (ex. 2 mb), results in "Something went wrong." rather than a message about the upload being too large. This will leave users confused as to the problem.

I understand the upload limit might be in the web server - not sure - thus the Upload code might not be privy to the issue, but the error message should include some hint as to the problem. Such as: "Upload failed. Please limit logos to a maximum size of 50 kb and file types: .jpg,.jpeg,.png"
