### ISSUE TITLE
Organisation: PeeringDB Suggested Entities (id: 20525)

### ISSUE THREAD

**Issue by netravnen** [peeringdb/peeringdb#361]
NAME: PeeringDB Suggested Entities
TYPE: ORG
URL : https://peeringdb.com/org/20525

1. What is the ORG object precisely used for? (function/purpose)
2. Is the intention this ORG is temporarily assigned when facilities/networks/ixes is still waiting for approval, And then afterwards (when approved) the proper ORG is assigned to an approved object?

**Comment by netravnen** [comment]
Question is asked in relation to https://peeringdb.deskpro.com/agent/#app.tickets,inbox:agent,t.o:20778,vis:5
where [/org/20525](https://peeringdb.com/org/20525) was assigned for the newly created network request. But even after approval
![image](https://user-images.githubusercontent.com/1938389/44211030-44ef3c00-a168-11e8-854c-d4338a2b7e17.png)
the ORG did _not_ change to proper ORG.

And it also looks like the proper ORG was not created when the user requested the network creation of [/asn/37308](https://peeringdb.com/asn/37308) https://www.peeringdb.com/cp/peeringdb_server/user/61319/change/?_changelist_filters=q%3Dcoollink.ng

## The result
- Network is created
- No ORG is created for coollink
- User is not added as admin of what would usually have been a newly created org called fx. coollink

**Comment by martzuk** [comment]
Could we perhaps make this only possible for facilities and not IXP or ASN? I know it was suggested we allow IXP, but to add an IXP you now have to provide details such as ixlan, which imho should only be done by the IXP owner.

Perhaps we could also add a prompt that warns the user they won't have access to edit the record and if possible to ask the actual owner of the facility to participate in PeeringDB.

Removing friction is good, but it seems like this adds quite some manual work to move things to the proper org (and create it first) when it should've been just added by the user instead of suggested.

**Comment by arnoldnipper** [comment]
See #107

**Comment by arnoldnipper** [comment]
@netravnen is this still relevant? If so, please explain. If not, please close

**Comment by arnoldnipper** [comment]
not relevant anymore
