### ISSUE TITLE
Network count differs when looking at GUI vs. API

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#368]
GUI:

https://www.peeringdb.com/fac/350 --> NYIIX --> 167

API:

curl -sG https://peeringdb.com/api/netixlan --data-urlencode fields=asn --data-urlencode ix_id=14 | jq -c '[.data[].asn] | unique | length'
168

**Comment by vegu** [comment]
@arnoldnipper hm, so the UI counts unique network objects, your query counts unique asn values on netixlan objects. In the schema netixlan objects have their own asn field which can differ from the parent network's asn.

`curl -sG https://peeringdb.com/api/netixlan --data-urlencode fields=net_id --data-urlencode ix_id=14 | jq -c '[.data[].net_id] | unique | length'` will give the expected result.

Should this be considered a bug in the UI and should it count unique asn values similar to your query? If so please flag as bug otherwise i think this can be closed.

**Comment by arnoldnipper** [comment]
@vegu imho it only should be clear what is talked about. So far all people I met used network and asn as a synonym. Maybe we only need way more **documentation**

**Comment by arnoldnipper** [comment]
@vegu / all ... what is of interest imho: # of orgs, # of ASN (aka peers), # of (logical) ports (aka IPs). I can't see how nets (aka net_id) do refelct any of these.
