### ISSUE TITLE
Communities Policy Field on the ASN Registration

### ISSUE THREAD

**Issue by fischerdouglas** [peeringdb/peeringdb#396]
The basic idea would be a link to a direct link where each ASN makes public their Communities Policy.

A more elaborated idea could be a classification of types of communities, and each ASN would inform their specific community for that action or classification.
It could be used to automate some jobs, in peers configurations, independently of the provider.

In this second case, my suggestion would be create a set of basic expected actions and classifications, and every ASN would need to inform(in case they have it) the equivalent community for that action or classification.
 - Black hole
 - No Export
 - Only for National
 - Only for Region X
 - Prepends
 - Etc

**Comment by fischerdouglas** [comment]
Original motivation for the suggestion:

Here in Brazil we have a recurring question of multiples Transit suppliers.
"Does any body has the list of communities of X?"
Where X frequently is:
 - Level3 (Century Link)
 - NTT
 - Globenet
 - Cogent
 - Oi (Brazilian)
 - Vivo (Brazilian)
 - Algar (Brazilian)
 - And many many others.

**Comment by fischerdouglas** [comment]
An additional motivation is that not all providers have that communities implemented on their networks.
Yeap, believing or not, this is a sad true...
And having this field as a public attribute, and being blank, it could cause some shame on the ASN provider operators, and take then to a good decision of implementing support to Communities.

**Comment by stillwaxin** [comment]
I was actually considering putting in a request for PDB to be able to host a single static (MarkDown potentially) page where operators can list both their peering policy in detail and any BGP communities they may support. They could be separate pages as well.

**Comment by arnoldnipper** [comment]
Networks already have a URL for their peering policy. And as long as communities are not standardized it does imho not make sense to overload PeeringDB with any additional information.

So from me a clear NACK for this feature. What do others think?

**Comment by mcmanuss8** [comment]
I think it would be valuable if we could standardize the way people communicate BGP communities and their meanings as a general problem. I agree with Arnold that without standardization, peeringdb isn't going to add much value here. The question is if this is something we should or could take on. If we want to take it on as a bigger project, I'm all for it. Alternatively, if someone else does and wants to use peeringdb as a structured data store, I'm also all for it. 

If neither of things is happening (current state), I agree we should nix this.

**Comment by mcmanuss8** [comment]
Mostly I think if we're going to do it we should do it right. Instead of just providing a blob of text, we should do something structured that's more machine readable. Like:

{
 'asn': 1,
 'communities': 
   [ { 
       'community': '1:123',
       'meaning': 'North American Route',
     }, ...],
}

or something. Otherwise we're not adding much more value than everyone defining their own format and putting it in txt or html or whatever.

**Comment by arnoldnipper** [comment]
> Mostly I think if we're going to do it we should do it right. Instead of just providing a blob of text, we should do something structured that's more machine readable. Like:
> 
> {
> 'asn': 1,
> 'communities':
> [ {
> 'community': '1:123',
> 'meaning': 'North American Route',
> }, ...],
> }
> 
> or something. Otherwise we're not adding much more value than everyone defining their own format and putting it in txt or html or whatever.

@mcmanuss8 that would be a new object `communities` which then could be linked to the `net` object. Right? @job what do you think about this proposal?

**Comment by arnoldnipper** [comment]
Communities are in use since long. Unfortunately, the meaning of communities is not standardized. And most likely never will be as each network operator has its own communities in place and do not want to change that. However, what could be achieved is to come up with a description language for communities. Then, each network may provide a _compiler_  to translate the policy into their communities.

Implementing a new `communities` object may be detrimental to this effort as this cements the status quo and leads into the wrong direction.

Anything to add, @job?

Nevertheless, @pc, please discuss!

**Comment by job** [comment]
Fully agree Arnold. Onwards to GROW in IETF :)

**Comment by arnoldnipper** [comment]
Two PC members don't support, one would do if there was a standard. There is none.
