### ISSUE TITLE
Undelete fac tool for AC

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#399]
Currently AC always has to reach out to 20C to get a facility properly undeleted. According to @vegu there is "... a command that does it, but it would need to be made a bit more user friendly and would need to have an UI made at the "Run Command" interface in /cp. If you make a ticket in the main repository i will spec it out properly, but it's likely going to be in the "major" cost range."

**Comment by vegu** [comment]
As @arnoldnipper noted, the [pdb_undelete command](https://github.com/peeringdb/peeringdb/blob/master/peeringdb_server/management/commands/pdb_undelete.py
) exists already and allows the undeletion of any of the peering related entities (org, net, fac, ix, ixlan, ixpfx, netixlan, poc, ixfac). 

This ticket describes creating a way for AdminCom to run it from the web-based control panel.

### Scope of this ticket

- streamline the command so that a UI can be easily built around it. Right now it involves first running pdb_reversion_inspect and getting the appropriate version id of the object when it was deleted, which is prone to user error and more complex than it needs to be for this purpose.
- a UI for it in the `/cp` "Run Command" section
- unit tests

**Comment by vegu** [comment]
@arnoldnipper this has been rolled to prod, instructions on how to use will be sent out early next week
