### ISSUE TITLE
Admin users are unable to add facilities / IXP

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#43]
http://ubersmith.peeringdb.com/admin/supportmgr/ticket_view.php?ticket=14000

http://ubersmith.peeringdb.com/admin/supportmgr/ticket_view.php?ticket=14016

**Comment by arnoldnipper** [comment]
Regarding Ubersmith#14016 user wrote: I was able to add it using Safari from a MAC. 
The problematic Browser was IE 11.0.9600.18349 on my official  laptop

**Comment by vegu** [comment]
Tried to reproduce the issue on IE11 on win7 and win8 without luck - we have had a similar issue with someone using firefox before, We've never been able to reproduce this (even in testing environments that matched the user's as far as OS and browser are concerned) and it likely seems to be a border case where csrf information is not passed along properly in the xhr headers for very client specific reasons.

We are fixing error messages caused by CSRF failures to be passed along correctly to the UI. So instead of a 403 FORBIDDEN error they will now see a "CSRF Failed" error which should make it easier to separate it from actual permission issues. This change will be in the next release (2.0.12)

**Comment by grizz** [comment]
Closing, better error message and still unable to reproduce.
