### ISSUE TITLE
the server rejected your data The fields network, facility, local_asn must make a unique set

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#45]
When trying to add facility "Global Switch (London 2)" to the set of fcilities of ASN 6774 this error message pops up.

![20160804-pdb-001](https://cloud.githubusercontent.com/assets/16888757/17394858/973b743c-5a2b-11e6-8ad5-5f08e00da292.png)

**Comment by vegu** [comment]
It is in the list for me already, which would cause the unique error, is it not for you?

**Comment by arnoldnipper** [comment]
ETOOLITTLECOFFEE ...

**Comment by eloos** [comment]
Yes, i realized that the problem is because after adding a facility it doesn't show up in the list, nor does it show when you are pressing save. You need to reload the page. I was adding and comparing sites from an excel sheet so I was trying to add a list of sites. So it is not a bug, but a UI issue in my view

**Comment by vegu** [comment]
Interesting, its supposed to add it to the list and scroll down to it, if it didn't that indicates some javascript issues. which version of safari was that?

**Comment by eloos** [comment]
I realized it is more subtle than that, sorry. What I do is filter on for instance 'amsterdam' and then adding doesn't add it to the list (need to learn to be specific). Again use case here is checking that all my <city>/<country> sites are indeed added, having the entire list is a drag

**Comment by vegu** [comment]
Made a ticket for this at #46
