### ISSUE TITLE
You can’t find an IXP in Montana; but you should be able too! 

### ISSUE THREAD

**Issue by mahtin** [peeringdb/peeringdb#479]
Search capabilities need to expand so they cover the address fields. You can’t (for example) search on “Billings” and find https://www.peeringdb.com/ix/199 (YRIX - Yellowstone Regional Internet Exchange in Billings, MT).

Many IXs use the *Long Name* field to fix this issue; however, it would help immensely if search was expanded.

This issue does not address the *MT* vs *Montana* issue; that’s uniquly an American issue which I’m not addressing presently.

**Comment by arnoldnipper** [comment]
In #455 we are proposing a new field for ix records. Instead of fields `city` and `country` it will have an `array` of (city, state, country) 3-tuples. Search then should be modified accordingly.

So imho it would make more sense to add this as a requirement to #455. Makes sense?

**Comment by mahtin** [comment]
In reviewing #455 (and #98 and #310) shows me that a master issue should be created to sum up all the search issues and then work on them as-a-whole. There's quite a few intertwined items at this point.

That said ... where does fixing search sit in the big picture of things? #98 has been open since Dec/2016 and has yet to be actioned.

**Comment by arnoldnipper** [comment]
> That said ... where does fixing search sit in the big picture of things? #98 has been open since Dec/2016 and has yet to be actioned.

The big picture aka roadmap still has to be developed. @koalafil is working on it.

**Comment by grrrrreg** [comment]
As mentioned in #445 I'd rather have geo-attributes derived from the facilities contained in the parent exchange object, and retiring the geo from the parent object.

**Comment by arnoldnipper** [comment]
As mentioned in #445 there is not necessarily facility information and there is also no easy way to abstract this information

**Comment by mahtin** [comment]
Today I could not find the IX in Nantes, France. A search for "Nantes" doesn't show it. However an advanced search with "Nantes" in the city name does show it up. 

HOWEVER ... you can't find the facilities when you search just on the city name. There's some inconsistent search behavior between exchange and facility within the advanced search page.

If I search for "Nantes" then I expect to find things in the city of "Nantes".

**Comment by leovegoda** [comment]
_This is intended to be a summary of the problem and a structured proposal for fixing and maintaining data quality, while helping people create good searches based on names. It is a first step on the path towards richer geographic search capability._

### User Issue
People need to be able to search for locations in different metro areas, often different countries, so that network operators can plan their growth path. Users need to find all the facilities in a given metro area and they need to know the addresses to which their networks team would be ordering circuits and x-connects.

### Problem: Lack of Normalization in Location Naming
Metro areas and facilities within them are identified in different ways in PeeringDB. They might be named in English, sometimes spelled out in full and sometimes using abbreviations. They might be named in the local language, sometimes with diacritical marks for some letters and sometimes without. 

Facilities listed in PeeringDB can also be described in multiple inconsistent ways.

### Problem: Impact on Geographic Search
The variety of naming conventions used in PeeringDB makes it difficult to search the database. Users are currently required to make multiple searches: one for each naming convention of which they are aware. This makes it more challenging for users to put a complete or consistent picture of the facilities in a metro area together. They have to spend more time on the job than they should and are never sure that they have all the data they need.

### Proposal: Normalize Existing Location Data in the Database
Normalize all variations for location names to an internationalized format for consistency at the database layer.

This should be a one time operation.

### Proposal: Normalize Inputs
Normalize new location and updates in the database using the internationalized format. 

Encourage normalized inputs through dynamic user feedback on web forms. Show a “do you mean?” dialog on user inputs for locations that  shows the user a list of location alternatives when an ambiguous term is used for a location.

Test API updates against an authoritative set of place names and divert mismatches for human review, with appropriate feedback via the API.

### Proposal: Presentation Layer Localization
Introduce a “do you mean?” dialog on user inputs for locations that  shows the user a list of location alternatives when an ambiguous search term is used. The UI should allow the user to select from a list that includes the local and internationalized spelling of a location name. 

### Operational Issues
This change should improve the consistency of location data in the database but it will not bring it up to 100% on its own. It is likely that we will need to create a process to review ambiguous locations and to validate the internal format for naming of new facilities in a location. @peeringdb/ac will need to advise on this aspect of the proposal.

### Out of Scope
This change proposal does not extend to implementing searches within jurisdictional borders, within a radius, or based on existing connections between facilities.

**Comment by leovegoda** [comment]
The work described in this issue will be addressed in issue #777. They key change from the summary I posted above is that we will normalize locations in the database using coordinates and and layer street and city addresses on top of that, as these can change from time to time but coordinates are generally more stable.

**Comment by mahtin** [comment]
A great beta release `2.28.0` the search is a thousand times better; however, you still can't find **YRIX** https://www.peeringdb.com/ix/199 (Billings, MT) when doing https://beta.peeringdb.com/search?q=Montana - yet that search works a lot better for networks, etc.
