### ISSUE TITLE
Phone number format

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#50]
every now and then I come across "suspicious" phone numbers. Are you
enforcing E.123 international notation for phone numbers? And how do we clean up
all the "garbage"?

**Comment by eloos** [comment]
Is it E.123 or E.164? E.164 looks more familiar. If we want to go the extra mile, shall we build in actual number validation? This means we check whether the number acutally exists, rather than whether the format is correct. We can even do two step verification this way if we want.
There are commercial services out there, and perhaps $MY_WORK can sponsor

**Comment by arnoldnipper** [comment]
Two step would be awesome!

**Comment by eloos** [comment]
Three decisions needed:
(1) do we enforce E.164 for new entries
(2) do we clean up existing data, and what do we do when we cannot convert? Mail the owner?
(3) do we want to use a 3rd party service to verify that the number exists when it is added?

**Comment by arnoldnipper** [comment]
ad (1): yes
ad (2): yes, but would collect all information which needs an update
ad (3): is this something you can get for free? If so: yes

**Comment by grizz** [comment]
1) yes
2) autoconvert where possible, enforce on adds, enforce when someone edits the record -- get stats and decide what to do from there? (do we have a policy on being able to email networks when we detect invalid information?)
3) separate ticket

**Comment by eloos** [comment]
@grizz I suggest we come with a common treatment for "wrong" records in #170 and ensure that as part of the deliverable we have a repeatable process to flag which phone numbers are not in a valid format.
So that means we restrict [2] to auto-convert where possible.
I have created a new ticket for [3]

**Comment by mcmanuss8** [comment]
+1 @eloos

**Comment by kay23** [comment]
👍  on 1. and 2.
Redecide how to proceed if we have an estimate how much couldn't ne autoconvert

**Comment by job** [comment]
[**yes**] on 1 and 2

3 seems near impossible or expensive. (you'll also need to keep verifying over time, what if the number goes out of service?)

**Comment by thatchrisp** [comment]
1) yes
2) yes
3) I agree with the others that it warrants its own ticket

**Comment by karumugham** [comment]
1. yes
2. yes
3. No for now, agree it's likely too complicated and expensive, and an abuse vector if we're doing dialouts to verify. Discuss further in 258.

**Comment by fhibler** [comment]
1. yes
2. yes
3. I'd do this as a separate topic. Whilst data quality is the highest good in PeeringDB, verifying phone numbers might be a tough thing to achieve. How would you declare a number as still valid? Maybe more like a 6-month reminder to review the contact information to the admins of the network/org?

**Comment by nopedial** [comment]
1) yes
2) yes
3) I agree with @job. It seems expensive at all levels to keep verification running over time.

**Comment by koalafil** [comment]
@Shawna the consensus is on 

(1) Enforce E.164 for new entries
AND
(2) Auto-convert existing data where possible 

Pls confirm if this is clear now or if you need further information to issue a quote for this one. Thanks

**Comment by arnoldnipper** [comment]
**Exactly**
