### ISSUE TITLE
Organization Merging Tool borken?

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#510]
For me, the Organization Merging Tool is broken. Doesn't work under Chrome nor Edge nor Firefox. When typing in a string in the search fields, no matches are shown.

Thus, AC currently is unable to merge organisations

**Comment by vegu** [comment]
It's trying to include the static files from the wrong place (can check by opening the browser console in https://www.peeringdb.com/cp/peeringdb_server/organization/org-merge-tool/)

Example `https://www.peeringdb.com/s/2.13.1/twentyc.edit.js` instead `https://www.peeringdb.com/s/2.13.1/20c/twentyc.edit.js`

We moved those files before we open sourced peeringdb, so not sure how this just now reared it's head. Likely the files existed in both places on prod and were recently removed? Or maybe no org merge was performed since november?

This needs a code fix, but ops can also temporarily fix it by copying the files to the old location

cc: @arnoldnipper

**Comment by arnoldnipper** [comment]
> This needs a code fix, but ops can also temporarily fix it by copying the files to the old location

@peeringdb/oc could you please do so

**Comment by ccaputo** [comment]
@arnoldnipper , I manually edited the relevant file (admin_extended.html) on the prod servers.  Please try again and report back.  Thanks.

**Comment by ccaputo** [comment]
@arnoldnipper - had a few mistakes when I did it 8 mins ago.  Should now be better.

**Comment by ccaputo** [comment]
@vegu pull request for your review: https://github.com/peeringdb/peeringdb/pull/511

**Comment by ccaputo** [comment]
@grizz https://github.com/peeringdb/peeringdb/pull/511 will need to go into any upcoming deploy to prod...

**Comment by arnoldnipper** [comment]
> @arnoldnipper - had a few mistakes when I did it 8 mins ago. Should now be better.

@ccaputo - not only better but even good ;-)
