### ISSUE TITLE
New Field "Health Check" 

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#512]
Seth Bennett from Apple brought this up. He suggested adding information where others can find health check information for my network/ix.

An easy way would be to add a new role "health check" which could take an URL (mailto or https) as a value.

**Comment by job** [comment]
Why should this be a *role*?

**Comment by job** [comment]
What is the purpose of the *health check*, what is being checked, and how do we conclude a *health* metric from this?

(just asking for clarification - I don't yet have an opinion on the idea)

**Comment by arnoldnipper** [comment]
> Why should this be a _role_?

Because it's easiest to implement  IMHO. We could also add another field to net/ix/fac of course. 

> What is the purpose of the _health check_, what is being checked, and how do we conclude a _health_ metric from this?
> 
> (just asking for clarification - I don't yet have an opinion on the idea)

Seth's idea was to provide a URL which gives information about healthiness of the network. I guess much like our [Status](http://status.peeringdb.com/)

**Comment by SethBennett** [comment]
Thanks Arnold!
Hi Job, my suggestion stems from what I've seen some peers put in the 'Notes' field.
For example, Amazon (https://www.peeringdb.com/net/1418) has links to check in order to verify system status (e.g. is the problem on my side or theirs). Apple (https://www.peeringdb.com/net/3554) has a similar link.

I imagine IXPs, transit-network providers, and others have similar dashboards that show whether a service affecting incident is currently occurring.

As for making it part of a Role; I'm totally open to how such a link get's presented. Just seems like a common enough item, that gets lumped into Notes, that maybe it deserves an explicit field.. or perhaps even another bit of data for the NOC contact.

**Comment by job** [comment]
Ah, I see what you mean. I think what might make more sense is to define a
new attribute for each "ix" and "net" object, that allows the user to
specify a URL to their status dashboard, just like where you can define a
looking glass and corporate website URL.

**Comment by arnoldnipper** [comment]
> Ah, I see what you mean. I think what might make more sense is to define a new attribute for each "ix" and "net" object, that allows the user to specify a URL to their status dashboard, just like where you can define a looking glass and corporate website URL.

and for `fac` as well. Or was there a specific reason to leave them out, @job

**Comment by job** [comment]
I’ve not yet seen a status page for a “fac”, but that doesn’t mean they
can’t exist!

**Comment by arnoldnipper** [comment]
> I’ve not yet seen a status page for a “fac”, but that doesn’t mean they can’t exist!

@job e.g. https://hostway.com/status/

**Comment by arnoldnipper** [comment]
Proposal

 * add a new field `status-dashboard` to objects `ix`, `fac`, and `net`
 * the value of this field is a URL to their status dashboard (like [ours](http://status.peeringdb.com/))

@pc please vote

**Comment by leovegoda** [comment]
+1

**Comment by ynbrthr** [comment]
+1

**Comment by shane-kerr** [comment]
+1

**Comment by egfrank** [comment]
**Summary**
- add `status_dashboard` of type `UrlField` to InternetExchange model and ix API serializer
- add `status_dashboard` of type `UrlField` to Network model and net API serializer
- add `status_dashboard` of type `UrlField` to Facility model and fac API serializer
