### ISSUE TITLE
Versioning is not working

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#531]
e.g. https://peeringdb.com/cp/peeringdb_server/ixlan/125/history/2066/ is not reflecting the status of /ix/125 as ixpfx 36.255.56.0/22 is also already deleted

**Comment by Shawna** [comment]
Please advise on how extensive you want the revert object functionality to be - mainly considering relationships that existed from and to that object at the time of the snapshot - and what user interface you envision for it.

**Comment by arnoldnipper** [comment]
UI: https://peeringdb.com/cp/peeringdb_server/obj/obj_id/history/ -> https://peeringdb.com/cp/peeringdb_server/obj/obj_id/versions would be fine

Versioning should enable rolling back an object step by step. I.e. whenever something was changed in between "Save" a new version is created.

The current history only allows for very, very coarse rollbacks.

**Comment by funkestefan** [comment]
👍
That would really facilitate the work of AC and lower the risk of "doing something wrong" for beginners.

**Comment by vegu** [comment]
> The current history only allows for very, very coarse rollbacks.

@arnoldnipper Lets say someone edits a network's prefix4 and prefix6 length and saves. Currently this creates a new version that contains both those changes. I don't think that necessarily needs to change, but if i understand you correctly, you would want to be able to rollback either of those independently?

Also with the current versioning UI, from what i've seen, it doesn't really show what changes in each version, i think we can definitely do something better there. Either highlight changes, or dont show unchanged fields at all?

I can for example envision a UI that lists all changes individually (on per row) and allows you to select which ones you want to revert. That would also eliminate having to click through too see the snapshot for each version as it is currently.

**Comment by arnoldnipper** [comment]
> but if i understand you correctly, you would want to be able to rollback either of those independently?

@vegu, if the change is done at the same time I still would be happy to just be able to roll back to the previous version w/o each step in between. Of course, the luxury version would provide that :)

**Comment by arnoldnipper** [comment]
> I can for example envision a UI that lists all changes individually (on per row) and allows you to select which ones you want to revert. That would also eliminate having to click through too see the snapshot for each version as it is currently.

There are pro and con for both. I also can see a use case to just say "roll back to the previous saved version" w/o having to specify all changes.

**Comment by netravnen** [comment]
> I can for example envision a UI that lists all changes individually (on per row) and allows you to select which ones you want to revert. That would also eliminate having to click through too see the snapshot for each version as it is currently.

A multi-select option. Were it could be possible to roll back 
- only select  changes, or
- bulk select all changes to be rolled back.[*]

*) depending on what is applicable in a given situation could be nice. Allows for granularity in what changes to roll backwards or forwards.

The simpel is to save each revision with all values. And roll either forwards or backwards between the whole key=>value array-set belonging to a given revision forwards or backwards in the object history.

**Comment by vegu** [comment]
One final concern are relationships, as the starting point of this ticket was that the prefix displayed in the current GUI wasn't correct when looking at the ixlan snapshot.

To explain what's going on - the prefix is its own object, with its own versions, and changes to it aren't currently tracked in the parent ixlan's snapshot.

If we want to be able to see related objects (such as the prefix) as they existed at the time of the snapshot this will likely require some substantial changes on how we do versioning. The parent (ixlan) would need to snapshot the version number of it's children (prefix) and every time the child (prefix) is updated it would need to trigger a new version to the parent as well. 

On the other hand maybe it's enough for now if each object (prefix in this case) can be reverted through its individual history?

**Comment by arnoldnipper** [comment]
> On the other hand maybe it's enough for now if each object (prefix in this case) can be reverted through its individual history?

Let's start with that. And please also add "IX Prefix" as a menu item on [Admin GUI](https://peeringdb.com/cp/peeringdb_server/)
![2019-07-23-18-07-14](https://user-images.githubusercontent.com/16888757/61730548-e23ff080-ad79-11e9-8ffe-a6c28a97e9de.png)

**Comment by Shawna** [comment]
@arnoldnipper 
Our proposed solution: (please review)

## Specifications for Versioning UI

### Abstract

Implement a user interface that allows peeringdb admins to view any object's history of changes as well as give them the tools to rollback / revert said changes.

### Requirements (Overview)

- Add any currently missing object types to be browsable in `/cp` (`ixpfx`, `netixlan`, `poc`, `netfac`, `ixfac`)
- History view that shows all versions (one per row) of an object, should also indicate what was changed in each version
- Version detail view that shows changes made in the version in full detail
- Rollback to version function
- Revert individual version function

### Requirements (Specifics)

#### Missing object types in `/cp`

Currently some objects are only available to be managed through their container objects (eg. prefixes in ixlan). All objects should be browsable / manageable independent from their parent views.

#### History View

Shows all versions for an object.

Show one version per row.

Each row should contain:

- version number
- date of creation
- user (if available)
- changes made

"changes made" could either be just field names, or a diff of some sort. Will need to experiment with what is viable with the visual space we have.

Action "revert" will be available via dropdown 

#### Version Detail view

Shows the changes made in the version with two columns `old` and `new`, buttons for "rollback" and "revert" will be available in this view as well.

This also sets us up to allow possible individual field rollbacks in the future, if needed.

Related objects such as children (ixlan in ix for example) will be excluded from this view, as they manage their own snapshots and should be handled through their individual version UIs.

#### Rollback to Version

Rolls back all changes made since the specified version, a new version will be created that has the object at whatever state it was in at the time of the specified version.

Show a confirmation screen that shows all changes that will be made before committing the rollback.

#### Revert individual Version(s)

This allows to revert changes made in an individual version (or multiple via multi select). If multiple versions are selected that touch the same field provide a GUI that lets you pick a value for the field from all the values available.

Show a confirmation screen that shows all changes that will be made before committing the revert

#### Handing un-deletions

The tool will allow to revert a deletion of an individual object if possible, however it will not provide the same functionality / logic of cascading undelete of children like the current undelete tool does. This is because we agreed to not handle relationships through the container object in this tool for the time being.

For example: restoring an ixlan from "deleted" to "ok" via this tool, will **not** restore any netixlans that were deleted as well.

Trying to undelete an object via this tool when the parent object is still deleted will error and block.

**Comment by netravnen** [comment]
https://github.com/peeringdb/peeringdb/issues/531#issuecomment-514708367 Check everything with me. :+1:

**Comment by peterhelmenstine** [comment]
'same same'

**Comment by arnoldnipper** [comment]
@Shawna thanks for the detailed proposals. Works for me.

**Comment by Shawna** [comment]
#531

The new version management can be accessed from the History button you
find in the upper right when looking at an entity in /cp

In the history listing it will show you one version per row, and all the
changes done in that version.

You can revert one or multiple versions or roll back to a specific version.

When reverting you may select which fields you want to revert (and which
version if more than one version touches the same field)

Rollback is only available from the version details view
Rollback is only available for versions smaller than current version



Please review both of these, and let us know if there are any issues or
questions.
