### ISSUE TITLE
inconsistent behavior on advanced search when changing tabs

### ISSUE THREAD

**Issue by eloos** [peeringdb/peeringdb#536]
Go to "Advanced search"
> First tab is exchanges, type name "belgacom" & press search => no results
> switch to tab "networks", belgacom is still selected as name, URL shows: https://peeringdb.com/advanced_search?name_search=belgacom&reftag=ix, press search, no results

In contrast when you go to advanced search, click networks and then enter "belgacom" and press search, it returns results

**Comment by arnoldnipper** [comment]
Fix: reset search field when changing tabs?

**Comment by koalafil** [comment]
I am with Eric on this one. 

Because the UI keeps the keyword in the search field of Networks after switching from IX, it fails to be informative enough towards the user that she/he had to hit Reset in between. 

If Reset is really needed, I would expect it to happen automagically as the user switches between IX tab to Networks (and Facilities too for that matter). 

Current behaviour of having the search keyword in tact in the new tab but returning no results is misleading imo.

**Comment by arnoldnipper** [comment]
Afaik there is another issue dealing with the same. Problem is that when switching tabs search is not reset

**Comment by mcmanuss8** [comment]
+1 this would be good to fix

**Comment by grizz** [comment]
+1

@peeringdb/pc Need votes please.

**Comment by arnoldnipper** [comment]
+1

**Comment by grizz** [comment]
No longer relevant since switching search backends.
