### ISSUE TITLE
Country names of search conditions not in alphabetical order (when locale = Japanese)

### ISSUE THREAD

**Issue by funkestefan** [peeringdb/peeringdb#575]
From a user:

I am using the system in Japanese, and the country names in the search conditions are in Japanese, but they are not in alphabetic order, either English alphabetic order or Japanese alphabetic order.

**Comment by ynbrthr** [comment]
It may be the case that it's true for other non-latin charsets as well. E.g. for Russian:
<img width="361" alt="image" src="https://user-images.githubusercontent.com/58094221/83637070-fdbc8000-a574-11ea-8175-0ca0589a2c58.png">
Notice the 'X' in the middle of the 'K's. Do we have folks from @peeringdb/pc with some familiarity with non-latin alphabets to check that? How does our sorting function deal with those?

Aside, it'd probably be a good idea to have a type-ahead field for searching cities, countries, rather than a drop-down

**Comment by arnoldnipper** [comment]
Didn't we have a similar issue? I.e. sorting by locale? Right, it was #356

**Comment by ynbrthr** [comment]
Right, missed that. @funkestefan are you ok to close that, it should be taken care of by #356

**Comment by funkestefan** [comment]
#356 should take care of that (sorting in browser with localecompare)
