### ISSUE TITLE
Sorting arrows are backwards for "standard" convention

### ISSUE THREAD

**Issue by grizz** [peeringdb/peeringdb#596]
I found some reference to it at https://ux.stackexchange.com/questions/2041/i-want-to-let-the-user-toggle-a-column-heading-to-sort-a-grid-by-a-date-field-h

And, since this is clearly a bikeshed issue, we could also use the icons from https://github.com/FortAwesome/Font-Awesome/issues/9464 :)

**Comment by mcmanuss8** [comment]
+1 on reversing them from where they are right now :)

**Comment by arnoldnipper** [comment]
+1 for whatever makes sense to you. I can live with both

**Comment by shane-kerr** [comment]
+1 to reverse them, _if_ we use icons such as in the FontAwesome link or have some other visual indicator of sort order.

According to the UX link, about half of the time users interpreted "up" from "down" differently, meaning that humans don't actually have any shared intuition about this. (I am suddenly reminded of [the Dress](https://en.wikipedia.org/wiki/The_dress).) To me this means that having some indication of what the interface means by "up" and "down" is important.

Even if we do not decide to include icons which help indicate order, we should probably change the icons anyway so that long-term users have a visual cue that something is different and don't just end up frustrated because things have flipped and they don't know why things seem broken until they figure out the change.

**Comment by grizz** [comment]
@shane-kerr totally agree on all counts, I'd be for icons.

I couldn't figure out which way they were "supposed" to be, which is what prompted me looking it up.
