### ISSUE TITLE
Add location of Physical IX-Port & Router Port

### ISSUE THREAD

**Issue by JGrondel** [peeringdb/peeringdb#607]
I would like the PeeringDB UI to reflect the location of the physical IX port. For most use cases a link to the facility would suffice.

The use cases where this would be relevant:
When setting up bilateral sessions over an IX you would like to keep your traffic as local as possible. Especially when peering with a network that has multiple ports on an exchange you would want to minimize latency and improve on resilience. One would normally prefer to set up sessions in the same facility, over sessions in the same metro, country or even cross border sessions.

Currently most exchanges offer a member list in the standardized euro-ix json-format where the requested information is optionally listed. Unfortunately, this format is not meant to be read and used by a human. Also it should be noted that some networks have automated processes based on PeeringDB and not on the Euro-ix format. 

I do see several ways the information could be presented in the GUI and/or the API. 
Information could be added to the “Peers at this exchange point” on the IX pages and/or “Public Peering Exchange Points” on the network's page. 
One could even argue for complete new pages per port where more relevant information could be shown. 

Note: Although not part of this request this may also be the time to list the location of the router connected to the IX-port. This router may be in the same facility as the switch port but could also be on another continent. Listing the router’s location would give an insight in remote-IX participation.)

**Comment by job** [comment]
I support this proposal, but only if we also allow for the "location of the router connected to the IX-port" to be specified.

Some suggestions for clarification:

Location of Physical IX-Port: the facility in which the port connected to the IX fabric is located. This means that when an "network" user indicates they are connected to an IXP, they should be presented with a drop-down menu which shows only the facilities in which the specified IX is present. This information potentially could be pre-filled with information from the euroix json data feeds.

Location of the Router port: the facility in which the router port on the "network" side is located. This means that when an "network" user indicates they are connected to an IXP, they should be presented with a drop-down menu which shows only the facilities in which the network themselves is present.

In practical terms - NTT might have a router in "InterXion Science Park", which is connected to an AMS-IX port located in NIKHEF. The "IX port" would be in NIKHEF, the router port would be in Interxion. 

If we make a sort of wizard for people to quickly add ports, we can hopefully make the wizard clever by asking the questions in such a way that we can skip over redundant questions (in case the Router port and IX port are in the same facility).

**Comment by job** [comment]
Further more - if we accept the notion of in more detail listing where the IX port is and where the Router port is, the user interface could leverage a simple haversine calculation to help users analyse the data they are looking for (for instance, we could maybe have a sorting button so you can sort on distance, or a search engine filter to list results that are closer by than X)

**Comment by arnoldnipper** [comment]
+1 ... very much like @job 's ideas

**Comment by kay23** [comment]
I support @job 's proposal on how to implement it by associating the Physical IX-Port and the location of the Router port.

**Comment by fkorsback** [comment]
+1 

I would definately like to see a flag or field that clearly shows in which metropolitian-area the ip-adress im about to peer with is currently in.

**Comment by schiederme** [comment]
If would be nice, if networks can add a tag for remote peering.

**Comment by grizz** [comment]
+1 from me, great ideas! Off the top of my head, what do we do about private facilities? Could allow for manually entering long / lat? or Just leave it for now and people can pick the facility closest to where they're at?

**Comment by arnoldnipper** [comment]
What do you mean by "private facilities", @grizz? I guess this is something different then "Private Peering Facilities". Right? 

Currently, we require that facilities to be listed have to offer service to the public. However, when introducing this feature it would also make sense to list those _private facilities_.

**Comment by fkorsback** [comment]
> +1 from me, great ideas! Off the top of my head, what do we do about private facilities? Could allow for manually entering long / lat? or Just leave it for now and people can pick the facility closest to where they're at?

Thats why i was thinking instead of flagging which facility the "location of the port connected to the IX that holds the IXLAN IP-Adress" it could be marked with "closest city" instead of facility. Cause in reality what we (the people peering on IX:es) care about is the proximity to the peer, not really if that network is coming through facility1 or facility2 in the same city. But if the peer comes in from south-africa to for example amsterdam, its important to know. 

So to avoid pitfalls such as unregistered facilities, private facilties, secret facilities (for example this happens quite alot in Sweden) maybe a geographical affiliation is good enough?

**Comment by arnoldnipper** [comment]
So what about either `fac_id` or (`longitude`, `latitude`)?

**Comment by mahtin** [comment]
@arnoldnipper - it should always be a `fac_id` because you want all locations to have the full compliment of attributes independent of usage. A `fac_id` maps into the info in `/api/fac` and that's very useful.

For a small IX there should be a data structure (or documentation) that maps an IX's `fac_id` to be the same as the physical IX port `fac_id`.

Oh; so what happens when a network long-hauls it's port from the IX's `fac_id` to some other datacenter `fac_id`. That should not mean the IX is listed within that other datacenter. There should be an explicit understanding that only the IX's `fac_id` controls location vs. the networks `fac_id`.

BTW: If you go read #515, you would see that these Virtual-IX's don't have a valid main `fac_id` and hence, if we allow them, then the networks/members/customers all need an explicit `fac_id` per entry. So maybe #515 defines this need!

**Comment by arnoldnipper** [comment]
> BTW: If you go read #515, you would see that these Virtual-IX's don't have a valid main `fac_id` and hence, if we allow them, then the networks/members/customers all need an explicit `fac_id` per entry. So maybe #515 defines this need!

@mahtin, there are also a couple of so-called Internet-backbone-interconnection IXs which don't any `ixfac` records. Otoh there are so-called Virtual-IXs which have `fac_id` records.

**Comment by arnoldnipper** [comment]
> it should always be a `fac_id` because you want all locations to have the full compliment of attributes independent of usage

@mahtin, not all networks are in a location which has a `fac_id`. Hence (`longitude`, `latitude`) would be needed.

**Comment by mahtin** [comment]
> @mahtin, not all networks are in a location which has a fac_id. Hence (longitude, latitude) would be needed.

That's being damn lazy. You either have facilities or you don't exist. Period. Don't mess up a database with random overlapping data fields just because it's the easy thing to do. If a network (or IX or IX remote port) decides it's in some other place, then provide a way to create a facility (and hence `fac_id`). At least then, there's consistency and a way-forward to allocate ownership of facilities.

> Just to give you an idea. We have 725 ix, but only 497 have at least one ixfac record associated. Unlikely that we already have 228 so-called Virtual-IXs.

Indeed. It actually sounds like we have IXs that need some serious review so that missing data is created.

**Comment by grizz** [comment]
We have an easy way to create a facility: https://www.peeringdb.com/suggest/fac

From comments, and review, I think forcing `fac_id` is a good idea, if it's a secret private facility on the Router Location side, it's such an edge case, it probably doesn't matter. Adding the two fields to `netixlan` would be beneficial to most users.

1. They could either pick the nearest facility, but then it would show them present in a facility they may not be

2. We could allow "Router Location" to be null for networks

3. We could add "private" to the Facility object, let them set a lat/long, and only allow them to pick it.

I'm leaning towards 2.

**Comment by arnoldnipper** [comment]
@grizz, all of what you propose does not really make sense to me. Only because you have a hammer not everything has to be a nail. 

Why are we leaned towards forcing `fac_id`? Only because we need (`longitude`, `latitude`). Right`So why not using either of this?

**Comment by grizz** [comment]
Because in 99+% of the cases, people are going to be connected at a facility we already have, so it would be a lot easier for them to just select it from a drop down.

It forces both networks and IXPs to keep their data updated.

Additionally, it keeps the code, API, and UI clean and easy. If it's required, imagine explaining to people that they had to go look at the facility they're connected to and copy paste long/lat into the fields.

And as @mahtin said:

> You either have facilities or you don't exist. Period.

Which I fully support, with the exception of "None" if you don't want to disclose it or are virtual :)

**Comment by mahtin** [comment]
> Which I fully support, with the exception of "None" if you don't want to disclose it or are virtual :)

Yes, I'm a +1 on "None" (as described by @grizz noted as option 2 above).

**Comment by arnoldnipper** [comment]
> Additionally, it keeps the code, API, and UI clean and easy. If it's required, imagine explaining to people that they had to go look at the facility they're connected to and copy paste long/lat into the fields.

Of course, each `net` or `ix` is in some building, but not necessarily in PDB `fac`. There might e.g. `ix` where you only can connect to via a carrier (i.e. remote connections).

And of course, I don't want anyone to copy-paste geolocation data. They only may have to provide these, if they are not located in a facility.

Let's do a proper modelling and not just use the hammer :)

**Comment by arnoldnipper** [comment]
What about 

 * adding new fields `net_netfac_id` (`net` endpoint) and `net_ixfac_id` (`ix` endpoint) to `netixlan`
 * default for both is `null`
 * `net_netfac_id` is the `fac_id` of a facility where `net` is. Hence a `netfac`record also should exist
 * `net_ixfac_id` is the `fac_id` of a facility where `ix` is. Hence a `ixfac`record also should exist
 * value is only settable by `net`

**Comment by mcmanuss8** [comment]
> What about
> 
> * adding new fields `net_netfac_id` (`net` endpoint) and `net_ixfac_id` (`ix` endpoint) to `netixlan`

Maybe netfac_id and ixfac_id ? The extra net in the front could be confusing IMO. 

> * default for both is `null`
> * `net_netfac_id` is the `fac_id` of a facility where `net` is. Hence a `netfac`record also should exist
> * `net_ixfac_id` is the `fac_id` of a facility where `ix` is. Hence a `ixfac`record also should exist
> * value is only settable by `net`

Seems good

**Comment by DenisKlimek** [comment]
+1 We support this too. Specially if you're connected to a IXP which is spreaded all over a country or even multiple countries.

**Comment by netravnen** [comment]
On Mon, 13 Jan 2020 at 13:03, Denis Klimek <notifications@github.com> wrote:

> +1 We support this too. Specially if you're connected to a IXP which is
> spread all over a country or even multiple countries.
>
> & with remote peering becoming more of a thing in recent years. (refer to
e.g. study published via the RIPE NCC in 2018,
https://labs.ripe.net/Members/vgiotsas/uncovering-remote-peering-at-internet-exchange-points
)

**Comment by vidister** [comment]
Maybe it's sufficient to provide the location of the IXP port and the latency from there to the peering Router.
That would be more useful for traffic engineering since the plain locations don't help much if you don't know which fiber path is being used. Also that would solve the problem of having to record all private locations which could be secret.

**Comment by job** [comment]
> Maybe it's sufficient to provide the location of the IXP port and the latency from there to the peering Router.
> That would be more useful for traffic engineering since the plain locations don't help much if you don't know which fiber path is being used. Also that would solve the problem of having to record all private locations which could be secret.

I think that further complicates things because it no longer depends on user contributed data, explicit involvement of the ixp, and a clear consensus on what route server where's measurement means what. 

One can even argue that fiber paths can automatically be assumed in many locations given the abundance of KMZ files. "Private locations" in context of peeringdb, are not "private" but for "private peering". The word private means the opposite in our terminology in many cases funny enough.

I think having both IXP port and Router port is important

**Comment by arnoldnipper** [comment]
> I think having both IXP port and Router port is important

Strong ACK. KISS ... from there anyone may build fancy tools.

**Comment by DenisKlimek** [comment]
What about using the data from the IXP itself which is very often in JSON available? Many IXPs are including the physical location of the connected switch to it.

Mit freundlichem Gruß
Stadtwerke Norderstedt

Denis Klimek

Carrier Manager & Professional Network Engineer
IP-Systemtechnik

Tel: +49 (0) 40 / 521 04 – 1049

dklimek@stadtwerke-norderstedt.de<mailto:dklimek@stadtwerke-norderstedt.de>
www.stadtwerke-norderstedt.de<http://www.stadtwerke-norderstedt.de/>

Von: Arnold Nipper [mailto:notifications@github.com]
Gesendet: Dienstag, 14. Januar 2020 01:07
An: peeringdb/peeringdb
Cc: Klimek, Denis; Comment
Betreff: Re: [peeringdb/peeringdb] Add location of Physical IX-Port & Router Port (#607)


I think having both IXP port and Router port is important

Strong ACK. KISS ... from there anyone may build fancy tools.

**Comment by JGrondel** [comment]
> What about using the data from the IXP itself which is very often in JSON available? Many IXPs are including the physical location of the connected switch to it. 

For the location of the IXP port this sounds reasonable for those networks that allow IXP updates.
Be aware that IXP's are not aware/do not list the location of the router.

Unfortunately naming of data centres is not always consistent. However, the  IX-F Member List does allow to include a "pdb_facility_id" for data centres. If the localisation of the IXP port would (partially) be based on the .json scheme this could be used.

**Comment by martzuk** [comment]
> I think having both IXP port and Router port is important

I agree, but I see a conflict in a few places. We're trying to show a physical attribute (well actually two), but we seem reluctant to enforce at minimum 1 facility, see #611. 

IMHO the user should be able to select the port location as a drop down, populated by the facilities an IX lists on its entry. To cover the situation of it being an entirely (playground IX) we should have a "Virtual" facility in pdb (see #515). To cover the situation of a facility not being listed the IX can either ask the site operator to add it, or it can be suggested to pdb (https://peeringdb.com/suggest/fac). The user should then be able to select the router location by either selecting "same as port" or "remote".

This does the following:
- Makes it easy for a user to provide the information without copying/pasting lat/lon
- Keeps the data quality high
- Separates "real" (seems to be a subjective term) and "playground" IXPs without having to remove them

To echo what Martin says:
> You either have facilities or you don't exist. Period.

However we want to encourage use of PeeringDB in BGP experimentation and the like, so the above feels it can accomodate both the use case of improving PeeringDB functionality and data quality without excluding said use case of playground IXPs (which seem to have ballooned as of late).

**Comment by arnoldnipper** [comment]
@martzuk there are also many non-playground ixes having no facility they are in. For whatever reason. We can't and probably don't want to force them to add one as one of the topmost paradigms of PeeringDB is that the user decides what to publish. Or not to publish.

**Comment by martzuk** [comment]
Then how do we expect people to list where a port/connection is, if it isn't anywhere?

**Comment by job** [comment]
I expect the listing to be optional

**Comment by arnoldnipper** [comment]
> Then how do we expect people to list where a port/connection is, if it isn't anywhere?

@martzuk they may still list their end if the IX does not provide facility information. No?

**Comment by martzuk** [comment]
Not if the facility doesn't exist on peeringdb like you said. 
> there are also many non-playground ixes having no facility they are in.

If the facility is on peeringdb it's hardly a stretch to expect the ix to list it as a pop

**Comment by arnoldnipper** [comment]
Maybe I misunderstand this whole issue. For a connection to an ix (i.e. there is a netixlan object), there is an A-End (net) and a B-End (ix). For the A-End there should be a netfac object with net_id being the id of the net connected to the ix. And for the B-End there should be an ixfac object with ix_id being the id of the ix where the net is connected to. A-End should be selectable and specified by the net. B-End should be selectable and specified by the IX. This is my understanding of how it should work.

And whether an IX list a facility as a pop is up to the IX.

**Comment by job** [comment]
Dear all - I'm attempting to summarize what has been discussed so far infused with my perspective on what potential direction we can take here.

The `netixlan` object can be extended with two `a_side` and `z_side` attributes. The `*_side` attributes point to a `fac_id`. The network operator (`net_id` owner) can set the `a_side` attribute to whatever `fac_id` they are present in, the IX (`ix_id` owner) can set the `z_side` to whatever `fac_id` the IX is present in.

I'm sure the euro-ix json format can be used to help feed the `z_side` `fac_id` values, and the l3 network operator can either use the API or the web UI (via a pull down menu) to set the `a_side`. 

Both `a_side` and `z_side` are entirely optional. 

Data Ownership: IX owns `z_side`, Network operator owns `a_side`. If there is disputes conflicts the AC can handle them.

Thoughts?

**Comment by job** [comment]
To add: over time it is possible a network operator migrates the connection to a different datacenter via layer-2 or optical backhauling, then the network operator can update `a_side` to the new `fac_id` where according to them the `netixlan` connection is terminated in a router. This is user submitted data - if the network operator indicates that their LINX connection is terminated in Africa, so be it. That is up to them.

Similarly, an IX can migrate customers, an IX may accept the incoming cross connect in datacenter A, but in reality connect the cross connect to the layer-2 fabric in datacenter B. An IX might migrate customers from datacenter to datacenter through optical backhauling - again, that is up to the IX. They can set `z_side` to whatever they think is appropriate.

Both sides are user submitted data, and technology independent.

**Comment by kevin-nlix** [comment]
I agree with the approach regarding the ownership model; it makes a lot of sense taking into account the processes around these connections.

The only thing I'd change in your proposal are the column names; using ambiguous terminology like `side` leads to confusion and thus bugs. I suggest calling them `net_fac` and `ix_fac`, clearly indicating which part of the connection they belong to. The downside of this naming is that there's also the `ixfac` and `netfac` tables, so it can also be somewhat confusing as we're not going to reference those, hence the `_` in between which you would not use when referencing those tables.

**Comment by job** [comment]
@kevin-nlix yeah... I picked A & Z side because that is terminology often found in describing interconnections in inter-company context, but I'm not married to any specific terms, though I think `ix_fac` vs `ixfac` will lead lots of confusion, because we don't really pronounce underscores `_` in voice communication :-)

**Comment by arnoldnipper** [comment]
@kevin-nlix and @job: what about `net_side` and `ix_side`?

**Comment by kevin-nlix** [comment]
I could support that. At that point you're basically saying `the Network/Internet Exchange side of the Public Peering Exchange Point`. In the current data model the term `side` isn't really ambiguous; it shouldn't be that big of a deal for now. This is also a new scenario for the data model as this kind of connection between models hasn't been made before, so there's no right or wrong here.

Also, I was thinking about this over the weekend and I've always wondered why the connection between `NetworkIXLan` and `Facility` wasn't there yet. Is there any historical reason why this hasn't been implemented or is it just a case of 'never got around to it'? I suspect the latter, but in case of the former it's good to know about the considerations of the past.

**Comment by arnoldnipper** [comment]
> Also, I was thinking about this over the weekend and I've always wondered why the connection between `NetworkIXLan` and `Facility` wasn't there yet

A simple relation between `netixlan` and `fac` does not make sense. That's the reason we no enhance the data model.

**Comment by as44980** [comment]
> Data Ownership: IX owns `z_side`, Network operator owns `a_side`. If there is disputes conflicts the AC can handle them.

This concerns me as it would at least appear to dilute the "user submitted" data model, which if this was implimented would undermine the value of PeeringDB in my eyes :(

**Comment by arnoldnipper** [comment]
> This concerns me as it would at least appear to dilute the "user submitted" data model, which if this was implimented would undermine the value of PeeringDB

Would you mind to explain, @as44980?

**Comment by as44980** [comment]
> Would you mind to explain, @as44980?

Sure, based on..

> the IX (ix_id owner) can set the z_side to whatever fac_id the IX is present in.

If the Network declines to set any value for the a_side (or sets this to the poposed value of "None"), but the IX is encouraged to list the z_side based on where they deliver the service, does this not risk "outing" the network as being present in or near to the z_side facility when they have decided not to share this information?

**Comment by as44980** [comment]
> Of course, each `net` or `ix` is in some building, but not necessarily in PDB `fac`. There might e.g. `ix` where you only can connect to via a carrier (i.e. remote connections).

While I also assume every Network is going to have a physical presence in some building somewhere, from what I can see PeeringDB providers the ability for `net` records to indicate which (if any) "Private Peering Facilities" they are present in from the list of Facilities with `fac` objects..

I, and I assume many others, have taken this to mean "Facilities where this network is able to accomodate private peering" rather than "Facilities where this network engages in peering, which are themselves private"... and of course for private peering to be via a dedicated physical interconnect :)

If this is the correct inpterpreration then I would not expect a network which doesnt support 'private peering' to list any facilities in the "Private Peering Facilities" section, even if they are present in one or more Facilities with `fac` records for the purposes of connecting to a "Public Peering Exchange Point".

Thus to expect Networks to populate the `a_side` such that the "`net_netfac_id` is the `fac_id` of a facility where net is" and "a `netfacrecord` also should exist" would appear to require networks to indidate they are able to support Private Peering at any Facility they wish to list as the `a_side` of an `netixlan`..

Is this intentional?

**Comment by arnoldnipper** [comment]
> If the Network declines to set any value for the a_side (or sets this to the poposed value of "None"), but the IX is encouraged to list the z_side based on where they deliver the service, does this not risk "outing" the network as being present in or near to the z_side facility when they have decided not to share this information?

This only says that the network is connected to the ix in the give facility. However, it does not say anything about where the network is.

**Comment by as44980** [comment]
> This only says that the network is connected to the ix in the given facility. However, it does not say anything about where the network is.

That sounds a lot like "we only know where you phone is located at all times, this does not say anything about where _you_ are located" ;)

**Comment by arnoldnipper** [comment]
> That sounds a lot like "we only know where you phone is located at all times, this does not say anything about where _you_ are located" ;)

You should see more movies on how to see how to trick LEAs etc ;-)

**Comment by as44980** [comment]
Jokes aside, should Networks have a say on wether an IX publishes information on where the `z_side` of their connection is located?

FWIW some IX's make this information publically available, some to other members only and at least one which does not disclose this at all ;)

**Comment by arnoldnipper** [comment]
> Jokes aside, should Networks have a say on wether an IX publishes information on where the `z_side` of their connection is located?

No

**Comment by as44980** [comment]
> > Jokes aside, should Networks have a say on wether an IX publishes information on where the `z_side` of their connection is located?
> 
> No

Ergo my concerns that, while this concept has plenty of merits, the proposed implimentation dilutes the "user submitted" data model by allowing somebody other than the Network to publish data which they may regards as sensitive without their consent :(

**Comment by arnoldnipper** [comment]
You still have to explain why the network should be authoritative for the `z_side`.  Until then your claim is void.

**Comment by as44980** [comment]
> You still have to explain why the network should be authoritative for the `z_side`. Until then your claim is void.

I dont beleive that I have suggested the Network should be authoratitive as to the value of the `z_side`, simply that allowing anyone other than the Network to decide if this value is published would appear to dilute the user submitted data model..

Ie the Network opts to configure and display the `a_size` values that would clearly be user submitted data, in line with the PeeringDB model.

However i fail to see how having this value set by somebody other than the Network, and as you highlight in this case the user with have "No" say on whether an IX publishes information on where the z_side of their connection is located..

Which to be does not align with the (supposedly) user submitted data model of PeeringDB since the user does not submit the `z_side` information..

And from what I can gather this model would not consider the `z_side` data related to where this Network connects to a given IX to belong to the user, even in cases where the IX is contractually prohibited from revealing such details (at least for specific customers).

So IMHO this is slowly, but surely, chipping away at the core concept of PeeringDB's data ownership model... 

thus -1 from me :(

**Comment by job** [comment]
When the IX is contractually prohibited from publishing `z_side` information, the IX (also a PeeringDB user) should not publish the `z_side`.

**Comment by as44980** [comment]
> When the IX is contractually prohibited from publishing `z_side` information, the IX (also a PeeringDB user) should not publish the `z_side`.

While I dont disagree with this in pricinple, I am concerened that highlighting that an IX is  "also a PeeringDB user" is suggesting that information provided by an IX about their members is "user submitted".. is that what is being suggested here?

If so would it also be considered "user submitted" if a facility owner was to request the ability to list all of the networks who it feels to be present in facilities which themselves are owned by the facility operator (contractual oblibations nowithstanding)?

**Comment by as44980** [comment]
> > Of course, each `net` or `ix` is in some building, but not necessarily in PDB `fac`. There might e.g. `ix` where you only can connect to via a carrier (i.e. remote connections).
> 
> While I also assume every Network is going to have a physical presence in some building somewhere, from what I can see PeeringDB providers the ability for `net` records to indicate which (if any) "Private Peering Facilities" they are present in from the list of Facilities with `fac` objects..
> 
> I, and I assume many others, have taken this to mean "Facilities where this network is able to accomodate private peering" rather than "Facilities where this network engages in peering, which are themselves private"... and of course for private peering to be via a dedicated physical interconnect :)
> 
> If this is the correct inpterpreration then I would not expect a network which doesnt support 'private peering' to list any facilities in the "Private Peering Facilities" section, even if they are present in one or more Facilities with `fac` records for the purposes of connecting to a "Public Peering Exchange Point".
> 
> Thus to expect Networks to populate the `a_side` such that the "`net_netfac_id` is the `fac_id` of a facility where net is" and "a `netfacrecord` also should exist" would appear to require networks to indidate they are able to support Private Peering at any Facility they wish to list as the `a_side` of an `netixlan`..
> 
> Is this intentional?

Would be nice to get feedback on these points as well ;)

**Comment by tpaseka** [comment]
Think this is important to get included into PeeringDB. Support this action!

**Comment by arnoldnipper** [comment]
Summarising from what @job wrote [here](https://github.com/peeringdb/peeringdb/issues/607#issuecomment-698932970)

**Summary**

 - The netixlan object is extended with `a_side` and `z_side` fields
 - The `*_side` fields point to a `fac_id`
 - Only the network operator (net_id owner) can set the `a_side` field to a valid `fac_id` of a `fac` they are present in
 - Only the IX operator (ix_id owner) can set the `z_side`field to a valid `fac_id` of a `fac` the IX provides its service
 - Both `a_side` and `z_side` are optional and may be `null`
 
 @peeringdb/pc, please vote

**Comment by martinhannigan** [comment]
Thanks for the team mention!

Not awful, but misplaced. I'll -1 for now. 

The concept is certainly worth consideration. There has been smoke around the actual physical location of all objects. This idea may cause further fragmentation that leads to more confusion. 

Hasn't come to consensus, but seems like there is interest in a straw man such as:

Campus object (definitions are the blocker)
-Physical Address Object (no blockers yet)
----Facility objects (exists)
 {net, ixp, etc objects live here and exists)
-------Sub facility objects (interest from more than one)
 {net, ixp, etc objects live here. no blockers yet}

The ability to nest (in this case) IXPs in a physical, facility or sub facility object well defines where the port actually is.  I'd like to stop focusing on IXPs and shift a little focus to a holistic environment. Site selection is getting hard and our investments could be more focused on a wider user base.

PeeringDB v3?

Warm regards,

-M<

**Comment by leovegoda** [comment]
The @peeringdb/pc discussed this issue at [its November meeting](https://docs.peeringdb.com/committee/product/notes/2022-11-03_Product_Committee_Notes.pdf). I followed up with @JGrondel to clarify the use case.

The intended use case is to allow IXPs to provide the location of each switch each port is provided on. This information can help networks peering at the same facility to keep their traffic within a switch, improving resiliency. The data for the switch location should come from the `pdb_facility_id` attribute of the `switch` statement in the [IX-F Member Export Schema](https://github.com/euro-ix/json-schemas) JSON file provided by the IXP. Because IXPs using this API tend to automate the production of their export using tools like [IXP Manager](https://www.ixpmanager.org/), the data should remain fresh. Not all IXPs provide data using the IX-F Member Export Schema or provide complete data but take up is growing. 

One consequence of implementing this feature would be visibility of which IXPs operate a metro area peering LAN and more geographically distributed IXPs. 

Informal conversations with a number of large content providers indicate that they would find this information valuable and would build tools to use it.

Note that this proposal would give IXPs a clear way to share information about the location of a switch in a facility through PeeringDB. The location of networks' peering routers would be a separate problem to solve, if there is demand for that information.

**Comment by peterhelmenstine** [comment]
So to 'improving resiliency' and not necessarily performance which is
another characteristic that could come out of this.

fyi - just reiterating there was a previous discussion on performance by
knowing the latency to a peer. Not quite the same thing.

**Comment by arnoldnipper** [comment]
@leovegoda and @peeringdb/20c, can we please come up with a design, please.

**Comment by apolyr** [comment]
+1 for this feature - at least as it is summarized by leovegoda on Nov 11, 2022

Actually, I like to propose two additions to the internet exchange view:
a.	Additional column within the table “Peers at this Exchange Point”, listing the facility name per entry
b.	Additional column at “Local Facilities” table, listing the number of ASNs of this IXP within each facility

Both would give good visibility to anyone who tries to understand where the "denser" facilities of the IXP would be.
