### ISSUE TITLE
When creating an ix via the API also return ixlan_id and ixpfx_id

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#609]
For creating an `ix` record a `prefix` field has to be provided. Generally speaking, `prefix` does not belong to the `ix` record, but to the `ixpfx` which in turn belongs by `ixlan`.

To be efficient the POST call should also return `ixlan_id` and `ixpfx_id`. Otherwise an additional call to find out these ids have to b emade.

Does that make sense, @grizz  and @vegu? If so, @peeringdb/pc, please support.

**Comment by shane-kerr** [comment]
+1

Also, are there other create operations where a similar logic applies?

**Comment by arnoldnipper** [comment]
> Also, are there other create operations where a similar logic applies?

`ix` is the only record which requires a field which actually belongs to a different record (`ixpfx`).

**Comment by grizz** [comment]
Requiring the prefix was just implemented in #277 and I think we might have made the API a bit sloppy with that. I wonder if a better approach since IX is different wouldn't be to add a separate "sugar" call to create an IX with all the info at once?

I'll discuss internally after the holidays and see what we can come up with.

**Comment by arnoldnipper** [comment]
With the planned removal of `ixlan` could it make sense to remove `ixpfx` as well and move this information to `ix` as `prefixlist4` and `prefixlist6`? For migration and maybe other use cases we would still have to allow multiple ixpfx.

**Comment by grizz** [comment]
> With the planned removal of ixlan could it make sense to remove ixpfx as well and move this information to ix as prefixlist4 and prefixlist6? For migration and maybe other use cases we would still have to allow multiple ixpfx.

I'd be for that, but it would require PDB api v3. Created #625 to start collating these.

**Comment by vegu** [comment]
With #21 the ixlan created with the ix will have the same id as the ix (even if we do NOT migrate old ixlan ids, going forward this id equality is going to be the case) so that issue solves itself.

With that in mind, all we need is the `ixpfx_id` field added to the POST response, correct?

cc: @peeringdb/pc @grizz @arnoldnipper

**Comment by arnoldnipper** [comment]
> With that in mind, all we need is the `ixpfx_id` field added to the POST response, correct?

Yes, that's correct as the `ixlan` will be dropped with V3. However, for completeness sake, I would like to add `ixlan_id` as well. Is there any issue with doing so?

**Comment by vegu** [comment]
No issue, just double checking since the ixlan id can now be inferred from the ix id

**Comment by grizz** [comment]
**Release Summary**

When creating an IX record via API, the call will also return the implicitly created ixlan_id and ixpfx_id. This makes it simpler and reduces the number of calls that need to be made to the API.
