### ISSUE TITLE
Add irr_as_set and irr_as_set6 to netixlan

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#612]
Relates to #151 and #605.

To provide a hook for fine-grained routing-policies add an `irr_as_set` and `irr_as_set6` to `netixlan`. This field has a **single** as-set/route-set as value. Default is "" and means that the policy is taken from the `net` object. If != "" it is overruling the value at `net`.

Remark:  If accepted we also would have to add `info_prefixes` and `info_prefixes6` to `netixlan`.

Though proposing I tend to -1 as we really would cover corner-cases.

**Comment by job** [comment]
Is the purpose to allow people to specify "Per IX connection" specific AS-SETs?

**Comment by arnoldnipper** [comment]
> Is the purpose to allow people to specify "Per IX connection" specific AS-SETs?

Yes and no ... this was a proposal from some user. Would be good to talk about it and to make up our mind. There might be corner cases where this is useful. In general, I don't see a need for this feature.

**Comment by sspies8684** [comment]
If this was implemented, I would support it by integrating it into the internal DE-CIX systems.

**Comment by job** [comment]
i propose we close this issue in line with the thinking developed in https://github.com/peeringdb/peeringdb/issues/605

**Comment by arnoldnipper** [comment]
As this gets no traction

**Comment by as44980** [comment]
> As this gets no traction

While I agree this particular approach didnt seem to have much support, it seems that this particular topic has been divided into a great many smaller "issues" which all then get closed due to lack of consensus..  

The net result seems to be that any issues or suggestions that come from outside of a small list of individuals is treated very differently from those which come from the rest of us :(
