### ISSUE TITLE
Update news for networks

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#63]
http://ubersmith.peeringdb.com/admin/supportmgr/ticket_view.php?ticket=6841

... We were
hypothesizing it might useful if we could submit a update request that would be
forwarded to the listed peeringDB admin for approval. Then they could click
through and update the entry or deny it. It seems that's not on the road map, so
I'll communicating with them directly. 

Thank you for your quick response. 

Cheers!

Russell Adams, Senior Product Architect
365 Data Centers
Desk  415.901.5714
Mobile 415.867.8017
radams@365datacenters.com
365datacenters.com

**Comment by mcmanuss8** [comment]
What's the use case here? "We at $network are now in $new_ix?" or "We at $network are now offering $speed connections?" or "We at $network are now merging with $other_network?"

**Comment by grizz** [comment]
I don't understand this either

**Comment by arnoldnipper** [comment]
The use case is: "Hey, I've detected that your $entry is wrong. This is the update"

**Comment by eloos** [comment]
If the use case is referring to bad data that is being flagged for the owner/peeringDB admin to take action, then I suggest this is a sub-case of #170

**Comment by arnoldnipper** [comment]
Iirc the use case Russell had in mind was that he wanted to remind networks to list that they are in his facility

**Comment by eloos** [comment]
@arnoldnipper ok that is good input, in that case it is similar to having an IX-F feed. Either way it is not up to the admin committee to show networks to be present in a particular facility. Do we want to make an API/entry screen that allows data-centre operators to suggest that a particular network is in their facility? Then just like in #61 we could make that part of an update request sent to a user.

**Comment by arnoldnipper** [comment]
Not really imho ... what we could do is to add an email address to fac entries which gets emailed every time a network registeres / withdraws.

**Comment by eloos** [comment]
@arnoldnipper I don't think that resolves the use case, I have had it too that DC's reached out to me to ensure I added them as part of my peeringdb record when they were part of our footprint. It seems Rusell's use case is about that. Such an email would not solve it.
That said, this only seems to be bad data from a 3rd party point of view (DC), not from a network point of view. If a network doesn't list a building it is probably because they have no significant presence there.
@arnoldnipper you had reopened this issue, are you ok that we close this again as a wontfix?
