### ISSUE TITLE
Bug in renumbering tool 

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#660]
Obviously there is an issue in handling longer masks (see #304 ). I also noticed that the masks still have to be of the same size. That does not make sense. Typically ixes go from a /n to /n-1 or even /n-2.

![20200306 PeeringDB 03](https://user-images.githubusercontent.com/16888757/76101715-2a411a00-5fcf-11ea-9e01-a88b692a8aae.png)

@peeringdb/pc please +1

**Comment by shane-kerr** [comment]
+1

**Comment by grizz** [comment]
I'd have to look back and find the discussion on this, but I believe that we all decided renumbering to the same prefix length was the only thing that made sense, since what else can you do for an auto renumber? After renumbering, in this case a /25, you could then edit the prefix and make it a /24 for example. KISS theory. :)

I'm very confused by the output there, as it should obviously not be .128 for each. We'll look into that more.

**Comment by arnoldnipper** [comment]
KISS:
  * old_mask >= new_mask
  * align the new addresses to the start address of the new range

**Comment by grizz** [comment]
> KISS:
> 
> * old_mask >= new_mask

I disagree that it's simpler, at worst it's just adding 1 extra step: renumber and then change the prefix. That one extra step for the AC member doing it makes the backend more complex and require more tests, etc.

> * align the new addresses to the start address of the new range

This is a clear bug that only happens with /25s. Yesterday, this tool had been used 6 times over the last two years, yet it's taken a lot of time discussing and creating. At some point all of our time is better spent just manually doing the handful of renumbers instead of trying to account for every corner case in a corner case tool. :)

I'm +1 and Minor for fixing the bug, any more time spent discussing how it should work is going to bump it to a Major in my opinion.

**Comment by arnoldnipper** [comment]
@grizz 

 * the tool **is** already checking masks. For whatever reason, it currently insists that old_mask == new_mask. Which is rubbish and confuses. So simply check that old_mask >= new_mask which makes sense

 * even when renumbering does not happen often, it greatly helps our users and AC and prevents from manual editing which is highly error-prone. Talking about corner cases of corner cases is thinking little of what AC does IMHO

**Comment by grizz** [comment]
Sold, +1
