### ISSUE TITLE
Separate "affiliation" e-mail address

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#67]
Currently when a user requests affiliation with an organisation A, all admins of A get an e-mail. A lot of users interpret the affiliation with a peering requests. This leads to the situation that esp. peering friendly networks are swamped with affiliation requests. A separate e-mail address would ease handling of affiliation requests

**Comment by arnoldnipper** [comment]
@vegu / @grizz pls add estimate

**Comment by vegu** [comment]
To be clear, this would be an email address that exists on the org object, that if set all affiliation request to the org get sent there instead of directly to the org admin users email addresses?

**Comment by arnoldnipper** [comment]
yes, if bound to the org that would be a list of e-mail addresses. Alternatively an admin may specify a separate e-mail address resp. indicate not to get notifcations.

**Comment by vegu** [comment]
> Alternatively an admin may specify a separate e-mail address resp. indicate not to get notifcations.

Would this be something they can set up per organization, or one global setting for all organizations they are an admin of?

So far as i understand - from the most recent description - this implementation would need:

- Manage org affiliation email addresses: backend and tests
- Manage org affiliation email addresses: UI component - this would be a new tab in org admin section
- Set user's affiliation email address: backend and tests
- Set user's affiliation email address: UI component - may make sense to make this part of the org admin tool instead of the user's profile, since only org admin users would be interested in this setting anyways.
- Allow user to opt out of affiliation notices: backend and tests
- Allow user to opt out of affiliation notices: UI component - see above

@arnoldnipper, can you clarify if the user's affiliation email address and opt out setting should be configurable per organization or global, and also let me know if i missed anything. 

Thanks

**Comment by grizz** [comment]
@arnoldnipper Could this just be solved by better wording in the request? I appreciate that users don't want to get swamped with erroneous emails, but this doesn't fix that, it just changes the address(es) they go to. I would think most networks would not want to set up a separate address just for PDB affiliations.

**Comment by eloos** [comment]
Would it make sense to allow the user to specify which email address domain extensions can request an affiliation as a comma-separated list? We can default to a wildcard meaning anyone.

**Comment by grizz** [comment]
> Would it make sense to allow the user to specify which email address domain extensions can request an affiliation as a comma-separated list? We can default to a wildcard meaning anyone.

Yes, that's a much better solution, we should also word affiliation requests better if this is a real problem. Do we have stats for how often this has happened?

**Comment by eloos** [comment]
@grizz don't we have email-server stats?

**Comment by grizz** [comment]
@eloos I don't think email stats would give the full picture? I was thinking of complaint tickets, although we could probably more accurately query our db for denied requests.

Either way, I don't think we have enough information to prioritize this.

**Comment by eloos** [comment]
@arnoldnipper you requested this feature, do you have any idea of how big of an issue this is?

**Comment by arnoldnipper** [comment]
From the top of my head I would say there were 2-3 complaints so far.

**Comment by eloos** [comment]
@arnoldnipper I think that is not the amount of issues we would be looking for to make this a priority at this time. I think it is now clear enough to go in the backlog. We would implement it as a limitation on the email-domain names that can request affiliation.

**Comment by vegu** [comment]
Moving back to decide, as it seems a decision on this still needs to be made.
