### ISSUE TITLE
Strings missing on translate.peeringdb.com

### ISSUE THREAD

**Issue by grizz** [peeringdb/peeringdb#752]
Additional strings from #714 -- https://github.com/peeringdb/peeringdb/issues/714#issuecomment-631993462

Users requesting affiliation
Users in Organization
Policy
Private Peering Facilities
Local Facilities
Filter
Present
Absent
Chinese (Simplified)
Chinese (Traditional)

Additional strings from #725 -- https://github.com/peeringdb/peeringdb/issues/725#issuecomment-634541086

kosovo
Sales E-mail
Facilities
Networks
Contact Information
Abuse (But appears in the drop down menu at the Contact Information edit page of a network)
Sales (But appears in the drop down menu at the Contact Information edit page of a network)
Technical (But appears in the drop down menu at the Contact Information edit page of a network)
Operational
Affiliation is your own organisation. That means you are an employee or otherwise working for the organisation. The affiliation request is sent to support@peeringdb.com if no one is affiliated to the organisation yet. Otherwise, the admins are contacted. Only affiliate once per organisation. If you don't get an answer within a couple of days, please contact support@peeringdb.com.
Open
Selective
Restrictive

**Comment by grizz** [comment]
@gordon-shumway-net Did I miss any strings here?

**Comment by gordon-shumway-net** [comment]
Hey @grizz ,

most of the Strings you mentioned should be already fixed or are already fixed. I also need some time to come into the topic again, it's a few weeks ago that we talked about that the last time. :)

* Strings who are a ~~crossed out~~ are **fixed** and appear translated.
* Strings who are **bold** need to be fixed and **don't work yet**.
* Strings who are written without any formatting should be fixed with the related pull request but aren't yet.

If there is any related information somewhere else, I tried to link it.


Strings from #714 who wasn't or aren't available for translation on translate.peeringdb.com

~~Users requesting affiliation~~ https://github.com/peeringdb/peeringdb/issues/714#issuecomment-632195611
Users in Organization #731 
**Policy** - _Appears in the Contact Information Table for as example a Network_ (But appears translated in the drop down menu at the Contact Information edit page of a network)
Private Peering Facilities #731 
Local Facilities #731 
~~Filter~~ #731 
Present #731 
Absent #731 
~~Chinese (Simplified)~~ https://github.com/peeringdb/peeringdb/issues/714#issuecomment-635014569
~~Chinese (Traditional)~~ https://github.com/peeringdb/peeringdb/issues/714#issuecomment-635014569

Strings from #725 that are translated but don't appear on beta.peeringdb.com

**kosovo** - _Appears in the Advanced Search in the "Country Filter" when you search for IXs or Facilities_
~~Sales E-mail~~
~~Facilities~~ #731 
~~Networks~~ #731 
~~Contact Information~~ #731 
**Abuse** - _Appears in the Contact Information Table for as example a Network_ (But appears translated in the drop down menu at the Contact Information edit page of a network)
**Sales** - _Appears in the Contact Information Table for as example a Network_ (But appears translated in the drop down menu at the Contact Information edit page of a network)
**Technical** - _Appears in the Contact Information Table for as example a Network_ (But appears translated in the drop down menu at the Contact Information edit page of a network)
~~Operational~~
~~Affiliation is your own organisation. That means you are an employee or otherwise working for the organisation. The affiliation request is sent to support@peeringdb.com if no one is affiliated to the organisation yet. Otherwise, the admins are contacted. Only affiliate once per organisation. If you don't get an answer within a couple of days, please contact support@peeringdb.com.~~ https://github.com/peeringdb/peeringdb/issues/725#issuecomment-633861793
**Open** - _Appears on an IX Site on the "Peers at this Exchange Point" Table_
**Selective** - _Appears on an IX Site on the "Peers at this Exchange Point" Table_
**Restrictive** - _Appears on an IX Site on the "Peers at this Exchange Point" Table_

---

There are some other strings I discovered right now which aren't translated on beta.peeringdb.com:
This is not even in Weblate:
**admin** - _Appears in the Organization Users Management and is defining the Group Membership_
This is on Weblate but not translated on beta.peeringdb.com:
**member** - _Appears in the Organization Users Management and is defining the Group Membership_
**Public Relations** - _Appears in the Contact Information Table for as example a Network_ (But appears translated in the drop down menu at the Contact Information edit page of a network)

---

Gordon :)

**Comment by grizz** [comment]
@gordon-shumway-net Thank you so much for the thorough and detailed feedback!

**Comment by gordon-shumway-net** [comment]
Hey together,
happy new year!
How is it going? :)

I was just checking the status and also if the most strings seems to be fixed now, the following are still not, can someone check that out?

Strings from #714 who wasn't or aren't available for translation on translate.peeringdb.com

**Policy** - _Appears in the Contact Information Table for as example a Network_ (But appears translated in the drop down menu at the Contact Information edit page of a network)

Strings from #725 that are translated but don't appear on beta.peeringdb.com

**kosovo** - _Appears in the Advanced Search in the "Country Filter" when you search for IXs or Facilities_
**Abuse** - _Appears in the Contact Information Table for as example a Network_ (But appears translated in the drop down menu at the Contact Information edit page of a network)
**Sales** - _Appears in the Contact Information Table for as example a Network_ (But appears translated in the drop down menu at the Contact Information edit page of a network)
**Technical** - _Appears in the Contact Information Table for as example a Network_ (But appears translated in the drop down menu at the Contact Information edit page of a network)
**Open** - _Appears on an IX Site on the "Peers at this Exchange Point" Table_
**Selective** - _Appears on an IX Site on the "Peers at this Exchange Point" Table_
**Restrictive** - _Appears on an IX Site on the "Peers at this Exchange Point" Table_

---

Gordon :)

**Comment by leovegoda** [comment]
The Product Committee has decided to close this issue. There was no agreement on the concept and the issue has not been discussed for six months or longer.
