### ISSUE TITLE
One NET Object for each IX Object - Max Prefix and AS-SET to filter Route-Servers

### ISSUE THREAD

**Issue by fischerdouglas** [peeringdb/peeringdb#755]
We are looking for a consistent way to get the following information to deploy, AND CYCLICAL UPDATE, automatically our BGP Session.
- Prefix v4
- Prefix v6
- AS-SET

PeeringDB API is a bless for that!
But not for MPLA Route Servers.

The objects of type "IX", on PeeringDB does not have those information.
And it’s reasonable that it doesn’t.
Those information are attribute of object of type "NET".

On a perfect world, where each IXP has their own ASN... This is simple to solve!
Create a NET for each route-server ASN... and all is good.

DE-CIX, AMS-IX, CABASE, solves it exactly like this...
For each IXP Location, they use an specific ASN, and with that they can create a "NET" object for each IXP Location.

With this parity between "IX" and "NET" objects, gets easier to automate the queries of Max Preffix and AS-SETs.

But there are some other organizations that uses the same ASN for all the IXP Locations(L2 isolated from each other).
This is the case of IX.BR(AS26162), and Equinix(AS24115)
And I Believe that IX Australia(AS7606) is also on the same situation.

If I'm not mistaken, ASN is an Unique Key attribute for NET Objects on PeeringDB...
So, is not possible to have several NET objects with the same ASN.

**Comment by fischerdouglas** [comment]
My suggestion to solve this:
A - Open an Exception(SPECIFIC TO IXPs) about ASN being a Unique Key, allowing that each IXP location has their own NET object.
B - Suggest/Demands that Each IXP has their own NET Object.
C - Create an attribute called NET_ID on IX objects, that will point to the NET referent to that IXP Location.

**Comment by fischerdouglas** [comment]
On other idea is to hang those information in other database like
https://ixpdb.euro-ix.net/en/ixpdb/route-servers/
But it does no sounds very good to me.

**Comment by fischerdouglas** [comment]
Examples IXPs from the same organization, from different locations, with different ASNs, and one NET Object to each IXP Location.

DE-CIX
-------
https://peeringdb.com/ix/31        IX -> DE-CIX Frankfurt 
https://peeringdb.com/net/947   NET -> DE-CIX Frankfurt Route Servers
Primary ASN6695
IRR as-set/route-set AS-DECIX
IPv4 Prefixes 300000
IPv6 Prefixes 50000

https://peeringdb.com/ix/1277      IX -> DE-CIX Madrid
https://peeringdb.com/net/10018  NET -> DE-CIX Madrid Route Servers
Primary ASN48793
IRR as-set/route-set AS-DECIX-MAD
IPv4 Prefixes 240000
IPv6 Prefixes 50000

https://peeringdb.com/ix/2531        IX -> DE-CIX Lisbon
https://peeringdb.com/net/19331   NET -> DE-CIX Lisbon Route Servers
Primary ASN43729
IRR as-set/route-set AS-DECIX-LIS
IPv4 Prefixes 200000
IPv6 Prefixes 50000

AMS-IX
--------
https://peeringdb.com/ix/26          IX -> AMS-IX
https://peeringdb.com/net/4277   NET ->AMS-IX Route Servers
Primary ASN6777
IRR as-set/route-set AS-AMS-IX-RS
IPv4 Prefixes 210000
IPv6 Prefixes 35000

https://peeringdb.com/ix/1623        IX -> AMS-IX India
https://peeringdb.com/net/14899   NET -> AMS-IX India NOC Operations
Primary ASN24193
IPv4 Prefixes 5000
IPv6 Prefixes 2000

IX -> AMS-IX Caribbean
https://www.peeringdb.com/ix/366
NET -> AMS-IX Caribbean Route Servers
https://www.peeringdb.com/net/14259
Primary ASN52462
IPv4 Prefixes 100
IPv6 Prefixes 100

**Comment by fischerdouglas** [comment]
Examples IXPs from the same organization, from different locations, using ASN, and only one NET Object to all the IXP Locations.

IX.BR
-----
https://peeringdb.com/ix/171       IX -> IX.br (PTT.br) São Paulo
https://peeringdb.com/ix/177       IX -> IX.br (PTT.br) Rio de Janeiro
https://peeringdb.com/ix/2822     IX -> IX.br (PTT.br) Cascavel
https://peeringdb.com/net/5802  NET -> NIC.br - IX.br (PTT.br) MLPA Route Servers
Primary ASN26162

IX Australia
------------
https://peeringdb.com/ix/716       IX -> IX Australia (Sydney NSW)
https://peeringdb.com/ix/21         IX -> IX Australia (Perth WA)
https://peeringdb.com/ix/576       IX -> IX Australia (Brisbane QLD)
https://peeringdb.com/net/7021  NET -> IX Australia
Primary ASN7606
IPv4 Prefixes 100000
IPv6 Prefixes 50000

**Comment by job** [comment]
The expectation is that IXPs register a new ASN per route server setup if the routing policy is significantly different from other places (because of a different set of peers for example). ASNs are either free or very cheap, using more ASNs is simpler than changing PeeringDB IMHO, there are plenty of ASNs available.

**Comment by arnoldnipper** [comment]
Fully agree with @job. Hence a -1 for the feature request

**Comment by netravnen** [comment]
On Fri, 26 Jun 2020 at 03:11, Douglas Fischer <notifications@github.com>
wrote:

> But there are some other organizations that uses the same ASN for all the
> IXP Locations(L2 isolated from each other).
>
> This is the case of IX.BR(AS26162), and Equinix(AS24115)
> And I Believe that IX Australia(AS7606) is also on the same situation.
>
Would you mayhaps know about specific teams and/or contacts at either of
the organizations you mentioned above? Which would be able to elaborate on
why  this design decision of using the same ASN for all Internet Exchanges,
even if they are L2 separated.

> If I'm not mistaken, ASN is an Unique Key attribute for NET Objects on
> PeeringDB...
> So, is not possible to have several NET objects with the same ASN.
>
Correct

**Comment by arnoldnipper** [comment]
> Would you mayhaps know about specific teams and/or contacts at either of the organizations you mentioned above?

Please spawn a discussion on Global IXP tech list <tech-discuss@lists.ix-f.net>

**Comment by remcovanmook** [comment]
> Would you mayhaps know about specific teams and/or contacts at either of the organizations you mentioned above? Which would be able to elaborate on why this design decision of using the same ASN for all Internet Exchanges, even if they are L2 separated.

Hi - partly responsible for the Equinix migration to 24115 back in 2012 or so. The decision was a pretty simple one: route servers back then very much needed a 16-bit ASN for compatibility and BGP community sake, and they should never show up in the global routing table. Therefore reusing the same ASN for all IXP route servers of a single organisation was, and is, a perfectly reasonable thing to do. The routing policy argument does not apply here IMHO because there's (hopefully) no independent routing policy done by the route server at all - it just serves as a vehicle for the member ASNs to express theirs. 

Forcing operators, either network or IXP, to adhere to a certain design so it better fits the peeringdb data model is the world upside down. Peeringdb is there to reflect what the operators intend, not the other way around.

**Comment by job** [comment]
@remcovanmook 

Route server ASNs *do* show up in the global system, because that is what you see when you type "show ip bgp neighbor x.y.z-routeserver-ip". It is what you lookup in PDB, or in the IRR, or in RPKI, or IPNOCDB. Route servers must not be treated as if they are passive hidden elements, they are not.

Each route server does have independent routing policies in its execution. Even if the principle is the same across all IXPs (aka build time is the same), the run time ends up not being the same (different IXPs operated by same org have different peers, and the peers may optionally provide additional influence through the use of BGP communities or other tools the IXP provides). 

The routing policy very much applies, instead of changing peeringdb one can use RPSL to publish what IXP route server peer can potentially expect which routes. If that becomes too complicated (when there is 0 overlap between "same ASN used, different IXPs used" it probably is time to get a separate ASN. I know we don't like RPSL, so its just an example.

Using the same ASN everywhere can be reasonable, but is not without consequences. If you use the same ASN everywhere, your RPSL document can become very lengthy, to the point where you cannot express the differences between various IXPs you operate in RPSL and have to spin up a new ASN.

Perhaps we are using different definitions of what a routing policy actually is?

**Comment by arnoldnipper** [comment]
> Forcing operators, either network or IXP, to adhere to a certain design so it better fits the peeringdb data model is the world upside down. Peeringdb is there to reflect what the operators intend, not the other way around.

So, what is your proposal? The field "IRR as-set/rs-set" is there since PDB's very beginning and obviously served its purpose very well. However, running an RS with the same ASN at different IXP then does not work.

> Perhaps we are using different definitions of what a routing policy actually is?

It would be good to come to a common understanding. I see a clear approach in what @job says, but do not yet see it for @remcovanmook

**Comment by fischerdouglas** [comment]
I Agree with @job and @arnoldnipper about the argument that each IXP Location should have their own ASN.

I even mentioned AMS-IX, DE-CIX, and cabase as good examples of this.
(Perhaps the only thing missing here is a specific attribute to create an unequivocal link between object IX and object NET.)



However, being pragmatic, we are talking about more than 70 IXP locations, and perhaps more than 4-5 thousand BGP sessions(or even more).
And we are talking about many IX who are among the largest in the world.
So I believe that changing that is something that **will not happen**.

My goal is to make it possible for this information to be published and consulted automatically (via API).

So brought the idea of the exception of multiple NET objects with the same ASN.

In my opinion, thinking about keeping this information within PeeringDB, this would be the most coherent and scalable option.
(very importantly keep this exception EXCLUSIVELY for IXPs)

**Comment by fischerdouglas** [comment]
Another alternative would be to rely on Route-Servers objects from the IXPDB (EURO-IX) database.

Create an unambiguous link within the NET object in PeeringDB pointing to the Route-Server Object from there.

And with that, whoever wants to automate, go and get that information there.

**Comment by remcovanmook** [comment]
@job - I think we are. Following your definition, any setup that is not identical in run time should be using a different ASN. Given that a common route server feature is to say 'you can send other members my prefixes, but not to ASN <x>' effectively creates as many different run time views as there are participants, which should then by extension have their own ASN. 

To me that seems a rather drastic direction if the problem that needs to be solved is one to identify which filter set to apply for which route server instance. Identifying which ASNs are in use as route servers, and then have the ix object link to a policy statement/as-set specific for that IX instance's route servers seems like a much more inclusive approach.

**Comment by arnoldnipper** [comment]
(Perhaps the only thing missing here is a specific attribute to create an unequivocal link between object IX and object NET.)

See https://github.com/peeringdb/peeringdb/issues/734

**Comment by as44980** [comment]
Should we consider the nuances that Layer2 IX fabrics are not the same thing as any Layer3 services such as route-collectors and/or route-servers which are offered to participants of a given L2 fabric, as touched upon in #672 ?

**Comment by as44980** [comment]
> Each route server does have independent routing policies in its execution. Even if the principle is the same across all IXPs (aka build time is the same), the run time ends up not being the same (different IXPs operated by same org have different peers, and the peers may optionally provide additional influence through the use of BGP communities or other tools the IXP provides).

Typically an IX route-servers "routing policy" is to redistribute all (valid) prefixes between all of its peers, unless instructed to do otherwise by the peer using BGP communities.

However if there are a pair of route-servers on a single IX, perhaps with the same ASN, then its possible for a peer to advertise different prefixes, or even the same prefixes with different action communities to each of those two route-servers.. 

So in this case do these two different route-servers have different "routing policies", and if so is it being suggested that each route-server instance must have its own ASN?

**Comment by arnoldnipper** [comment]
> However if there are a pair of route-servers on a single IX, perhaps with the same ASN, then its possible for a peer to advertise different prefixes, or even the same prefixes with different action communities to each of those two route-servers..

Then the peer should use different ASN ;-)

**Comment by job** [comment]
If you don't have a backbone (like a route server node doesn't have) AND use the same AS number everywhere, indeed your customers will lose visibility on what is happening in reality.

Douglas is right to point out there is friction because if the approach chosen by the likes of Asteroid. That friction doesn't need to exist, automated and manuak networks benefit a ton from AS level granularity. AS numbers are free in the RIPE region and extremely affordable elsewhere. If you can operate 70 IXPs you surely can afford it.

If you don't have a backbone, but pretend to be one, it causes some types of issues. Information is lost by recycling the same ASN everywhere. Astroid deploys *different configs* with different policies everywhere. Go check for yourself: different IPs, different sets of peers, and no IGP of any kind to bridge it all together into a single autonomous system. It's a group of autonomous systems from the internets perspective. 

Happy to have a phonecall to discuss what a routing policy is. We can go over virtual whiteboard and discuss what RIRs think routing policy is and how it maps into RPSL and our collective understanding of the internets architecture.

PS. You mentioned communities, please take a look at large communities.

**Comment by arnoldnipper** [comment]
> Happy to have a phonecall to discuss what a routing policy is

What about an online session where everyone who is interested can participate?

**Comment by fischerdouglas** [comment]
> Happy to have a phonecall to discuss what a routing policy is.

> What about an online session where everyone who is interested can participate?

Its OK, for me...
Just schedule it.

**Comment by as44980** [comment]
Might it be worth us considering RFC1930 here, and while there are plenty of other sections which im sure others will quote, I suspect that this part of [Section 6](https://tools.ietf.org/html/rfc1930#section-6) may be relevant here:

`Sites should not be forced to place themselves in a separate AS just so that someone else (externally) can make AS-based policy decisions.`

**Comment by job** [comment]
Right, so two route servers connected to the same layer-2 switching fabric should probably use the same ASN.

**Comment by as44980** [comment]
> Right, so two route servers connected to the same layer-2 switching fabric should probably use the same ASN.

On the basis that they could, potentially, announce the same prefixes*... ?

(* except in reality where its appears fairly common place for at least one member on an IX to only have one active session with the route-server)

**Comment by netravnen** [comment]
On Fri, 26 Jun 2020 at 17:10, as44980 <notifications@github.com> wrote:
> except in reality where its appears fairly common place for at least one member on an IX to only have one active session with the route-server

Can be mitigated if all Route Servers located at a particular Peering
LAN has internal full-mesh IBGP peerings established (this is how
DE-CIX does it)

**Comment by as44980** [comment]
> Can be mitigated if all Route Servers located at a particular Peering LAN has internal full-mesh IBGP peerings established (this is how DE-CIX does it)

This may present challenges with respect to [RFC7948](https://tools.ietf.org/html/rfc7948#section-4.1) which highlights that the only method to prevent path hiding which "does not require explicit support from the route server client is for the route server itself to maintain an individual Loc-RIB for each client that is the subject of conflicting outing policies."

Similarly it also states " Route server installations SHOULD be secured against BGP NEXT_HOP hijacking, as described in Section 4.8." and  thus "route server operators SHOULD check that the BGP NEXT_HOP attribute for BGP routes received from a route server client matches the interface address of the client"

Which I suspect would not be the case for prefixes which one route-server instance learns from another route-server instance on the same IXP...

And that's even before considering if "full-mesh iBGP peerings" between the route-servers is going to have a positive or negative impact on their ability to "provide a reliable reachability brokerage service", which appears be be the reason that it is RECOMMENDED that exchange operators who implement route server systems provision multiple route servers on each shared Layer 2 domain."  :)

**Comment by netravnen** [comment]
> > Can be mitigated if all Route Servers located at a particular Peering LAN has internal full-mesh IBGP peerings established (this is how DE-CIX does it)
>
> This may present challenges with respect to RFC7948 which highlights that the only method to prevent path hiding which "does not require explicit support from the route server client is for the route server itself to maintain an individual Loc-RIB for each client that is the subject of conflicting outing policies."
> Similarly it also states " Route server installations SHOULD be secured against BGP NEXT_HOP hijacking, as described in Section 4.8." and thus "route server operators SHOULD check that the BGP NEXT_HOP attribute for BGP routes received from a route server client matches the interface address of the client"
> Which I suspect would not be the case for prefixes which one route-server instance learns from another route-server instance on the same IXP...
> And that's even before considering if "full-mesh iBGP peerings" between the route-servers is going to have a positive or negative impact on their ability to "provide a reliable reachability brokerage service", which appears be be the reason that it is RECOMMENDED that exchange operators who implement route server systems provision multiple route servers on each shared Layer 2 domain." :)

In regards to proper technical set-up. I believe the best in every
"major" IXP doing the technical set-up of any Route-server per
recommended guidelines in general. (regarding de-cix specific set-up,
to my knowledge, it is done in accordance with general
recommendations. Apart from that, I have no specific knowledge. Due to
the set-up being the responsibility of a team I am not part of in the
company. Alas, I have no more to add regarding anything DE-CIX
specific, apart from what I have already expressed)

**Comment by arnoldnipper** [comment]
> (this is how DE-CIX does it)

This is how DE-CIX does it **not**

**Comment by netravnen** [comment]
> > (this is how DE-CIX does it)
> 
> This is how DE-CIX does it **not**

_Statement retracted_

**Comment by fischerdouglas** [comment]
What are the cons of this Idea?

Is "just" the proposal of the ASN as an unique key on NET objects?

**Comment by arnoldnipper** [comment]
> Is "just" the proposal of the ASN as an unique key on NET objects?

Yes, "network" just means "ASN" and the field `asn` is a key.

**Comment by fischerdouglas** [comment]
Well... I don't that there is any chance of the IXPs that uses same ASN for different locations change their ASNs...

And I can bet a box of <pt_BR>Sorvete Seco</pt_BR>, those with small balloons on the top, that it wont happen!

In my point of view, being able to query max-prefix and AS-SET on a trusty database, is a matter of routing security...

And doesn't matter witch database, PeerinDB or IXPDB...
But the information need to be there.

With that option available, big heart jedi-master guys could teach young dummies to query it automatically...
Or even create auto-provisioning peer session tools opensource, based on that information...

And with that, we can all sleep a little more peacefully...

**Comment by as44980** [comment]
> What are the cons of this Idea?
> 
> Is "just" the proposal of the ASN as an unique key on NET objects?

IMHO there is a fundamental issue with assuming that IXP's will, or should, operate a single Layer3 'network' on top of the Layer2 IX fabric...

This is infact a key element for (some) IX's to reinforce that the service which they provide is ifacilitating interconnection between members, without necessarily having any involvement in any layer3 routing which the members may do.. at least beyond assinging IP's from a shared 'Peering LAN' subnet :)

If the IX operator chooses to provide additional Layer3 services on top of this Layer2 Fabric, including but not limited to Route-Collectors and Route-Servers, that is great.. 

However AFAIK neither of these is required for an IXP to operate, or to to meet any vaugue definition of an 'IXP' PeeringDB is using (see #515), so I dont see how it could be reasonable to " Suggest/Demands that Each IXP has their own NET Object."

**Comment by as44980** [comment]
But going back to the original issue, if there was to be say a new field added for a (Layer2) IXP to be able to specifty the ASN used for common (Layer3) services such as Route-Servers.. (#734)

Would it be fair to say that by follow that link to the net object for that ASN, users can "automate the queries of Max Preffix and AS-SETs" based on the information contained in that record?

In which case is the real issue that, when an IXP has opted to use the same ASN for route-server instances on multiple non-connected Layer2 IXP fabrics, any Prefix values or AS-SET's would not be specific to that metro?

And if so, would the idea from #612 to "add an irr_as_set and irr_as_set6 to netixlan" which could "allow people to specify 'Per IX connection' specific AS-SETs?" provide a suitable mechanism for the user/automation to establish the correct AS-SET in the situation described above?

**Comment by as44980** [comment]
> However if there are a pair of route-servers on a single IX, perhaps with the same ASN, then its possible for a peer to advertise different prefixes, or even the same prefixes with different action communities to each of those two route-servers..

Just to expand on this.... while this may not reflect _all_ IXP route-servers, it would appear from [these graphs](https://portal.linx.net/stats/route-server) of LINX's [as8714](https://as8714.peeringdb.com/) that its statistically unlikely that there would ever be exatly the same set of prefixes announced even by a 'redundant pair' of route-servers connected to the same Layer2 IXP fabric..

**Comment by job** [comment]
Folks - the maximum prefix limits and AS-SETs are currently present in PeeringDB, assume that the reader interprets these as 'global defaults'.

The RPSL language can be used to describe where the routing policy deviates from the peeringdb published defaults. I understand it is not easy to use the RPSL language, and there are very few tools (if any) that can help parse the RPSL. This is what it is.

IXPs that require multiple ASNs to differentiate the services (route collection, route server, website + mail asn, etc etc)... can just request multiple ASNs to do so. Nothing in PeeringDB or their own process limits those organisations from getting as many ASNs as they need. PeeringDB as a tool cannot force people to get the amount of ASNs they need, but PeeringDB as a tool was designed with specific concepts in mind, such that people use globally unique ASNs when and where needed.

I understand the frustration, but peeringdb is the wrong place.

@fischerdouglas have you actually asked the IXP operator why they use the same ASN everywhere and shown that that in doing so there is a loss of granularity in systems such as PeeringDB (but also others)? Did you start a dialogue with them?

**Comment by job** [comment]
> With that option available, big heart jedi-master guys could teach young dummies to query it automatically...
> Or even create auto-provisioning peer session tools opensource, based on that information...
> 
> And with that, we can all sleep a little more peacefully...

Have you taken a look at this open source repository? I helped write a system that automatically and securely establishes BGP sessions for peering https://github.com/coloclue/kees you are free to copy it

**Comment by fischerdouglas** [comment]
Hello again...

P.S.1: I'm a noobie on the concepts of PeeringDB, and I'm not a dev guy.
So I spent some time reading the issues of PeeringDB here in GitHub to try to understand a bit more your modus operandi and way of thinking.
P.S.2: Please sorry if English, my grammar, and mostly my terminology are not "thaaaat" precise.

I tried to read all the issues that were pointed in this thread, and all the issues pointed there recursively.
Questions about:
- Where to put looking glass info?
- What is the recommended route-server?


I saw that there most of the issues becomes from the difference in how the modeling of an IX should be in a perfect world, and how it actually is.

Talking about PeeringDB Modeling, In terms of "IX", "NET", and "ORG" objects, the perfect world would be DE-CIX...
 - One "IX" PeeringDb Object to each Location
 - One ASN to Each location, what takes to One "NET" PeeringDb Object to each Location
 - Just one set of IPv4+IPv6 Lan Net on each location.
 - Just one ASN for the route-servers on each location.
 - No Private IP Address or ASN being used on the Lan or route-servers
(Some objects are missing some attributes(max prefix, as-set, etc, some links missing.., but just minor details.)

But not everyone could do the do things like that since the begging.
- There are several IX With more than one Network Lan Address(v4 and v6)
   - Most of then, legacy.
   - A big part of then, private IP Addresses.
- There are several IX that use private ASN on route-servers
This is pretty? NOOOOOO!!!
Anybody starting from scratch should do things like that? NOOO!

But those places exist! And (fortunately or not) they work!
And there is a lot of traffic running over then.

**Comment by fischerdouglas** [comment]
So, after leaning a bit more PeeringDB concepts, I understood that allowing multiple NET objects having the same ASN is a complicated thing! Even if it would be an exception only for IXPs.
 - Access to PeeringDB URLs based on ASN(hostname or HTML route) will need some "disambiguation" treatment.
 - I don't even know what would be necessary to get the information through API based on ASN-based-only query.
    - But the queries based on the IDs would keep working.

But I still see allowing multiple NET objects with the same ASN as the simpler solution to the issue that I presented, and indirectly to others like "what is the looking glass of this IXP?".

**Comment by fischerdouglas** [comment]
And, thinking a bit more...

Considering that on a single L2 IXP location can exist more than one IP Lan Subnets and more than one ASN for the Route-Servers...

The link from IXP Objects to NET Objects will need to be Multivalored.
Because a single IXP could point to more than one NET.

Another Option would create the "net_id" attribute on the LAN Subnet of the IXP.

**Comment by as44980** [comment]
> Talking about PeeringDB Modeling, In terms of "IX", "NET", and "ORG" objects, the perfect world would be DE-CIX...

If this approach represents BCP, and the majority of other IXP's are on board, then perhaps there should be an RFC...  :p

**Comment by arnoldnipper** [comment]
Lack of support
