### ISSUE TITLE
Remove support for IXP in_dfz

### ISSUE THREAD

**Issue by nickhilliard** [peeringdb/peeringdb#761]
There's been a bit of online discussion about the `in_dfz` field.  The tl;dr on this is that it's made fully redundant by RPKI, and that peeringdb data quality would be improved by removing the field.

So I'd like to propose removing the field from PeeringDB.

Its use case is stated in #352, namely that peeringdb should contain a record of whether an IXP prefix should be carried in the Internet DFZ.  Organisations would then be able to use this information as a source of authority for implementing bogon lists.

There's a bunch of reasons why this is a bad idea and why RPKI is the better option:

1. Any IXP that wants their peering LAN prefixes not to be carried in the DFZ can issue a ROA for the prefix with AS0 as the origin and this will signal that the prefix should be dropped immediately and globally.  A substantial number of carriers and most larger IXPs already support RPKI filtering, which means that any IXP which issues this sort of ROA can issue a $prefix/AS0 ROA and their prefix will automatically disappear across large chunks of the internet.

1.1. the original justification from the OP in #352 can be satisfied completely with RPKI.

2. The RPKI option already works today, across large chunks of the internet, and the RPKI deployment footprint is rapidly expanding because it's got native support out-of-the-box in almost all routing stacks.

3. RPKI provides a consistent implementation: the IXP can configure exact match or subnets as desired. There are no semantics associated with the `in_dfz` field which specify whether it's exact or subnets, either from the point of view of the data producer (i.e. the ixp) or the consumer (the organisation building the bogon list).

4. Implementing this on DFZ networks a) would mean starting out from zero and b) will require an awful lot of effort before it would become widely supported. In order to get this to work adequately, `in_dfz` would need to be implemented as an authoritative filtering source for DFZ operators.  There's only a handful of these in existence, e.g. RPKI (+ potentially SLURM), IRRDB and existing static / local prefix lists.  This means that all DFZ operators who wanted to implement this would need to write code to explicitly pull this info from peeringdb and somehow blend it into their prefix-list generation infrastructure.  This is a high barrier to adoption because all DFZ operators will need to do their own thing and there is no possibility of code re-use across operators.

4.1. we need fewer sources of authority for any specific data output set, rather than more.  Each new source of authority creates a long term burden of support, and this costs time and effort to maintain on the part of everyone.

5. `in_dfz` duplicates existing data.  This creates a burden of maintaining two sets of data which do almost exactly the same thing.

6. there are no semantics defined which determine how to handle the situation where rpki and in_dfz disagree with each other. Note that this includes disagreement about how to handle subnets.

7. RPKI is cryptographically secured and has legal / contractual standing.  `in_dfz` does not.

8. if anyone wants to treat IXP peering lan prefixes differently to other DFZ prefixes, it's already possible to pull a complete list of peering lan prefixes from peeringdb and request validation through their RPKI cache API. This will give information which is more accurate (i.e. single source of authority).

**Comment by lamehost** [comment]
I do agree with Nick. Even if it was developed with the best intentions in mind, `in_dfz` adds very little value to the product and creates confusion.

It also makes me think that PeeringDB would like to be an authoritative source of information for filtering which i believe is not something the database should do for various reasons.

Last, but not least, IETF and the rest of the internet community has already agreed that RPKI is the proper method for IXPs to stop the propagation of their LANs in the DFZ.

I recommend to retire `in_dfz` before it gets traction.

**Comment by job** [comment]
I too think this feature has unintended consequences in the long term, and it would be better to direct peeringdb resources to informing/explaining RPKI (in relation to interconnection) than to replicate some of the functionality without the cryptographic verification.

I think the feature was proposed in a different era (2018) when RPKI deployment arguably was not the norm, while now in 2020 things are different.

**Comment by grizz** [comment]
As one of the people who voted for it, I now agree it was a mistake to add it. Regardless of the RPKI state back then, it's a good lesson for the PC against pushing things forward that add API changes, since they're difficult to undo.

Removing the field will require a v3 release (#625) -- I think in the interim, we could change it to read only and set it from checking against RPKI, which could also have a help blurb that explains how we do it and promotes using RPKI.

Or just null it and move on with the same blurb, which would be less work. :)

@peeringdb/pc thoughts? As a separate action, we should also look at requiring a full vote for anything that changes the API.

**Comment by tking** [comment]
The big difference between PeeringDB+in_dfz and RPKI+AS0 is that the PeeringDB+in_dfz feature is Opt-Out and RPKI+AS0 is Opt-In. So, PeeringDB+in_dfz comes more or less for free to increase the routing security right away.

To support this statement with facts we performed some research on this:
1) There are 1557 Peering LAN Prefixes in PeeringDB. Today, 179 have valid AS0 ROAs in place. 1052 are not covered by ROAs. 326 show invalid ROAs (maxLength issues: 50, Origin AS issues: 276).
2) Only for 2 Peering LAN Prefixes the PeeringDB+in_dfz value is set to true. The remaining 1555 Peering LAN Prefixes show PeeringDB+in_dfz=false. 

This shows that the PeeringDB+in_dfz feature is perfect to increase the routing security today!

Please keep this feature and do not remove it!

**Comment by as44980** [comment]
> Removing the field will require a v3 release (#625) -- I think in the interim, we could change it to read only and set it from checking against RPKI, which could also have a help blurb that explains how we do it and promotes using RPKI.

I agree this should cease to be a user (ie IXP) submitted value, and think its a neat idea to re-purpose this to return a value derived from RPKI data..  

However I suspect we would not then want to get involved with attempting to consult any live routing data?

Assuming that is the case then the question for this idea would then be..

if a ROA with AS0 origin sets this value to "false", and a ROA with a non-zero AS sets this value to "true", then what should be returned for a peering lan prefix with no ROA?

**Comment by will-h** [comment]
I've just done a quick query of prefixes (as returned by https://www.peeringdb.com/api/ixpfx) and recorded the results. The peeringdb query returns 831 IPv4 prefixes and 727 IPv6.

I then checked those prefixes for DFZ reachability with RIPEStat (https://stat.ripe.net/data/prefix-overview/data.json?resource=XXX [1]) and took the `'announced'` result from there.

There are some limitations here as regards more specific / less specific routes announced, and I couldn't immediately check if originating AS was a sane value - if someone here has more experience doing RIPEStat queries they're welcome to give it a try!

Results were: 

False (i.e. **not announced**): **IPv4** 676 (81%), **IPv6** 608 (84%)
True (i.e. **announced**): **IPv4** 155 (19%), **IPv6** 119 (16%)

If my methodology is correct, it seems this "in_dfz" data is somewhat inaccurate, because we do see rather a lot of those IXP prefixes out there. It might be best to discontinue it purely on _accuracy_ grounds.

[Did in_dfz default to 'False' by any chance?]

[1] https://stat.ripe.net/docs/data_api#prefix-overview

**Comment by tking** [comment]
...

> There are some limitations here as regards more specific / less specific routes announced, and _I couldn't immediately check if originating AS was a sane value_ 

**Which renders this analysis useless including the reasoning based on it.**

**Comment by will-h** [comment]
> > There are some limitations here as regards more specific / less specific routes announced, and _I couldn't immediately check if originating AS was a sane value_
> **Which renders this analysis useless including the reasoning based on it.**

Pointing out any potential errors in my methodology was an attempt at good faith on my part. Are you able to provide any more specific (pun not intended🙂 ) analysis that the data peeringdb publishes is accurate?

If we cannot even attempt to prove the data approaches correctness, we must fall back to the routing intent published via standards-based RPKI rather than publish poor quality data. That is our responsibility to the community.

I still stand by my comments in the past that it is a mistake to include routing policy data in the Peeringdb, when we have as a community invested millions in the multistakeholder RIR system, RPKI and the rest.

> > Did in_dfz default to 'False' by any chance?

Anyone know?

**Comment by funkestefan** [comment]
> So, PeeringDB+in_dfz comes more or less for free to increase the routing security right away.

I am not aware of any protocol or router implementation that queries PeeringDB to validate prefixes. On the contrary: PeeringDB is not a trusted source for prefix data and there is no validation instance. All those things exist for RPKI.

> This shows that the PeeringDB+in_dfz feature is perfect to increase the routing security today!

This shows, thtat most peering lan prefix operators do not care about RPKI or are doing a bad job regarding peering security. Since only IXPs can manage any kind of prefixes in PeeringDB, this feature is targeting IXP operators only. I don't know any reason why an ixp lan should appear in the DFZ anyway. If anyone wanted to compile a list of ixp lans for filtering purposes, this person would not need an extra flag for that. The data already existed since pdb added ixplan support.

**Comment by klindqvist** [comment]
> The big difference between PeeringDB+in_dfz and RPKI+AS0 is that the PeeringDB+in_dfz feature is Opt-Out and RPKI+AS0 is Opt-In. So, PeeringDB+in_dfz comes more or less for free to increase the routing security right away.
> 
> To support this statement with facts we performed some research on this:
> 
> 1. There are 1557 Peering LAN Prefixes in PeeringDB. Today, 179 have valid AS0 ROAs in place. 1052 are not covered by ROAs. 326 show invalid ROAs (maxLength issues: 50, Origin AS issues: 276).
> 2. Only for 2 Peering LAN Prefixes the PeeringDB+in_dfz value is set to true. The remaining 1555 Peering LAN Prefixes show PeeringDB+in_dfz=false.
> 
> This shows that the PeeringDB+in_dfz feature is perfect to increase the routing security today!

Not really, RPKI is getting deployed - how many networks have built and tested prefix building based on in_dfz? I would guess "not many".

**Comment by barryo** [comment]
> The big difference between PeeringDB+in_dfz and RPKI+AS0 is that the PeeringDB+in_dfz feature is Opt-Out and 
> RPKI+AS0 is Opt-In. 

Isn't this one of the biggest problems? Rather than a real state of `yes/no/unknown` it appears to be implemented as `yes/no` and defaulting to `yes`. So the only data you can rely on regarding this from PeeringDB is those that have opted out as any `yes` value really means `maybe`. I.e. the feature seems fundamentally broken as designed.

Of course, and as @will-h rightly says, it is a mistake to include routing policy data in the PeeringDB. For any network where I have administrative input, I'll declare my routing intentions with RPKI. I wasn't particularly aware that this option existed in PeeringDB (and I'm uncomfortable with it being there now that I know about its existence). 

For the record: I support the removal of in_dfz from PeeringDB.

**Comment by ik5pvx** [comment]
I fully support Nick's proposal and reasoning to remove this feature. 
We definitely not need yet another source of stale informations to build filters from.

**Comment by tim-preston** [comment]
Nick, as usual, making a lot of sense.
Gets my support too.

**Comment by moshivji** [comment]
Nick gets my vote .

**Comment by arnoldnipper** [comment]
> [Did in_dfz default to 'False' by any chance?]

It does ... for obvious reasons ;-)

**Comment by tking** [comment]
I think the vote is obvious!

Just kill the feature!

Thanks for the insightful and fruitful discussion!!! I like this kind of exchange of arguments!

**Comment by ynbrthr** [comment]
> As one of the people who voted for it, I now agree it was a mistake to add it. Regardless of the RPKI state back then, it's a good lesson for the PC against rushing things forward that require API changes, since they're difficult to undo.
> 
> Removing the field will require a v3 release (#625) -- I think in the interim, we could change it to read only and set it from checking against RPKI, which could also have a help blurb that explains how we do it and promotes using RPKI.
> 
> Or just null it and move on with the same blurb, which would be less work. :)
> 
> @peeringdb/pc thoughts? As a separate action, we should also look at requiring a full vote for anything that changes the API.

+1, and I'm in favor of nulling the field

**Comment by arnoldnipper** [comment]
> Removing the field will require a v3 release (#625)

Remove it with v3 and leave it there until then as it does no harm

**Comment by job** [comment]
> > Removing the field will require a v3 release (#625)
> 
> Remove it with v3 and leave it there until then as it does no harm

I don't think we should wait until v3, which might be a long period.

we should be able to roll this back / hide from the users to stop spreading confusion.

**Comment by shane-kerr** [comment]
So @grizz's  proposal of nulling the field means what exactly? Possibly:

1. Setting any current in_dfz values to false?
1. Removing from the web UI?
1. Returning an error to any API calls that have a true value for in_dfz? Or ignoring true values for in_dfz and always using false (which seems dangerous to me)?
1. Removing the field on any 3.x branch?

**Comment by nickhilliard** [comment]
the options so far seem to be:

1. set to specific value: {true,false}
1. don't touch existing values
1. use feed from rpki validator to determine value

option 2 seems like the worst of all worlds.  Some of the data in there is incorrect and there's no option available for IXPs not to express an opinion.  I.e. the only options are `true` and `false`; there's no `null`.  

option 3 is falling into the sunk cost fallacy.  If there's a decision to deprecate this feature, then it should be deprecated rather than enhanced because otherwise mixed signals are going to be sent out.

option 1 is not ideal, but as long as it's documented adequately, it's probably the least harmful of the three.  It would need to be accompanied by documentation warnings to say that the field must not be used, as it is hard-coded to a specific value.  POST / PUT with `in_dfz` should be rejected as an error.

**Comment by barryo** [comment]
I know changing APIs without a major version bump is a no-no. But, before we wrap outselves up in convoluted plans, it looks like this was only implemented 27 days ago?

Maybe we could all hold our collective noses and just "revert" it rather than "remove" it? 🤷‍♂️ 

I mean, is anyone actually using it?

**Comment by arnoldnipper** [comment]
> I mean, is anyone actually using it?

Yes. 
```
curl -sG https://peeringdb.com/api/ixpfx --data-urlencode in_dfz=1 --data-urlencode fields=id | jq '.data | length'
3
```

**Comment by barryo** [comment]
@arnoldnipper - by *"is anyone actually using it?"* I meant using it by consuming the API. 

That three people stumbled upon it in the UI and twiddled the knob isn't particularly relevant here.

**Comment by grizz** [comment]
@shane-kerr Yes, exactly. In this case, I would set it to `true` since it would remove it from any filters that were being generated from the data.

> I don't think we should wait until v3, which might be a long period.

We absolutely need to wait until v3 to remove a field, it could break any code expecting that field. See also semver.

> option 3 is falling into the sunk cost fallacy. If there's a decision to deprecate this feature, then it should be deprecated rather than enhanced because otherwise mixed signals are going to be sent out.

It's not the sunk cost fallacy, it's throwing good time after bad. :)

+1 for nulling it.

**Comment by shane-kerr** [comment]
Okay, +1 from me for:

1. Setting any current `in_dfz` values to `true`, which effectively makes this field a no-op.
1. Removing from the web UI (if it's there).
1. Returning an error to any API calls that have a `false` value for `in_dfz` (something like "no longer supported").
1. Removing the field on any 3.x branch.

I think that I've asked this before but I forget the answer... do we have a place documenting plans for 3.x? (I didn't see a branch, and a quick search didn't find anything.)

**Comment by arnoldnipper** [comment]
> That three people stumbled upon it in the UI and twiddled the knob isn't particularly relevant here.

That sounds quit arrogant to me.

**Comment by barryo** [comment]
> > That three people stumbled upon it in the UI and twiddled the knob isn't particularly relevant here.
> 
> That sounds quite arrogant to me.

Wasn't my intention. The issue with reverting/removing and semver is that if people are consuming the API to use this field then it cannot just be rolled back. My point [here](https://github.com/peeringdb/peeringdb/issues/761#issuecomment-662069338) is that it's reasonbly new and **if** no one's consuming it, there *may* be an easy option.

**Comment by arnoldnipper** [comment]
From my pov this feature does not do any harm. Not promoting it and then removing it with v3 is the option I prefer.

**Comment by job** [comment]
> Okay, +1 from me for:
> 
>     1. Setting any current `in_dfz` values to `true`, which effectively makes this field a no-op.
> 
>     2. Removing from the web UI (if it's there).
> 
>     3. Returning an error to any API calls that have a `false` value for `in_dfz` (something like "no longer supported").
> 
>     4. Removing the field on any 3.x branch.
> 
> 
> I think that I've asked this before but I forget the answer... do we have a place documenting plans for 3.x? (I didn't see a branch, and a quick search didn't find anything.)

this sounds good to me

+1

**Comment by arnoldnipper** [comment]
> do we have a place documenting plans for 3.x?

[API v3] https://github.com/peeringdb/peeringdb/issues/625)

**Comment by arnoldnipper** [comment]
I don't see that we had consensus on this already

**Comment by grizz** [comment]
If you look back at the comments, this received consensus and finalized, but the milestones weren't updated correctly. I didn't notice that when we cherry picked it for this deploy.

It's currently in production (v2.22), please re-open if you think I did something incorrectly.
