### ISSUE TITLE
Fantasy organisation names

### ISSUE THREAD

**Issue by patrick7** [peeringdb/peeringdb#821]
Most recently I noticed that a lot of hobby ASNs are using fake / fantasy names as their organisation name. 
While I see no problem with hobby ASNs, imho the only name which should be allowed is the one registered in the RIRs database (ORG object) or commercial register, to keep it clean and professional.

**Comment by arnoldnipper** [comment]
Thanks for letting us know, @patrick7. Net names and organisation names **are** taken from what is in RIR. But even there it is often not so easy to pick the right one as not every ASN has an org-name associated. 

Once registered, the admins are free to change the name of the organisation and the name of the net. Does that really do harm?

**Comment by patrick7** [comment]
It does not "harm", but it's just wrong data in the database. The organisation should be the entity which is operating the ASN. A fantasy name is not really an entity. 

I know that the owner may give its project a name, that's totally fine for me - but in my opinion, PeeringDB should be a professional place (not a playground) with real, correct data.

**Comment by arnoldnipper** [comment]
There is a German saying "Namen sind Schall und Rauch".  And what is right is determined by the user. There are only minimal requirements for putting in an ASN. And as long as these requirements are met and our AUP is not violated it's fine with us. 

I'm closing this issue again as I do not see a task for us to do.

**Comment by as44980** [comment]
Out of interest, does PeeringDB have a policy with respect to user submitted data which may be perceived as offensive, threatening or hate speech?

**Comment by arnoldnipper** [comment]
> Out of interest, does PeeringDB have a policy with respect to user submitted data which may be perceived as offensive, threatening or hate speech?

Doesn't the [AUP](https://peeringdb.com/aup) cover this?

**Comment by as44980** [comment]
> > Out of interest, does PeeringDB have a policy with respect to user submitted data which may be perceived as offensive, threatening or hate speech?
> 
> Doesn't the [AUP](https://peeringdb.com/aup) cover this?

IANAL but to me that would appear to focus primarily on what can be done with the data which is made available by PeeringDB rather than what policies are applied to data which is submitted..

ie is any vetting performed on user-submitted data either before it goes into the database, or prior to it being included in any results returned by user queries, with respect to potentially offensive language, hate speech or glorifying historical atrocities?

> There is a German saying "Namen sind Schall und Rauch". And what is right is determined by the user.

Are citizens in Germany allowed to freely determine how they should be referred to, or are there perhaps some restrictions imposed by law to exclude some specific names or terms from this "right"?
