### ISSUE TITLE
IX-F importer: if ixf_ixp_member_list_url is null then ixf_ixp_import_enabled can't be true

### ISSUE THREAD

**Issue by ccaputo** [peeringdb/peeringdb#846]
Per https://github.com/peeringdb/peeringdb/issues/795#issuecomment-701881320 we have some /ix/ records where ixf_ixp_member_list_url is empty while ixf_ixp_import_enabled is true.  This will cause an ix to get a notification of:

```
IXF import url not specified
```

@arnoldnipper , what would you like to happen here?  I'm thinking:

  - ixf_ixp_import_enabled should only be able to be set to true when ixf_ixp_member_list_url is non-null
  - ixf_ixp_import_enabled should get reset to false when ixf_ixp_member_list_url is cleared

**Comment by arnoldnipper** [comment]
The proposed behaviour makes sense

**Comment by arnoldnipper** [comment]
@pc, please dedicate a few seconds.

Currently, an ix is able to set "please import my IX-F JSON", although there is no URL to the JSON. This causes the importer to spit out an error. This issue proposes that you only can set the import flag to true if the URL != ""

**Comment by shane-kerr** [comment]
+1

I'm also happy if we simply disable the error though, which seems more gentle from a user point of view.

**Comment by arnoldnipper** [comment]
> I'm also happy if we simply disable the error though, which seems more gentle from a user point of view.

Depends on ... if a user sets the switch to "please import" and didn't specify a URL then they either didn't understand what they do or got distracted. Hence, informing them is imho a good idea. So, what @ccaputo proposes seems more gentle from a user pov. No?

**Comment by shane-kerr** [comment]
> > I'm also happy if we simply disable the error though, which seems more gentle from a user point of view.
> 
> Depends on ... if a user sets the switch to "please import" and didn't specify a URL then they either didn't understand what they do or got distracted. Hence, informing them is imho a good idea. So, what @ccaputo proposes seems more gentle from a user pov. No?

If we want to alert user to their possible confusion then the current situation is actually the best, because they have to figure out what they want.

If we want the system to work in the most natural way possible, we can either:

1. Disable the error and just ignore `ixf_ixp_import_enabled` set to `true` if `ixf_ixp_member_list_url` is empty
2. Set the `ixf_ixp_import_enabled` to `false` if `ixf_ixp_member_list_url` is empty

I argue that option #2 (which is the current proposal) is more surprising to users, since we are changing the values that they sent.

**Comment by arnoldnipper** [comment]
Option 2 is not the current proposal.  The proposal is

 * if `ixf_ixp_member_list_url ` = "" then user is not able to  set `ixf_ixp_import_enabled` = true

Instead, an error message is shown. We are not changing any values but prohibit a value to be set.

**Comment by shane-kerr** [comment]
> Option 2 is not the current proposal. The proposal is
> 
>     * if `ixf_ixp_member_list_url ` = "" then user is not able to  set `ixf_ixp_import_enabled` = true
> 
> 
> Instead, an error message is shown. We are not changing any values but prohibit a value to be set.

The original proposal is:

*   ixf_ixp_import_enabled should only be able to be set to true when ixf_ixp_member_list_url is non-null
*   ixf_ixp_import_enabled should get reset to false when ixf_ixp_member_list_url is cleared

The last bullet there is option 2. My understanding was that this is the proposal being discussed - both bullets.

The first bullet seems non-controversial to me and I definitely support that. The second bullet is the reason that I suggested disabling the error instead of implicitly modifying data.

**Comment by arnoldnipper** [comment]
So, how does `ixf_ixp_import_enabled` look if the user clears `ixf_ixp_member_list_url`, @shane-kerr?

**Comment by ccaputo** [comment]
> So, how does `ixf_ixp_import_enabled` look if the user clears `ixf_ixp_member_list_url`, @shane-kerr?

I think @shane-kerr is saying that it would be left as-is.

I can see the point of view that we shouldn't modify `ixf_ixp_import_enabled` for the network.  With that in mind, can we at least move forward with the below summary?

(In the case where a network removes the URL, but leaves `ixf_ixp_import_enabled` checked, they will get an error notice emailed to them on the next Importer run - normally at 0000 UTC.  That email will contain the language "IXF import url not specified" which hopefully they'll act on.  Per https://github.com/peeringdb/peeringdb/issues/880#issuecomment-727583443 a reminder about this will be sent to them every N days (currently 15) until fixed.)

**Summary**

- ixf_ixp_import_enabled should only be able to be set to true when ixf_ixp_member_list_url is non-null

**Comment by arnoldnipper** [comment]
@pc, another +1 needed. @ynbrthr? What do you think?

**Comment by ynbrthr** [comment]
+1 on "ixf_ixp_import_enabled should only be able to be set to true when ixf_ixp_member_list_url is non-null"

If ixf_ixp_member_list_url is cleared while ixf_ixp_import_enabled is true, i'd rather throw up an error rather than changing ixf_ixp_import_enabled to false, or generate an error notice via email after the fact.

**Comment by arnoldnipper** [comment]
**Summary**

`ixf_ixp_import_enabled` should only be able to be set to true when `ixf_ixp_member_list_url` is non-null

**Comment by shane-kerr** [comment]
I'm quite happy with an error!

I'm not super happy with silently "fixing" user data (I put "fixing" in scare quotes because if a user is trying to configure inconsistent data like this then they are confused and we don't really know what their intention is, because the user does not know what their intention it).

**Comment by ccaputo** [comment]
Fix confirmed on beta.

**Comment by arnoldnipper** [comment]
**Release Notes**
Apply logic to the meaning of `ixf_ixp_member_list_url`. I.e. only allow `ixf_ixp_import_enabled`to be set to `true` if a URL is specified.
