### ISSUE TITLE
 IX-F Importer: Repeated emails are being generated for things already emailed

### ISSUE THREAD

**Issue by ccaputo** [peeringdb/peeringdb#850]
At ix/1285 AS6456, I have intentionally created a conflict with respect to operational status.

Under production, repeated runs of `pdb-container pdb_ixf_ixp_member_import --commit --ixlan 1285 --asn 6456` result in repeated emails to both the IX and the network.  The IXF Import Emails table confirms this.

This must not happen and is an absolute showstopper preventing further testing.  We can't have the Importer send emails of things it has already notified about, each time it is run.

Also, the output of the importer has an inaccurate "New Emails:" count each time it is run.  In this case two emails were sent, one to the network and one to the IX, confirmed on both the receiving end and the IXF Import Emails table, yet the count below is zero:

```
$ time flock -x -w 240 /tmp/pdb_ixf_ixp_import.lock /home/pdb/bin/pdb-container pdb_ixf_ixp_member_import --commit --ixlan 1285 --asn 6456
Fetching data for -ixlan1285 from https://www.seattleix.net/autogen/participants.json
Processing SIX Seattle (Jumbo) (1285)
Success: True, added: 0, updated: 0, deleted: 0
New Emails: 0
Attemping to resend 0 emails.
RE-SENT EMAILS: 0.

real    0m4.718s
user    0m0.051s
sys     0m0.019s
```

The result of 3 runs:

![Screen Shot 2020-10-07 at 2 48 33 PM](https://user-images.githubusercontent.com/1417833/95391612-34503180-08ac-11eb-86e8-b5b2153ed769.png)

**Comment by ccaputo** [comment]
I just noticed a DeskPro ticket was created each time.  Maybe this helps understand a failure which may be happening?  List of tickets and details on the first one:

<img width="1186" alt="Screen Shot 2020-10-07 at 2 58 20 PM" src="https://user-images.githubusercontent.com/1417833/95392493-b2610800-08ad-11eb-9b23-6b710a76a4e9.png">
<img width="1235" alt="Screen Shot 2020-10-07 at 2 58 40 PM" src="https://user-images.githubusercontent.com/1417833/95392503-b5f48f00-08ad-11eb-9215-9a9d887a861f.png">

**Comment by vegu** [comment]
So far we have been unable to reproduce this. 

It's also not obvious to us why it's making a deskpro ticket right away - but i think it might be connected to whatever is going on.

I think next step would be to try to reproduce on beta under the same conditions (minus the actual sending of emails)

**Comment by vegu** [comment]
Looks like the deskpro ticket and conflict resolution emails are created because the actual IX-F Member Data entry is at this point over a month old (Aug 26, 2020 as created date)

This looks like a bug in itself, it should probably check against when it was last updated to determine if individual conflict resolution is initiated?

I believe this also ties into the second bug of it doing repeated notifications for it on each run.

**Comment by vegu** [comment]
The failure to post to the DeskPRO api means we are unable to grab a deskpro ticket reference, which we use the determine whether participants have been notified on individual conflicts.

So there is 2 (potentially 3) different things to address here

- why is the deskpro api post failing
- if the deskpro api post is failing and cant provide a ticket reference don't send out individual conflict resolution emails
- determine whether or not a conflict qualifies for direct conflict resolution by updated date instead of created date

**Comment by vegu** [comment]
The deskpro post issue was caused by the `ixf_importer` user on the production environment missing values for first name and last name resulting in deskpro being unable to create a person for it.

This has been fixed and conflict notifications are now being published correctly.

**Comment by vegu** [comment]
We still have to address the remaining issue of repeated emails in the case of a deskpro api failure, so for the remaining scope of this ticket:

**Summary**

- if the deskpro api post is failing and cant provide a ticket reference don't send out individual conflict resolution emails
- determine whether or not a conflict qualifies for direct conflict resolution by `updated` date instead of `created` date

**Comment by ccaputo** [comment]
I am removing the "Showstopper" in the title, since that aspect has been fixed.

**Comment by mcmanuss8** [comment]
+1

**Comment by arnoldnipper** [comment]
I have routed this through to 3a as @vegu has flagged this a bug
