### ISSUE TITLE
add explicit order for fields in admin control panel

### ISSUE THREAD

**Issue by grizz** [peeringdb/peeringdb#861]
Starting with facility/X/change

**Comment by peterhelmenstine** [comment]
could you clarify what this is?

**Comment by arnoldnipper** [comment]
@peterhelmenstine, the order of fields in any of the https://peeringdb.com/cp/ is not explicit. This issue is to identify fields we have to have at a specific position.

Example: on any of an https://peeringdb.com/cp/peeringdb_server/facility/nnnn/change/ the `Website` field was moved down below the `Org` field. When you know want to work on a facility request you have to scroll down miles before seeing the `Website` field to get to the website., And then scroll up again to either approve or deny the request. 

Does that clarify?

**Comment by peterhelmenstine** [comment]
Ah yes. I noticed that one where the website 'appeared' to be gone but had to scroll to find it. Fully understand and agree to having that sorted. Thank you for the clarification.

+1

**Comment by arnoldnipper** [comment]
https://peeringdb.com//cp/peeringdb_server/facility/nnnn/change: pin `Website` under `Name` resp. line 11
