### ISSUE TITLE
IXF-Importer: minimise emails to Support/DeskPRO/AC

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#883]
Currently, if a technical email is missing for one network separate emails are sent to AC for [CREATE](https://peeringdb.deskpro.com/agent/#app.tickets,inbox:archive_resolved,t.o:50737,vis:6)/[REMOVE](https://peeringdb.deskpro.com/agent/#app.tickets,inbox:archive_resolved,t:50737,t.o:50736,vis:6) actions.

The Importer should send just **one** email combining all the suggestions.

**Comment by peterhelmenstine** [comment]
+1

**Comment by shane-kerr** [comment]
+1

**Comment by arnoldnipper** [comment]
**Summary**

In case a technical email is missing for a network, compile just **one** email combining all the suggestions..

**Comment by egfrank** [comment]
Hi all! One implementation detail, what do we want the ticket **subject** to be for this

**Comment by arnoldnipper** [comment]
> Hi all! One implementation detail, what do we want the ticket **subject** to be for this

s/Action May Be Needed/Several  Actions May Be Needed/ ... does that make sense?

**Comment by egfrank** [comment]
Hello!

In starting this issue, we had another question about implementation.

Currently, if the network has no technical email specified, we will immediately notify AC about the suggestion instead of consolidating emails first. So if a single network missing a technical email has, say, 3 suggestions, we'll send 3 emails, like this issue notes.

However, the exchanges that are also mentioned in those suggestions will be cc'd in those emails, if they have a valid point of contact.

So in the example where we send 3 emails to AC, each of those 3 emails could potentially be cc'ing a different exchange.

How do we want to handle that when it comes to this issue? Do we simply want to stop cc'ing exchanges if multiple appear in a consolidated email?

Additionally, we would have this same issue if the exchange was missing contact info but multiple effected networks have contact points. Do we want to include that in this issue as well?


@peeringdb/ac

**Comment by arnoldnipper** [comment]
> Do we simply want to stop cc'ing exchanges if multiple appear in a consolidated email?

I would do so. 

> Additionally, we would have this same issue if the exchange was missing contact info 

No. There is no exchange with missing contact info. And new exchanges will always have to provide a contact info to get registered.

**Comment by egfrank** [comment]
> Whom do we Cc in this case?

We don't cc anyone on the consolidated emails sent out to the networks and exchanges

In light of that, we **propose**:

1. If a network contact does not exist, consolidate the conflicts into one ticket for the AC (per network)
2. In lieu of cc'ing the exchange, add the conflicts to the consolidated email going out to the exchange

**Comment by arnoldnipper** [comment]
Please go ahead, @egfrank
