### ISSUE TITLE
IX-F Importer: history of changes per ixlan & netixlan

### ISSUE THREAD

**Issue by ccaputo** [peeringdb/peeringdb#893]
https://www.peeringdb.com/cp/peeringdb_server/ixlan/###/history/ (email me if you need specific) shows the following made by a user:

```
ixf_ixp_import_enabled: True →  False
ixf_ixp_import_error: None →  IXF import url not specified
ixf_ixp_import_error_notified: None →  2020-11-20 01:21:19.244000+00:00
```

The first change was actually made by the user.

The other two changes were made by the Importer.

It is a bug to report Importer changes as being made by a user.  We need to make it so Importer changes are logged in this kind of version history, under the Importer's "ixf_importer" user_id, at the time the Importer makes the changes, rather than being glommed into a user's next update, which may or may not happen anytime soon.

For netixlan, as a result of the Importer's actions due to "Allow IXP Update" being enabled by a network, it appears the user "None" is being set, rather than the "ixf_importer" user.  That is a bug and should be corrected.

If there are any other records with History, where the Importer makes an update, we should also have those changes logged in the /cp/ history as being performed by user "ixf_importer".

**Comment by vegu** [comment]
There are two separate bugs here

1) Looks like the `ixf_ixp_import_error` and `ixf_ixp_import_error_notified`  changes the importer makes dont trigger a revision snapshot, which is why it gets pulled into the next revision to the object (made by the user in this case)
2) Changes pushed by the importer during import through automatic updates of netixlan don't have the ix-f importer user set for the revision snapshot, which is why the user is set to `None`

**Comment by arnoldnipper** [comment]
Routed through to 3a as a developer classifies this as a bug

**Comment by ccaputo** [comment]
Fix and history confirmed for both ixlan and netixlan.  Tis glorious!
