### ISSUE TITLE
Make blog/blogs.peeringdb.com redirect to blog

### ISSUE THREAD

**Issue by mcmanuss8** [peeringdb/peeringdb#904]
Make blog.peeringdb.com and blogs.peeringdb.com redirect to https://docs.peeringdb.com/blogs/

**Comment by arnoldnipper** [comment]
+1

**Comment by ynbrthr** [comment]
+1

**Comment by grizz** [comment]
This can be done by @peeringdb/oc

**Comment by ccaputo** [comment]
- Added A & AAAA DNS entries for blog.peeringdb.com and blogs.peeringdb.com.  (Not really necessary since we have wildcards, but good to note special treatment.) (Also added missing AAAA gov.peeringdb.com entry.)
- Tested nginx regexp redirect on beta.
- Tested nginx regexp redirect on prod.
- Ansibled.

The following now redirect to the blogs page https://docs.peeringdb.com/blogs/ after any browser cache redirects have been cleared:

http://blog.peeringdb.com/
http://blogs.peeringdb.com/
https://blog.peeringdb.com/
https://blogs.peeringdb.com/
