### ISSUE TITLE
netixlan ipaddress sanitation fixes

### ISSUE THREAD

**Issue by vegu** [peeringdb/peeringdb#92]

**Comment by arnoldnipper** [comment]
Now that every ix has an ixlan and ixpfx it is possible to run a sanitation script once to remove mismatching entries, i.e. entries which do not fall within the IP range. We should do this in 2-3 months as there are still left-overs from the ixlan migration.

@peeringdb/pc, what do you think?

**Comment by arnoldnipper** [comment]
+1

**Comment by shane-kerr** [comment]
So from a product point of view the proposal is to create a cleanup script, and have it added to whatever scheduler we use?

**Comment by arnoldnipper** [comment]
@shane-kerr we only need to run the sanitation script once. Since release 2.14.0 ( #8 ) we already check network's IXP IP address against IXP's IP range.

We might want to take care of address migration at an `ix` however. I.e. what to do with left-overs when an `ix` removes the old IP range? IMHO it would be helpful to run the migration tool we already have then. @ccaputo, another item for the TODO list IMHO

**Comment by shane-kerr** [comment]
+1 (for creating the cleanup script)

I think we should run it ASAP, and let users know that we are going to delete data for them, and then actually do it in the 2-3 month time mentioned.

**Comment by mcmanuss8** [comment]
Agreed, we shouldn't just delete it without warning. Let's give them ample time to correct the data (and include instructions for how to do this, as well as how to ask AC for help if they aren't sure). 
+1 to write a script with two modes:
a)  warn mode that sends each network a list of IP mismatches they own that need cleaning up 
b) a cleanup mode that deletes bad entries found above

**Comment by ccaputo** [comment]
> We might want to take care of address migration at an `ix` however. I.e. what to do with left-overs when an `ix` removes the old IP range? IMHO it would be helpful to run the migration tool we already have then. @ccaputo, another item for the TODO list IMHO

After the above sanitation script is run once to clean up legacy data, I imagine another script the Admin Committee is going to need is something that can wipe out dependent netixlan records in advance of a particular ixpfx deletion.

But I don't see that as something to detail in the task force policy document.  Rather it will hopefully be a consequence of that document, if the following proposal is adopted by the task force, and thus something to specify in this issue or another issue.:

'In order to prevent operational disruption, this Task Force recommends that PeeringDB be modified to prevent deletion or updates of "ix", "ixlan", and "ixpfx" data elements from having a disruptive effect on dependent "netixlan" data elements, when data exists that would be disrupted.  When needed, the removal of dependent data elements should be coordinated by the Admin Committee.'

**Comment by arnoldnipper** [comment]
> Agreed, we shouldn't just delete it without warning.

Really? Why? The data does not have any operational use. Hence removing the data does not have any operational impact. One of PDB's paradigms is to **delete wrong data**. IP addresses not within the `ix` IP range is **wrong data**.

**Comment by shane-kerr** [comment]
> > Agreed, we shouldn't just delete it without warning.
> 
> Really? Why? The data does not have any operational use. Hence removing the data does not have any operational impact. One of PDB's paradigms is to **delete wrong data**. IP addresses not within the `ix` IP range is **wrong data**.

I don't know how many records we are talking about, but doesn't it seem likely that a human may have made a mistake; a typo for example? Wouldn't it be nice to alert them to this, rather than just silently deleting their invalid records?

**Comment by arnoldnipper** [comment]
From what I've seen (%Netnod) 90% simply is crap. If we send an email we will have to do it via DeskPRO to follow up. If we want to spend that money, fine by me. IMHO it's not worth.

A general notification to announce should do.

**Comment by mcmanuss8** [comment]
I'm just worried about possible blow back from our user base like we had with IX-F integrations blowing away people's data. Do we have a list of the offending records? If so that'll inform how important it is to do the notification. If we're only talking 5-10 we can just email them real quick, it wouldn't be hard to do even manually.

**Comment by arnoldnipper** [comment]
> Do we have a list of the offending records?

Afair @funkestefan has already written a script. [AC](support@peeringdb.com) did have this on their todo list since quite a while already.

And can we agree that we delete IPs silently which obviously are **not** a typo? I.e. if the Hamming distance is > 1.

**Comment by funkestefan** [comment]
Is that script I sent out to you @arnoldnipper? I don't remember. Since I am traveling right now, I do not have access to my workstation at home right now. I will check once I am back.

**Comment by arnoldnipper** [comment]
@funkestefan afais we got stuck last year May. You promised to provide a Python script. But I've never seen one. Let's continue where we were last year.

**Comment by arnoldnipper** [comment]
> If we're only talking 5-10 we can just email them real quick, it wouldn't be hard to do even manually.

To give you an idea, @mcmanuss8. For IPv4 491 `net` with 629 `netixlan` records at 158 `ix` are affected.

**Comment by arnoldnipper** [comment]
I really don't see any benefit of having `netixlan` records where the IP address is outside the IP range. Can anyone please tell me :)

**Comment by ccaputo** [comment]
> I really don't see any benefit of having `netixlan` records where the IP address is outside the IP range. Can anyone please tell me :)

There's no benefit.  I think the concern is that if the data is removed without notifying the user that put it there, they won't know.  And that not knowing means they might just try to put it back (which won't succeed) and/or have some annoyance that data changed without their involvement, if they notice.

Maybe the thing to do here is include a notice in the next pdb-announce@ posting in advance of the next deploy, so that is widely and well-in-advance announced that blatantly invalid prefixes (prefixes that don't match an ix subnet) are going to be removed.  A then also forward that announcement email to each affected Network, in case they don't get pdb-announce@ posts.

**Comment by arnoldnipper** [comment]
Why not make that announcement now already? And repeat it 2x. And have it on social media as well (which happens automagically).

There is no rush to do the clean-up. What about doing it in 6-9 weeks?

**Comment by arnoldnipper** [comment]
*Update:* as Covid-19 gave me some cycles I went through all the entries and was able to correct all entries. There are some left which are due to ongoing migrations resp. one IX which is decommissioned. The most complex one was getting Netnod Stockholm's assignments clean. Also, the API was a big help, because it allows for easy re-location from one IX to another.
