### ISSUE TITLE
IX-F Importer: ticket status change when posting re-occuring conflict to existing resolved ticket

### ISSUE THREAD

**Issue by vegu** [peeringdb/peeringdb#920]
### Problem

Originally reported in #875

The IX-F import currently maintains one ticket on the deskpro end for each ix-f conflict. Meaning that if a ticket gets resolved and the conflict occurs again later down the line, the message will go to the existing ticket, while the ticket status will remain resolved.

#### A

On new IX-F conflict that already has a deskpro ticket use the deskpro api to check the existing ticket status and set it to `awaiting_agent` if it is currently `resolved`.

#### B

Instead create a new ticket for the conflict. This will need us to find a work around to the "Duplicate ticket" error the deskpro api currently returns if a ticket with the same subject already exists. A likely solution here would be to augment the ticket subject with a `YYYY-MM-DD-<proc-id>` suffix.

**Comment by ccaputo** [comment]
@peeringdb/ac please decide re A or B.  Thanks!

**Comment by peterhelmenstine** [comment]
A - I'm leaning for A so that we don't have to bounce between tickets to get the full story. I believe that's similar to how Deskpro works now. We resolve something pending the user's request and if they respond with additional data the same ticket shows up with the full thread of history. Easier than digging for the older ticket imo.

**Comment by DarwinCosta** [comment]
> A - I'm leaning for A so that we don't have to bounce between tickets to get the full story. I believe that's similar to how Deskpro works now. We resolve something pending the user's request and if they respond with additional data the same ticket shows up with the full thread of history. Easier than digging for the older ticket imo.

+1 A.

**Comment by arnoldnipper** [comment]
Clearly B, as this seems to be a **new** issue. Only the parties involved are the same. This is how I read what Stefan writes.

**Comment by ccaputo** [comment]
> Clearly B, as this seems to be a **new** issue. Only the parties involved are the same. This is how I read what Stefan writes.

@arnoldnipper It is a **new** issue in that the **identical** issue will had previously been resolved, but not a new issue in that it is for the **same** conflict, albeit after it had been previously resolved.  It could be a flapping identical conflict of sorts - happening less than a day after previous resolution, or it could be a repeat of the same conflict but months/years later.  The core Subject: would remain the same, such as:

```
Subject: [IX-F] FooIX AS#### 206.##.##.11 2001:##:##::1111 IX-F Conflict Resolution
```

Thus the thought with 'A' is that the previous history for this same conflict will be easily available.

With the above in mind, do you still prefer 'B'?

**Comment by arnoldnipper** [comment]
Yes

**Comment by netravnen** [comment]
Append timestamp to `YYYY-MM-DD`? E.g. `YYYY-MM-DD HH:MM`?

**Comment by leovegoda** [comment]
Is it possible to reach a consensus on how to move forward with this issue so we can schedule it for release 2.27, or is a deeper discussion needed?

**Comment by martinhannigan** [comment]
Question only:

Does ix-f pay for changes that are exclusive to them?? Or is this not
exclusive?

Thanks

**Comment by ccaputo** [comment]
> Question only: Does ix-f pay for changes that are exclusive to them?? Or is this not exclusive? Thanks

@martinhannigan I don't understand your question.  IX-F Pay?

**Comment by martinhannigan** [comment]
I'm trying to come up to speed and contribute. I know sponsorships fund the
expenses. And when I saw your response I doubled back to review the P&L and
the 990. Looks good. As I focus on the different types of records to better
understand, I also came across this in the IX listings: "IX-F Member Export
URL Visibility". Maybe the question is what does this do, and why is it
here? It appears to set a flag that allows a dedicated scraper to use the
record for other purposes. I'm interested in the overall mechanics of how
it all ties together.

I haven't really paid attention to pdb until recently. We are a collection
of competitors and PDB has had some uneven affects as a result of well
intentioned and seemingly minor things so I'm paying attention and trying
to contribute.

Apologies if there is a better list for these questions.

Thanks,

Marty

**Comment by ccaputo** [comment]
Hi @martinhannigan.  Glad to have you participating.

The IX-F (Internet Exchange Federation) has not ever paid PeeringDB.  That said, PeeringDB welcomes additional sponsorships: https://docs.peeringdb.com/misc/PeeringDB_Sponsorship_Levels.pdf

As I understand things (and folks should feel free to correct me where I am wrong), IX-F & Euro-IX developed a common schema for IXPs to use to export details.  This schema is at: https://github.com/euro-ix/json-schemas

Many IXPs export this data.  IXP Manager has this built in, while other IXPs write their own code to do an export.  For example, the SeattleIX's export - which I wrote - is at: https://www.seattleix.net/autogen/participants.json

Multiple entities use the exported data.  Euro-IX uses it for: https://ixpdb.euro-ix.net/

PeeringDB supports the ability for IXPs to cause their IX-F JSON export to be processed by PeeringDB for the purposes of helping to make the data at PeeringDB be more accurate.  We call it the "IX-F Importer" or "IX-F JSON Importer", hence some GitHub issues with this name in the title.  This process runs daily and is documented at: https://docs.peeringdb.com/ix-f-json-import-rules/

Some networks opt to allow the IX-F Importer to automatically populate their entries in cases where IXPs have indicated their presence or departure.  Other networks choose to use the Importer's "hints" to help auto-fill in missing data.  Additionally, conflicted data (such as the wrong network having someone else's IP assignment configured), can result in emails to the network or the IXP and sometimes results in a ticket for the Admin Committee to get involved.  A presentation on these Importer features is up at https://docs.peeringdb.com/presentation/20200817-dtf-implementation.pdf and https://www.youtube.com/watch?v=mtT_HojbIPs .

To finally answer your question: When an IXP configures the URL to be used for their export to PeeringDB, they have a choice of whether to make the URL public or not, with a setting in the "IX-F Member Export URL Visibility" field.  This is needed because some URLs include tokens/passwords to enable PeeringDB to query the data.  Not all IXPs want this data freely accessible, or maybe they want to know who is querying.

This particular GitHub issue has to do with how to handle a duplicate conflict, with respect to whether re-open a previous ticket for the Admin Committee, or whether to create a new ticket.  Generally, this kind of thing would be decided by the committee affected, since it affects their workload.

**Comment by martinhannigan** [comment]
Excellent, comprehensive response that creates multiple branches of review
for me. Thank you, most appreciated.

**Comment by arnoldnipper** [comment]
Still proposal **B**

**Comment by mcmanuss8** [comment]
I think A makes more sense if we could factor in time. Like @ccaputo said, a flapping kind of issues (resolved one day, goes back to broken the next day) would be annoying to get multiple tickets for. But if the delta was, say, a year apart, a new issue would make sense. My (possibly incorrect) read of the thread is that deskpro uses the subject line as a unique key and thus it'd be difficult to add time as a factor. 

I think the decision here really resides with @peeringdb/ac  though as they'll deal with the impact the most. I see two votes for A and one for B. Thus I support A unless @peeringdb/ac comes to a different view.

**Comment by arnoldnipper** [comment]
I change my vote from "B" to "none", making the vote from @peeringdb/ac unanimously "A"

**Comment by arnoldnipper** [comment]
@peeringdb/pc still votes needed to push it further

**Comment by grizz** [comment]
If the AC is happy with the choice, I'm happy! :)

+1

**Comment by grizz** [comment]
@arnoldnipper @mcmanuss8 is that a +1 from both of you?

**Comment by mcmanuss8** [comment]
Yes + 1 from me

**Comment by arnoldnipper** [comment]
+1 from me as well

**Comment by egfrank** [comment]
**Summary**
- On new IX-F conflict that already has a deskpro ticket, use the deskpro api to check the existing ticket status and set it to `awaiting_agent` if it is currently `resolved`
