### ISSUE TITLE
Rework ordering of dependencies

### ISSUE THREAD

**Issue by mcmanuss8** [peeringdb/peeringdb#954]
Right now the base page loads, which includes all the data for the object you're looking at, then it pulls in dependencies (see waterfall from chrome attached).

This is fine on smaller networks/ixes but pretty slow on bigger ones (/net/979 in this example is 2.13s for the base page!)

A more optimal approach would be to load in the base page then make calls to data fetchers (utilizing a spinning wheel or similar to indicate loading) in the background. 
![Screen Shot 2021-03-22 at 1 46 07 PM](https://user-images.githubusercontent.com/5892502/112034538-f884ed80-8b14-11eb-8292-df397811e65e.png)

**Comment by arnoldnipper** [comment]
+1

**Comment by grizz** [comment]
+1
This should be done with the UX changes I think?

**Comment by vegu** [comment]
**summary**

- change the loading of entity lists (netixlan, netfac, ixfac) to be asynchronous and to be done after the page has loaded in order to improve page loading times

**Comment by vegu** [comment]
Updated the summary above, and re-tagging as minor.

Looking at the code that drives this i think it'd be beneficial to first look at why its loading so slow, there might be easy things we can do to speed this up before switching to asynchronous loads for the lists.

The latter comes with a significant overhead since this will affect how the entity editor works as well.
